name = "zoom-dialer"
main = "src/index.ts"
compatibility_date = "2026-06-13"

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "PHONE_STORE"
id = "df957e28ed894d09b824c5a6f938fdeb9"