name = "zoom-dialer"
account_id = "5971da36b2a3b6fec11f642d3ce4e9cd"
workers_dev = true
compatibility_date = "2023-10-01"
main = "src/index.ts"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "PHONE_STORE"
id = "df957e28ed894d0b824c5a6f938fdeb9"
