# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import threading
import time
import collections
import sys
import os
import re
import logging
import json
import traceback
from pathlib import Path
from typing import Optional, Any
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone


_print_lock = threading.Lock()

# ── TUI 出力ブリッジ ──────────────────────────────────────────────────
# safe_print / ツール表示 → _tui_output_callback → RichLog
# AI レスポンス本文    → _tui_stream_callback  → Markdown.update()
_tui_output_callback: Optional[Any] = None  # callable(str) | None
_tui_stream_callback: Optional[Any] = None  # callable(str) | None（生Markdown）
_tui_mode_global: bool = False              # PipelineTypewriter が参照するフラグ


def set_tui_output(fn) -> None:
    """safe_print / ツール表示の出力コールバックを登録する（None で解除）。"""
    global _tui_output_callback
    _tui_output_callback = fn


def set_tui_stream(fn) -> None:
    """AI レスポンス本文（生 Markdown）のストリームコールバックを登録する（None で解除）。"""
    global _tui_stream_callback
    _tui_stream_callback = fn


def set_tui_mode(enabled: bool) -> None:
    """PipelineTypewriter の TUI モードを有効/無効にする。"""
    global _tui_mode_global
    _tui_mode_global = enabled


def safe_print(*args, **kwargs):
    """複数スレッドからの出力が混ざらないようロック制御する print。
    TUI コールバックが登録されている場合はそちらへ出力する。"""
    if _tui_output_callback is not None:
        text = " ".join(str(a) for a in args)
        end  = kwargs.get("end", "\n")
        full = text if (not end or text.endswith(end)) else text + end
        try:
            _tui_output_callback(full)
        except Exception:
            pass
        return
    with _print_lock:
        print(*args, **kwargs)

def _try_read_file_text(path: Path) -> str:
    """UTF-8で読み込みを試行し、失敗した場合は置換して強制的に読み込む。"""
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")

class C:
    """Razer Green 統一テーマ（グリーン + シアン + ホワイト基調）"""
    RESET   = "\033[0m"
    BOLD    = "\033[1m"
    DIM     = "\033[2m"
    # 基調: グリーン／シアン／ホワイト  アクセント: イエロー・レッドのみ
    _RG     = "\033[38;2;0;255;65m"    # Razer Neon Green  #00FF41（メイン）
    _RG_DIM = "\033[38;2;0;160;45m"    # Deep Green        #00A02D（枠線・サブ）
    _WHITE  = "\033[38;2;255;255;255m" # Pure White        #FFFFFF（テキスト）
    _GRAY   = "\033[38;2;0;200;100m"   # Medium Green      #00C864（ラベル）
    _PURPLE = "\033[38;2;0;220;180m"   # Green-Cyan        #00DCB4（AI思考）
    _CYAN   = "\033[38;2;0;240;200m"   # Bright Cyan-Green #00F0C8（ツール結果）
    _RED    = "\033[38;2;255;0;60m"    # Neon Red          #FF003C（エラーのみ）
    _YELLOW = "\033[38;2;255;230;0m"   # Neon Yellow       #FFE600（警告のみ）
    _ORANGE = "\033[38;2;0;255;65m"    # = Razer Green     （並列処理）
    _MEM    = "\033[38;2;0;200;220m"   # Cyan              #00C8DC（メモリ）
    @staticmethod
    def green(s):      return f"{C._RG}{s}{C.RESET}"
    @staticmethod
    def green_dim(s):  return f"{C._RG_DIM}{s}{C.RESET}"
    @staticmethod
    def white(s):      return f"{C._WHITE}{s}{C.RESET}"
    @staticmethod
    def gray(s):       return f"{C._GRAY}{s}{C.RESET}"
    @staticmethod
    def red(s):        return f"{C._RED}{s}{C.RESET}"
    @staticmethod
    def yellow(s):     return f"{C._YELLOW}{s}{C.RESET}"
    @staticmethod
    def cyan(s):       return f"{C._CYAN}{s}{C.RESET}"
    @staticmethod
    def purple(s):     return f"{C._PURPLE}{s}{C.RESET}"
    @staticmethod
    def orange(s):     return f"{C._ORANGE}{s}{C.RESET}"
    @staticmethod
    def mem(s):        return f"{C._MEM}{s}{C.RESET}"
    @staticmethod
    def bold_mem(s):   return f"{C.BOLD}{C._MEM}{s}{C.RESET}"
    @staticmethod
    def bold_green(s): return f"{C.BOLD}{C._RG}{s}{C.RESET}"

def render_markdown(text: str) -> str:
    """
    Markdown テキストを ANSI エスケープコードに変換する。
    対応: 見出し / 太字 / 斜体 / インラインコード / コードブロック /
          箇条書き / 番号リスト / 水平線
    """
    lines = text.split("\n")
    out = []
    in_code_block = False
    code_lang = ""

    for line in lines:
        # ── コードブロック ─────────────────────────────
        if line.startswith("```"):
            if not in_code_block:
                in_code_block = True
                code_lang = line[3:].strip()
                label = f" {code_lang}" if code_lang else ""
                out.append(C.green_dim(f"┌─code{label}"))
            else:
                in_code_block = False
                out.append(C.green_dim("└─"))
            continue

        if in_code_block:
            out.append(f"  {C._RG_DIM}{line}{C.RESET}")
            continue

        # ── 水平線 ─────────────────────────────────────
        if re.match(r"^[-*_]{3,}$", line.strip()):
            out.append(C.green_dim("─" * 40))
            continue

        # ── 見出し ─────────────────────────────────────
        m = re.match(r"^(#{1,4})\s+(.*)", line)
        if m:
            level = len(m.group(1))
            title = _render_inline(m.group(2))
            if level == 1:
                out.append(C.bold_green(f"\n{title}"))
                out.append(C.green("─" * min(len(title) + 2, 50)))
            elif level == 2:
                out.append(C.bold_green(f"\n{title}"))
            elif level == 3:
                out.append(C.green(f"{title}"))
            else:
                out.append(C.gray(f"{title}"))
            continue

        # ── 箇条書き ────────────────────────────────────
        m = re.match(r"^(\s*)[-*+]\s+(.*)", line)
        if m:
            indent = len(m.group(1)) // 2
            bullet = ["•", "◦", "▸"][min(indent, 2)]
            out.append(f"{'  ' * indent}  {C.green(bullet)} {_render_inline(m.group(2))}")
            continue

        # ── 番号リスト ──────────────────────────────────
        m = re.match(r"^(\s*)(\d+)\.\s+(.*)", line)
        if m:
            indent = len(m.group(1)) // 2
            num = m.group(2)
            out.append(f"{'  ' * indent}  {C.green(num + '.')} {_render_inline(m.group(3))}")
            continue

        # ── 通常行 ──────────────────────────────────────
        out.append(_render_inline(line))

    return "\n".join(out)

def _render_inline(text: str) -> str:
    """インライン要素を変換する（Green テーマ）"""
    text = re.sub(r"`([^`]+)`",
                  lambda m: f"{C._RG}{m.group(1)}{C.RESET}", text)
    text = re.sub(r"\*\*(.+?)\*\*|__(.+?)__",
                  lambda m: f"{C.BOLD}{C._WHITE}{m.group(1) or m.group(2)}{C.RESET}", text)
    text = re.sub(r"\*(.+?)\*|_(.+?)_",
                  lambda m: f"{C._PURPLE}{C.DIM}{m.group(1) or m.group(2)}{C.RESET}", text)
    return text


def _render_inline_mem(text: str) -> str:
    """インライン要素を変換する（Aqua テーマ・Thinker 専用）"""
    text = re.sub(r"`([^`]+)`",
                  lambda m: f"{C.BOLD}{C._MEM}{m.group(1)}{C.RESET}", text)
    text = re.sub(r"\*\*(.+?)\*\*|__(.+?)__",
                  lambda m: f"{C.BOLD}{C._WHITE}{m.group(1) or m.group(2)}{C.RESET}", text)
    text = re.sub(r"\*(.+?)\*|_(.+?)_",
                  lambda m: f"{C.DIM}{C._MEM}{m.group(1) or m.group(2)}{C.RESET}", text)
    return text


def render_markdown_thinker(text: str) -> str:
    """Thinker 専用 Markdown レンダラー（Aqua/Mem カラーテーマ）"""
    lines = text.split("\n")
    out = []
    in_code_block = False
    code_lang = ""

    for line in lines:
        if line.startswith("```"):
            if not in_code_block:
                in_code_block = True
                code_lang = line[3:].strip()
                label = f" {code_lang}" if code_lang else ""
                out.append(C.mem(f"┌─code{label}"))
            else:
                in_code_block = False
                out.append(C.mem("└─"))
            continue
        if in_code_block:
            out.append(f"  {C._MEM}{C.DIM}{line}{C.RESET}")
            continue
        if re.match(r"^[-*_]{3,}$", line.strip()):
            out.append(C.mem("─" * 40))
            continue
        m = re.match(r"^(#{1,4})\s+(.*)", line)
        if m:
            level = len(m.group(1))
            title = _render_inline_mem(m.group(2))
            if level == 1:
                out.append(C.bold_mem(f"\n{title}"))
                out.append(C.mem("─" * min(len(title) + 2, 50)))
            elif level == 2:
                out.append(C.bold_mem(f"\n{title}"))
            elif level == 3:
                out.append(C.mem(f"{title}"))
            else:
                out.append(C.gray(f"{title}"))
            continue
        m = re.match(r"^(\s*)[-*+]\s+(.*)", line)
        if m:
            indent = len(m.group(1)) // 2
            bullet = ["•", "◦", "▸"][min(indent, 2)]
            out.append(f"{'  ' * indent}  {C.mem(bullet)} {_render_inline_mem(m.group(2))}")
            continue
        m = re.match(r"^(\s*)(\d+)\.\s+(.*)", line)
        if m:
            indent = len(m.group(1)) // 2
            num = m.group(2)
            out.append(f"{'  ' * indent}  {C.mem(num + '.')} {_render_inline_mem(m.group(3))}")
            continue
        out.append(_render_inline_mem(line))

    return "\n".join(out)


def get_ascii_art_str(subtitle: str = "") -> str:
    """ASCII アートを ANSI コード付き文字列として返す。TUI の Static ウィジェット用。
    pyfiglet の ansi_shadow フォント（ボックス線文字のみ、文字化けなし）を使用。
    Razer グリーン基調のグラデーション。pyfiglet がなければフォールバック。
    """
    try:
        import pyfiglet
        raw   = pyfiglet.figlet_format("MIMIC", font="ansi_shadow")
        body  = [l for l in raw.split("\n") if l.strip()]
    except ImportError:
        body = [
            "███╗   ███╗██╗███╗   ███╗██╗ ██████╗",
            "████╗ ████║██║████╗ ████║██║██╔════╝",
            "██╔████╔██║██║██╔████╔██║██║██║     ",
            "██║╚██╔╝██║██║██║╚██╔╝██║██║██║     ",
            "██║ ╚═╝ ██║██║██║ ╚═╝ ██║██║╚██████╗",
            "╚═╝     ╚═╝╚═╝╚═╝     ╚═╝╚═╝ ╚═════╝",
        ]

    # Razer グリーン → ティール → エレクトリックアクア グラデーション
    COLORS = [
        "\033[38;2;0;255;65m",    # Razer Neon Green
        "\033[38;2;0;255;120m",   # Green-Teal
        "\033[38;2;0;255;180m",   # Teal
        "\033[38;2;0;242;218m",   # Cyan-Green
        "\033[38;2;0;230;255m",   # Electric Aqua
        "\033[38;2;80;215;255m",  # Sky Aqua
    ]
    DIM = "\033[38;2;0;80;80m"
    BLD = "\033[1m"
    R   = C.RESET

    n = len(COLORS)
    art_lines = [
        f"{BLD}{COLORS[min(i, n-1)]}{line}{R}"
        for i, line in enumerate(body)
    ]

    SEP = f"{DIM} {'─' * 50}{R}"
    sub = f"{BLD}{COLORS[-1]} {subtitle or 'THE HYBRID AI AGENT'}{R}"

    return "\n".join(art_lines) + f"\n{SEP}\n{sub}\n{SEP}"


# ── ログシンク（ReactLog への転送用）──────────────────────────────
_log_sink = None  # callable(level: str, message: str) | None

def set_log_sink(fn) -> None:
    """WARNING/ERROR を ReactLog に転送するコールバックを登録する。"""
    global _log_sink
    _log_sink = fn


# ── チームイベントシンク（team.py の team_* イベントを ReactLog に転送）─────
_team_event_sink = None  # callable(event: dict) | None

def set_team_event_sink(fn) -> None:
    """team.py の team_* イベントを ReactLog に転送するコールバックを登録する。"""
    global _team_event_sink
    _team_event_sink = fn


def emit_team_event(event: dict) -> None:
    """team.py から呼ばれる。_team_event_sink が設定されていれば転送する。"""
    if _team_event_sink is not None:
        try:
            _team_event_sink(event)
        except Exception:
            pass


class _ReactSinkHandler(logging.Handler):
    """Python logging の WARNING/ERROR を ReactLog に転送するハンドラ。"""
    def emit(self, record: logging.LogRecord) -> None:
        if _log_sink is None:
            return
        try:
            _log_sink(record.levelname.lower(), self.format(record))
        except Exception:
            pass


def setup_logger(log_file: Optional[str] = None) -> logging.Logger:
    logger = logging.getLogger("openrouter_agent")
    logger.setLevel(logging.DEBUG)
    fmt = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s", datefmt="%Y-%m-%d %H:%M:%S")

    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(fmt)
    logger.addHandler(ch)

    # WARNING 以上を ReactLog にも流す（_log_sink が設定されてから有効になる）
    sink = _ReactSinkHandler()
    sink.setLevel(logging.WARNING)
    sink.setFormatter(fmt)
    logger.addHandler(sink)

    if log_file:
        # 無制限に肥大化するのを防ぐため 5MB x 3世代でローテーションする
        from logging.handlers import RotatingFileHandler
        fh = RotatingFileHandler(log_file, maxBytes=5 * 1024 * 1024, backupCount=3, encoding="utf-8")
        fh.setFormatter(fmt)
        logger.addHandler(fh)

    return logger


def prune_old_sessions(sessions_dir: Path, keep: int = 200) -> int:
    """.mimic/sessions 配下の古いセッションファイル（.md/.jsonl）を直近 keep 件のみ残して削除する。
    起動ごとに呼ぶことでディスク使用量が無限に増え続けるのを防ぐ。戻り値は削除したファイル数。"""
    if not sessions_dir.exists():
        return 0
    latest_mtime: dict[str, float] = {}
    for f in sessions_dir.glob("*.*"):
        if f.suffix not in (".md", ".jsonl"):
            continue
        latest_mtime[f.stem] = max(latest_mtime.get(f.stem, 0.0), f.stat().st_mtime)
    if len(latest_mtime) <= keep:
        return 0
    ordered = sorted(latest_mtime.items(), key=lambda kv: kv[1], reverse=True)
    stale_stems = {stem for stem, _ in ordered[keep:]}
    removed = 0
    for f in sessions_dir.glob("*.*"):
        if f.suffix in (".md", ".jsonl") and f.stem in stale_stems:
            try:
                f.unlink()
                removed += 1
            except OSError:
                pass
    return removed

log = setup_logger(str(Path(__file__).parent / "mimic.log"))

class TokenBucket:
    """
    Token Bucket レートリミッター（RPM専用モード対応）

    ── RPM 制御: Token Bucket ──────────────────────────────────────
    バケツ容量  = rpm_limit トークン（例: 15）
    補充レート  = rpm_limit トークン / 60秒（例: 毎秒 0.25トークン）
    リクエストごとに 1 トークンを消費。

    ── RPD 制御: 日次カウンタ（オプション）────────────────────────
    rpd_limit=0 を指定すると RPD 無制限モード（Gemma 4 等に対応）。
    通常モデルは rpd_limit > 0 で日次上限を管理。

    ── スレッドセーフ ────────────────────────────────────────────────
    全操作を threading.Lock で保護。
    """

    RPD_UNLIMITED = 0  # RPD無制限を示す定数

    def __init__(self, rpm_limit: int = 15, rpd_limit: int = 1500):
        self.rpm_limit = rpm_limit
        self.rpd_limit = rpd_limit  # 0 = 無制限

        self._tokens: float = float(rpm_limit)
        self._last_refill: float = time.monotonic()
        self._refill_rate: float = rpm_limit / 60.0

        # RPD カウンタ（無制限モードでも記録だけはする）
        self._rpd_count: int = 0
        self._rpd_reset_at: datetime = self._next_utc_midnight()

        self._lock = threading.Lock()

    @staticmethod
    def _next_utc_midnight() -> datetime:
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        return (now + timedelta(days=1)).replace(
            hour=0, minute=0, second=0, microsecond=0
        )

    def _refill(self, now_mono: float):
        elapsed = now_mono - self._last_refill
        self._tokens = min(
            float(self.rpm_limit),
            self._tokens + elapsed * self._refill_rate
        )
        self._last_refill = now_mono

    def _check_rpd_reset(self, now_utc: datetime):
        if now_utc >= self._rpd_reset_at:
            self._rpd_count = 0
            self._rpd_reset_at = self._next_utc_midnight()

    @property
    def rpd_unlimited(self) -> bool:
        return self.rpd_limit == self.RPD_UNLIMITED

    def acquire(self) -> tuple[bool, float]:
        """
        トークンを1枚取得しようとする。

        Returns:
            (True, 0.0)           取得成功
            (False, wait_sec)     RPM 不足 → wait_sec 秒後に再挑戦
            (False, float('inf')) RPD 枯渇 → 今日は使用不可（無制限モード時は発生しない）
        """
        with self._lock:
            now_mono = time.monotonic()
            now_utc  = datetime.now(timezone.utc).replace(tzinfo=None)

            self._check_rpd_reset(now_utc)

            # RPD チェック（無制限モードはスキップ）
            if not self.rpd_unlimited and self._rpd_count >= self.rpd_limit:
                return False, float("inf")

            self._refill(now_mono)

            # 浮動小数点誤差を許容 (1e-5)
            if self._tokens >= 1.0 - 1e-5:
                self._tokens = max(0.0, self._tokens - 1.0)
                self._rpd_count += 1
                return True, 0.0

            wait = (1.0 - self._tokens) / self._refill_rate
            # 微小なジッターを追加してCPUの無駄打ちを防止
            return False, wait + 0.01

    def wait_time(self) -> float:
        with self._lock:
            now_mono = time.monotonic()
            elapsed = now_mono - self._last_refill
            projected = min(
                float(self.rpm_limit),
                self._tokens + elapsed * self._refill_rate
            )
            if projected >= 1.0:
                return 0.0
            return (1.0 - projected) / self._refill_rate

    @property
    def tokens_available(self) -> float:
        """現在の利用可能トークン数（表示用）"""
        with self._lock:
            now_mono = time.monotonic()
            elapsed = now_mono - self._last_refill
            return min(
                float(self.rpm_limit),
                self._tokens + elapsed * self._refill_rate
            )


class ThinkAwareBuffer:
    """ストリームチャンクから <think>/<thought> を検出して分割する。
    タグが複数チャンクにまたがる場合も安全に処理する。"""
    _OPEN_TAGS  = ["<think>", "<thought>"]
    _CLOSE_TAGS = ["</think>", "</thought>"]
    _MAX_OPEN_LEN  = max(len(t) for t in _OPEN_TAGS)
    _MAX_CLOSE_LEN = max(len(t) for t in _CLOSE_TAGS)

    def __init__(self):
        self._buf      = ""
        self._in_think = False

    @staticmethod
    def _find_first(buf: str, tags: list) -> tuple:
        """最も早く出現するタグの (index, tag_len) を返す。見つからなければ (-1, 0)。"""
        best_idx, best_len = -1, 0
        for tag in tags:
            i = buf.find(tag)
            if i != -1 and (best_idx == -1 or i < best_idx):
                best_idx, best_len = i, len(tag)
        return best_idx, best_len

    def push(self, chunk: str) -> list[tuple[bool, str]]:
        """チャンクを受け取り (is_think, text) のリストを返す。タグ自体は除去される。"""
        self._buf += chunk
        results: list[tuple[bool, str]] = []
        while self._buf:
            if self._in_think:
                idx, tlen = self._find_first(self._buf, self._CLOSE_TAGS)
                if idx == -1:
                    safe = max(0, len(self._buf) - self._MAX_CLOSE_LEN)
                    if safe:
                        results.append((True, self._buf[:safe]))
                        self._buf = self._buf[safe:]
                    break
                results.append((True, self._buf[:idx]))
                self._buf      = self._buf[idx + tlen:]
                self._in_think = False
            else:
                idx, tlen = self._find_first(self._buf, self._OPEN_TAGS)
                if idx == -1:
                    safe = max(0, len(self._buf) - self._MAX_OPEN_LEN)
                    if safe:
                        results.append((False, self._buf[:safe]))
                        self._buf = self._buf[safe:]
                    break
                if idx > 0:
                    results.append((False, self._buf[:idx]))
                self._buf      = self._buf[idx + tlen:]
                self._in_think = True
        return [(is_t, t) for is_t, t in results if t]

    def _strip_partial_tags(self, text: str, tags: list) -> str:
        """末尾にいずれかの tag の前方一致断片が残っていれば除去する。"""
        for tag in tags:
            for n in range(min(len(tag) - 1, len(text)), 0, -1):
                if tag.startswith(text[-n:]):
                    return text[:-n]
        return text

    def flush(self) -> list[tuple[bool, str]]:
        """残バッファを強制フラッシュする（safe margin なしでタグを正しく処理）。"""
        if not self._buf:
            return []
        results: list[tuple[bool, str]] = []
        while self._buf:
            if self._in_think:
                idx, tlen = self._find_first(self._buf, self._CLOSE_TAGS)
                if idx == -1:
                    content = self._strip_partial_tags(self._buf, self._CLOSE_TAGS)
                    if content:
                        results.append((True, content))
                    self._buf = ""
                    break
                results.append((True, self._buf[:idx]))
                self._buf = self._buf[idx + tlen:]
                self._in_think = False
            else:
                idx, tlen = self._find_first(self._buf, self._OPEN_TAGS)
                if idx == -1:
                    content = self._strip_partial_tags(self._buf, self._OPEN_TAGS)
                    if content:
                        results.append((False, content))
                    self._buf = ""
                    break
                if idx > 0:
                    results.append((False, self._buf[:idx]))
                self._buf = self._buf[idx + tlen:]
                self._in_think = True
        return [(is_t, t) for is_t, t in results if t]


class PipelineTypewriter:
    """
    AIストリーミングを3段パイプラインで表示する:
      Stage1: rawバッファに蓄積（改行 or 200文字超で区切り）
      Stage2: render_markdown でレンダリング（完全行のみ）
      Stage3: タイプライタースレッドが1文字ずつ出力（500文字/秒）
    コードブロックが途中の場合は閉じるまでバッファを保持する。
    auto_mode=True のときは即時出力（遅延なし・レンダリングなし）。
    tui_mode=True のときは _tui_output_callback に直接送る（スレッドなし）。
    <think>...</think> ブロックはグレーのボックスで別レンダリングする。
    """
    _CHARS_PER_SEC = 500
    _BUFFER_SIZE   = 200

    def __init__(self, auto_mode: bool = False, renderer=None):
        self._auto_mode        = auto_mode           # auto_mode と tui_mode を分離
        self._tui_mode         = _tui_mode_global
        self._renderer         = renderer or render_markdown
        self._raw_buf          = ""
        self._think_raw_buf    = ""
        self._think_aware      = ThinkAwareBuffer()
        self._in_think_display = False
        self._disp_q: collections.deque = collections.deque()
        self._full: list[str] = []
        self._done  = False
        self._lock  = threading.Lock()
        self._thread: Optional[threading.Thread] = None

    def _should_flush(self, buf: str) -> bool:
        if "\n" not in buf and len(buf) < self._BUFFER_SIZE:
            return False
        if buf.count("```") % 2 != 0:
            return False
        return True

    @staticmethod
    def _strip_think_tags(text: str) -> str:
        """安全網: 漏れた <think>/<thought> タグを除去する。"""
        return re.sub(r'</?(?:think|thought)>', '', text)

    def _flush_raw(self, force: bool = False):
        if not self._raw_buf:
            return
        last_nl = self._raw_buf.rfind("\n")
        if force or last_nl == -1:
            raw_text = self._strip_think_tags(self._raw_buf)
            self._raw_buf = ""
        else:
            raw_text = self._strip_think_tags(self._raw_buf[:last_nl + 1])
            self._raw_buf = self._raw_buf[last_nl + 1:]

        if self._tui_mode:
            # TUI モード: 生 Markdown テキストをストリームコールバックへ送る。
            # render_markdown() は通さない（Textual の Markdown ウィジェットが処理する）。
            if _tui_stream_callback and raw_text:
                try:
                    _tui_stream_callback(raw_text)
                except Exception:
                    pass
        else:
            rendered = self._renderer(raw_text)
            if not rendered.endswith("\n"):
                rendered += "\n"
            self._disp_q.extend(rendered)

    def _enter_think(self):
        header = f"\n{C._GRAY}╭─ 💭 思考中 {'─' * 50}{C.RESET}\n"
        if self._tui_mode:
            self._tui_send(header)
        else:
            self._disp_q.extend(header)
        self._in_think_display = True

    def _flush_think_raw(self, force: bool = False):
        if not self._think_raw_buf:
            return
        last_nl = self._think_raw_buf.rfind("\n")
        if force or last_nl == -1:
            to_render = self._think_raw_buf
            self._think_raw_buf = ""
        else:
            to_render = self._think_raw_buf[:last_nl + 1]
            self._think_raw_buf = self._think_raw_buf[last_nl + 1:]
        if not to_render:
            return
        rendered = render_markdown_thinker(self._strip_think_tags(to_render))
        result = ""
        for line in rendered.rstrip("\n").split("\n"):
            result += f"{C._GRAY}│{C.RESET} {line}\n"
        if self._tui_mode:
            self._tui_send(result)
        else:
            self._disp_q.extend(result)

    def _exit_think(self):
        self._flush_think_raw(force=True)
        footer = f"{C._GRAY}╰{'─' * 62}{C.RESET}\n"
        if self._tui_mode:
            self._tui_send(footer)
        else:
            self._disp_q.extend(footer)
        self._in_think_display = False

    def _run(self):
        delay = 1.0 / self._CHARS_PER_SEC
        while not self._done or self._disp_q:
            if self._disp_q:
                sys.stdout.write(self._disp_q.popleft())
                sys.stdout.flush()
                time.sleep(delay)
            else:
                time.sleep(0.002)

    def start(self):
        if self._auto_mode or self._tui_mode:
            return  # TUI/auto モードはスレッド不要
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def _tui_send(self, text: str) -> None:
        """TUI モード用: render_markdown 済みテキストをコールバックへ送る。"""
        if _tui_output_callback is not None:
            try:
                _tui_output_callback(text)
            except Exception:
                pass
        else:
            sys.stdout.write(text)
            sys.stdout.flush()

    def feed(self, chunk: str):
        if not chunk:
            return
        self._full.append(chunk)
        if self._auto_mode:
            sys.stdout.write(chunk)
            sys.stdout.flush()
            return
        # TUI モードも通常モードも同じバッファ→render_markdown パイプラインを使う。
        # 出力先だけが _disp_q（通常）か _tui_send（TUI）で異なる。
        with self._lock:
            segments = self._think_aware.push(chunk)
            for is_think, text in segments:
                if is_think and not self._in_think_display:
                    self._flush_raw(force=True)
                    self._enter_think()
                elif not is_think and self._in_think_display:
                    self._exit_think()
                if is_think:
                    self._think_raw_buf += text
                    if self._should_flush(self._think_raw_buf):
                        self._flush_think_raw()
                else:
                    self._raw_buf += text
                    if self._should_flush(self._raw_buf):
                        self._flush_raw()

    def finalize(self) -> str:
        full = "".join(self._full)
        if self._auto_mode:
            return full
        with self._lock:
            for is_think, text in self._think_aware.flush():
                if is_think and not self._in_think_display:
                    self._flush_raw(force=True)
                    self._enter_think()
                elif not is_think and self._in_think_display:
                    self._exit_think()
                if is_think:
                    self._think_raw_buf += text
                else:
                    self._raw_buf += text
            if self._in_think_display:
                self._exit_think()
            if self._raw_buf:
                self._flush_raw(force=True)
        if self._tui_mode:
            return full  # TUI: スレッドなし、join 不要
        self._done = True
        if self._thread and self._thread.is_alive():
            self._thread.join(timeout=60)
        return full


# ── スクラッチパッド共有ステート ──────────────────────────────────────
# agent.py / tools.py / commands.py が遅延インポートなしで参照できる中央管理変数
_current_scratchpad: str = "【現在の進捗】タスクを開始しました。"
_scratchpad_lock = threading.Lock()

def get_scratchpad() -> str:
    with _scratchpad_lock:
        return _current_scratchpad

def set_scratchpad(text: str) -> None:
    global _current_scratchpad
    with _scratchpad_lock:
        _current_scratchpad = text


# ── ツール出力メモリキャッシュ ─────────────────────────────────────
_tool_output_cache: dict[str, str] = {}
_tool_cache_counter: int = 0
_TOOL_CHUNK_SIZE: int = 10000
_TOOL_CACHE_MAX_ENTRIES: int = 50
_tool_cache_lock = threading.Lock()

def cache_obs(tool_name: str, result: str, threshold: int = 2000) -> str:
    """observation短縮用: threshold文字超の結果をキャッシュして先頭+cache_keyを返す。"""
    global _tool_cache_counter
    if len(result) <= threshold:
        return result
    with _tool_cache_lock:
        _tool_cache_counter += 1
        cache_key = f"{tool_name}_{_tool_cache_counter:03d}"
        _tool_output_cache[cache_key] = result
        while len(_tool_output_cache) > _TOOL_CACHE_MAX_ENTRIES:
            del _tool_output_cache[next(iter(_tool_output_cache))]
    total = len(result)
    sliced = result[:threshold]
    remaining = total - threshold
    header = f"[{tool_name} 全{total}文字  cache_key=\"{cache_key}\"]\n"
    footer = f"\n…残り{remaining}文字: read_tool_cache(cache_key=\"{cache_key}\", offset={threshold})"
    return header + sliced + footer


def cache_tool_output(tool_name: str, result: str) -> str:
    """
    ツール出力が _TOOL_CHUNK_SIZE を超える場合はメモリにキャッシュし、
    先頭チャンクと続きの読み方を返す。
    超えない場合はそのまま返す。
    """
    global _tool_cache_counter
    if len(result) <= _TOOL_CHUNK_SIZE:
        return result

    with _tool_cache_lock:
        _tool_cache_counter += 1
        cache_key = f"{tool_name}_{_tool_cache_counter:03d}"
        _tool_output_cache[cache_key] = result
        while len(_tool_output_cache) > _TOOL_CACHE_MAX_ENTRIES:
            del _tool_output_cache[next(iter(_tool_output_cache))]

    total = len(result)
    sliced = result[:_TOOL_CHUNK_SIZE]
    remaining = total - _TOOL_CHUNK_SIZE

    header = f"[{tool_name} の出力  文字 0–{_TOOL_CHUNK_SIZE} / 全{total}文字  cache_key=\"{cache_key}\"]\n{'─' * 60}\n"
    footer = (
        f"\n{'─' * 60}\n"
        f"⚠ 残り {remaining} 文字\n"
        f"  続きを読む: read_tool_cache(cache_key=\"{cache_key}\", offset={_TOOL_CHUNK_SIZE})\n"
        f"{'─' * 60}"
    )
    return header + sliced + footer
