# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import subprocess
import os
import json
import threading
import traceback
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
from .utils import safe_print, C, log


class AutoGit:
    """
    タスク実行時の安全ネット。

    backup()     — タスク開始前にコミット（/undo のベースライン）
    checkpoint() — ファイル書き込み後に自動コミット（細粒度ロールバック）
    rollback()   — 直前のチェックポイント（またはバックアップ）に戻す
    diff()       — バックアップ以降の差分統計を表示
    """

    def __init__(self):
        self._last_backup_hash: Optional[str] = None
        self._checkpoints: list[str] = []  # checkpoint コミットハッシュのスタック

    def _run_git(self, cmd: list[str], cwd: str) -> tuple[int, str, str]:
        import subprocess
        try:
            result = subprocess.run(
                ["git"] + cmd,
                cwd=cwd, capture_output=True, text=True,
                encoding="utf-8", errors="replace", timeout=30,
            )
            return result.returncode, result.stdout.strip(), result.stderr.strip()
        except FileNotFoundError:
            return -1, "", "git が見つかりません（Git未インストール）"
        except Exception as e:
            return -1, "", str(e)

    def _is_git_repo(self, cwd: str) -> bool:
        rc, _, _ = self._run_git(["rev-parse", "--git-dir"], cwd)
        return rc == 0

    def _has_changes(self, cwd: str) -> bool:
        rc, out, _ = self._run_git(["status", "--porcelain"], cwd)
        if rc != 0:
            return False
        # 全ての変更（追跡対象外を含む）を検知する
        all_changes = [l for l in out.splitlines() if l]
        return bool(all_changes)

    def _get_head(self, cwd: str) -> Optional[str]:
        rc, out, _ = self._run_git(["rev-parse", "HEAD"], cwd)
        return out if rc == 0 else None

    def _ensure_git_user(self, cwd: str):
        """git user が未設定ならローカルに設定する"""
        rc, out, _ = self._run_git(["config", "user.email"], cwd)
        if rc != 0 or not out:
            self._run_git(["config", "user.email", "agent@mimic"], cwd)
            self._run_git(["config", "user.name",  "mimic-agent"], cwd)

    def backup(self, cwd: str) -> str:
        """タスク開始前のバックアップコミットを作成する"""
        if not self._is_git_repo(cwd):
            rc, _, err = self._run_git(["init"], cwd)
            if rc != 0:
                return f"git init 失敗: {err}"
            gitignore = Path(cwd) / ".gitignore"
            if not gitignore.exists():
                gitignore.write_text(
                    "__pycache__/\n*.pyc\n*.pyo\n*.log\n", encoding="utf-8"
                )
            safe_print(C.gray(f"  [AutoGit] git init 完了: {cwd}"), flush=True)

        if not self._has_changes(cwd):
            self._last_backup_hash = self._get_head(cwd)
            return "変更なし。バックアップをスキップ。"

        self._ensure_git_user(cwd)
        self._run_git(["add", "."], cwd)
        rc, _, err = self._run_git(
            ["commit", "-m", "🤖 mimic-agent: backup before task"], cwd
        )
        if rc == 0:
            self._last_backup_hash = self._get_head(cwd)
            self._checkpoints = []  # 新タスク開始でスタックをリセット
            h = self._last_backup_hash
            return f"バックアップ完了: {h[:8] if h else '?'}"
        return f"バックアップ失敗: {err}"

    def checkpoint(self, cwd: str, tool: str, path: str = "") -> None:
        """ファイル書き込み後の自動チェックポイントコミット"""
        if not self._is_git_repo(cwd) or not self._has_changes(cwd):
            return
        self._ensure_git_user(cwd)
        file_name = Path(path).name if path else ""
        msg = f"🤖 checkpoint [{tool}]{' ' + file_name if file_name else ''}"
        self._run_git(["add", "."], cwd)
        rc, _, _ = self._run_git(["commit", "-m", msg], cwd)
        if rc == 0:
            h = self._get_head(cwd)
            if h:
                self._checkpoints.append(h)
                safe_print(C.gray(f"  [AutoGit] ✓ {h[:8]} {msg}"), flush=True)

    def rollback(self, cwd: str) -> str:
        """直前のチェックポイント（またはバックアップ）にロールバックする"""
        if not self._is_git_repo(cwd):
            return "Gitリポジトリが見つかりません。"
        if self._checkpoints:
            self._checkpoints.pop()  # 最新チェックポイントを破棄
            target = self._checkpoints[-1] if self._checkpoints else self._last_backup_hash
        else:
            target = self._last_backup_hash
        cmd = ["reset", "--hard", target] if target else ["reset", "--hard", "HEAD~1"]
        rc, _, err = self._run_git(cmd, cwd)
        if rc == 0:
            h = self._get_head(cwd)
            return f"ロールバック完了: {h[:8] if h else '?'} へ戻しました"
        return f"ロールバック失敗: {err}"

    def diff(self, cwd: str) -> str:
        """バックアップ以降の差分統計を返す"""
        if not self._is_git_repo(cwd):
            return "Gitリポジトリが見つかりません。"
        if not self._last_backup_hash:
            return "バックアップが見つかりません（タスクを実行してください）。"
        rc, out, err = self._run_git(
            ["diff", self._last_backup_hash, "HEAD", "--stat"], cwd
        )
        return out if rc == 0 else f"diff 取得失敗: {err}"

class ReactLog:
    """ReActループの Thought / Action / Observation を蓄積・表示・エクスポートする"""

    def __init__(self):
        self.entries: list[dict] = []
        self.session_start: datetime = datetime.now()
        # JSONL 逐次書き込み用
        self._jsonl_path: Optional[Path] = None
        self._jsonl_lock  = threading.Lock()
        # 定期エクスポート用（None = 無効）
        self._auto_export_path: Optional[str] = None
        self._auto_export_interval: int = 0    # 秒
        self._auto_export_timer: Optional[threading.Timer] = None
        self._auto_export_lock = threading.Lock()

    def set_jsonl_path(self, path: Path) -> None:
        """JSONL 逐次書き込み先を設定する。既存ファイルがあれば読み込んで復元する。"""
        path.parent.mkdir(parents=True, exist_ok=True)
        self._jsonl_path = path
        if path.exists():
            try:
                for line in path.read_text(encoding="utf-8").splitlines():
                    line = line.strip()
                    if line:
                        self.entries.append(json.loads(line))
            except Exception as e:
                log.warning({"event": "jsonl_load_error", "error": str(e)})

    # ── 定期エクスポート制御 ──────────────────────────────────────

    def start_auto_export(self, path: str, interval_sec: int):
        """定期エクスポートを開始する。既に動いていれば再スケジュール。"""
        self.stop_auto_export()
        with self._auto_export_lock:
            self._auto_export_path     = path
            self._auto_export_interval = interval_sec
        self._schedule_next()
        log.info({"event": "auto_export_start",
                  "path": path, "interval_sec": interval_sec})

    def stop_auto_export(self):
        """定期エクスポートを停止する。"""
        with self._auto_export_lock:
            if self._auto_export_timer:
                self._auto_export_timer.cancel()
                self._auto_export_timer = None

    def _schedule_next(self):
        """次回タイマーをセットする（内部用）。"""
        with self._auto_export_lock:
            if not self._auto_export_path or self._auto_export_interval <= 0:
                return
            t = threading.Timer(
                self._auto_export_interval, self._fire_export
            )
            t.daemon = True   # プロセス終了時に自動停止
            t.start()
            self._auto_export_timer = t

    def _fire_export(self):
        """タイマーコールバック: エクスポートして次回をスケジュール。"""
        try:
            path = self._auto_export_path
            if path:
                self.export_markdown(path)
                safe_print(
                    C.gray(f"\n  [AutoExport] {Path(path).name} に保存しました "
                           f"({len(self.entries)} エントリ)"),
                    flush=True
                )
        except Exception as e:
            log.warning({"event": "auto_export_error", "error": str(e)})
        self._schedule_next()   # 次回をスケジュール

    @property
    def auto_export_enabled(self) -> bool:
        return bool(self._auto_export_path and self._auto_export_interval > 0)

    def clear(self):
        self.stop_auto_export()
        self.entries = []
        self.session_start = datetime.now()
        # _jsonl_path は保持する（モード切り替え後も同じファイルに書き続ける）
        self._auto_export_path     = None
        self._auto_export_interval = 0

    def add(self, type_: str, **kwargs):
        entry = {
            "type": type_,
            "ts": datetime.now().isoformat(timespec="seconds"),
            **kwargs,
        }
        self.entries.append(entry)
        if self._jsonl_path:
            try:
                with self._jsonl_lock:
                    with open(self._jsonl_path, "a", encoding="utf-8") as f:
                        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
            except Exception as e:
                log.warning({"event": "jsonl_write_error", "error": str(e)})

    def display(self):
        if not self.entries:
            safe_print(C.gray("  (ログなし)"))
            return
        safe_print(f"\n{C.green_dim('─' * 52)}")
        safe_print(C.bold_green("  ReAct Log  ") + C.gray(f"({len(self.entries)} エントリ)"))
        safe_print(C.green_dim("─" * 52))
        for e in self.entries:
            t    = e.get("type", "?")
            step = e.get("step", "?")
            if t == "thought":
                safe_print(f"  {C.purple('💭')} [{step}] {C.purple(e.get('content', ''))}")
            elif t == "action":
                args_str = ", ".join(
                    f"{k}={repr(v)[:30]}" for k, v in e.get("args", {}).items()
                )
                safe_print(f"  {C.bold_green('⚙')}  [{step}] {C.green(e.get('tool', '?'))}{C.cyan(f'({args_str})')}")
            elif t == "observation":
                obs = e.get("result", "")[:150].replace("\n", " ")
                safe_print(f"  {C.cyan('👁')}  [{step}] → {C.cyan(obs)}")
        safe_print(C.green_dim("─" * 52) + "\n")

    def save_session(self, sessions_dir: Path) -> str:
        """タイムスタンプ付きセッションファイルに自動保存する。"""
        sessions_dir.mkdir(parents=True, exist_ok=True)
        ts   = self.session_start.strftime("%Y-%m-%d_%H-%M")
        path = sessions_dir / f"{ts}.md"
        return self.export_markdown(str(path))

    def export_markdown(self, path: str) -> str:
        lines = [
            "# Session Log",
            "",
            f"**開始時刻**: {self.session_start.strftime('%Y-%m-%d %H:%M:%S')}",
            f"**エントリ数**: {len(self.entries)}",
            "",
            "---",
            "",
        ]
        turn         = 0
        current_step = -1
        _LEVEL_ICON  = {"error": "🔴", "warning": "🟡", "info": "ℹ️"}

        for e in self.entries:
            t  = e.get("type", "?")
            ts = e.get("ts", "")

            if t == "user_input":
                turn += 1
                current_step = -1
                lines += [f"## Turn {turn}  `{ts}`", ""]
                lines += [f"**User**: {e.get('content', '')}", "", ""]

            elif t == "final_answer":
                lines += [f"**Result** `{ts}`", "", e.get("content", ""), "", "---", ""]

            elif t == "system_event":
                level = e.get("level", "info")
                icon  = _LEVEL_ICON.get(level, "·")
                lines += [f"{icon} `{ts}` {e.get('content', '')}", ""]

            elif t == "session_start":
                lines += [
                    f"> 🟢 セッション開始 `{ts}`"
                    f"  model=`{e.get('model', '?')}`"
                    f"  provider=`{e.get('provider', '?')}`",
                    "",
                ]

            else:
                step = e.get("step", 0)
                if step != current_step:
                    current_step = step
                    lines += [f"### Step {step}", ""]
                if t == "thought":
                    lines += [f"#### 💭 Thought `{ts}`", "", e.get("content", ""), ""]
                elif t == "action":
                    tool = e.get("tool", "?")
                    args = e.get("args", {})
                    lines += [
                        f"#### ⚙ Action: `{tool}` `{ts}`", "",
                        "```json",
                        json.dumps(args, ensure_ascii=False, indent=2),
                        "```", "",
                    ]
                elif t == "observation":
                    tool   = e.get("tool", "?")
                    result = e.get("result", "")
                    lines += [
                        f"#### 👁 Observation: `{tool}` `{ts}`", "",
                        "```",
                        result[:2000],
                        "```", "",
                    ]

        content = "\n".join(lines)
        out = Path(path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
        return f"エクスポート完了: {path}  ({len(self.entries)} エントリ)"

