# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json
import os
import sys
import time
import re
import threading
from pathlib import Path
from typing import Optional
from .utils import safe_print, C, log, get_scratchpad
from .tools import ExecutionRegistry
from .agent import OpenRouterAgent


cmd_registry = ExecutionRegistry()

@cmd_registry.register("status", "レート制限状態を表示")
def cmd_status(agent: OpenRouterAgent, args: str):
    agent.print_status()

@cmd_registry.register("clear", "会話履歴をリセット")
def cmd_clear(agent: OpenRouterAgent, args: str):
    agent.clear_history()
    safe_print("会話履歴をクリアしました。")

@cmd_registry.register("model", "モデルの確認・変更 (/model → ライブ選択  /model <名前> → 直接指定)")
def cmd_model(agent: OpenRouterAgent, args: str):
    current = agent._config.model
    arg = args.strip()

    if not arg:
        # 引数なし → 起動時と同じライブセレクタを起動
        from .config import select_model_interactively
        new_model, new_ctx = select_model_interactively(agent._config.api_keys[0], current)
        if new_model != current:
            agent._config.model = new_model
            agent._config.context_length = new_ctx
            agent._update_compaction_threshold()
            agent.clear_history()
            safe_print(C.green(f"  ✓ モデルを変更しました: {new_model}"))
            safe_print(C.gray("  会話履歴をリセットしました。"))
        else:
            safe_print(C.gray(f"  モデルは変更されませんでした: {current}"))
        return

    # 引数あり → モデル名を直接指定
    agent._config.model = arg
    agent.clear_history()
    safe_print(C.green(f"  ✓ モデルを変更しました: {arg}"))
    safe_print(C.gray("  会話履歴をリセットしました。"))

@cmd_registry.register("cd", "作業フォルダの確認・変更 (/cd <パス>)")
def cmd_cd(agent: OpenRouterAgent, args: str):
    if not args:
        safe_print(f"  現在の作業フォルダ: {agent.cwd}")
        return
    new_path = args.strip().strip('"').strip("'")
    expanded = str(Path(new_path).expanduser().resolve())
    if Path(expanded).exists():
        agent.set_cwd(expanded)
    else:
        safe_print(f"  フォルダが見つかりません: {expanded}")

@cmd_registry.register("scratchpad", "スクラッチパッドの現在の内容を表示")
def cmd_scratchpad(agent: OpenRouterAgent, args: str):
    safe_print(C.yellow("  ┌─ Scratchpad ──────────────────────────────────────"))
    for line in get_scratchpad().splitlines():
        safe_print(C.gray(f"  │  {line}"))
    safe_print(C.yellow("  └──────────────────────────────────────────────────────"))

@cmd_registry.register("help", "コマンド一覧を表示")
def cmd_help(agent: OpenRouterAgent, args: str):
    safe_print(cmd_registry.help_text())


def _search_sessions(sessions_dir: Path, query: str, max_results: int = 5) -> list[dict]:
    """sessions_dir 内の .jsonl を検索し、ヒットしたターンを返す。"""
    hits = []
    q = query.lower()
    for jf in sorted(sessions_dir.glob("*.jsonl"), reverse=True):
        try:
            lines = jf.read_text(encoding="utf-8").splitlines()
        except Exception:
            continue
        entries = []
        for line in lines:
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except Exception:
                    pass
        # user_input / final_answer のペアを構築してヒット判定
        i = 0
        while i < len(entries):
            e = entries[i]
            if e.get("type") == "user_input":
                user_text   = e.get("content", "")
                answer_text = ""
                # 直後の final_answer を探す（次の user_input まで）
                for j in range(i + 1, len(entries)):
                    if entries[j].get("type") == "user_input":
                        break
                    if entries[j].get("type") == "final_answer":
                        answer_text = entries[j].get("content", "")
                        break
                if q in user_text.lower() or q in answer_text.lower():
                    hits.append({
                        "file":   jf.stem,
                        "ts":     e.get("ts", ""),
                        "user":   user_text[:200],
                        "result": answer_text[:300],
                        "full_user":   user_text,
                        "full_result": answer_text,
                    })
                    if len(hits) >= max_results:
                        return hits
            i += 1
    return hits


def register_search_command(sessions_dir_getter):
    """sessions_dir を返すコールバックを受け取って /search を登録する。"""

    @cmd_registry.register("search", "過去セッションを検索して注入 (/search <クエリ>)")
    def cmd_search(agent: OpenRouterAgent, args: str):
        query = args.strip()
        if not query:
            safe_print(C.gray("  使い方: /search <検索ワード>"))
            return

        sd = sessions_dir_getter()
        if not sd or not sd.exists():
            safe_print(C.yellow("  セッションログがまだありません。"))
            return

        hits = _search_sessions(sd, query)
        if not hits:
            safe_print(C.gray(f"  「{query}」に一致するログが見つかりませんでした。"))
            return

        safe_print(f"\n  {C.bold_green('🔍')} {C.white(repr(query))} — {C.green(str(len(hits)) + '件ヒット')}\n")
        for i, h in enumerate(hits, 1):
            safe_print(C.green_dim(f"  ┌─ [{i}] {h['file']}  {h['ts']} ─────────────────────"))
            safe_print(f"  {C.bold_green('User')}  : {C.white(h['user'])}")
            if h["result"]:
                safe_print(f"  {C.green('Result')}: {C.gray(h['result'])}")
            safe_print(C.green_dim("  └" + "─" * 55))
            safe_print()

        safe_print(C.yellow(f"  コンテキストに注入しますか？ [番号をカンマ区切り / all / n]: "), end="", flush=True)
        try:
            resp = sys.stdin.readline().strip().lower()
        except (EOFError, KeyboardInterrupt):
            safe_print()
            return

        if not resp or resp == "n":
            return

        selected = hits if resp == "all" else []
        if resp != "all":
            for token in resp.split(","):
                token = token.strip()
                if token.isdigit():
                    idx = int(token) - 1
                    if 0 <= idx < len(hits):
                        selected.append(hits[idx])

        if not selected:
            return

        inject_lines = [f"[過去セッションの参考情報（/search {query}）]"]
        for h in selected:
            inject_lines.append(f"\nUser: {h['full_user']}")
            if h["full_result"]:
                inject_lines.append(f"Result: {h['full_result']}")
        inject_text = "\n".join(inject_lines)
        agent.conversation.append({"role": "user",      "content": inject_text})
        agent.conversation.append({"role": "assistant", "content": "了解しました。参考情報を確認しました。"})
        safe_print(C.green(f"  ✓ {len(selected)} 件をコンテキストに注入しました。"))


def _parse_session_file(path: Path) -> dict:
    """JSONL セッションファイルをパースしてターン情報を返す。"""
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except Exception:
        return {}

    entries = []
    for line in lines:
        line = line.strip()
        if line:
            try:
                entries.append(json.loads(line))
            except Exception:
                pass

    model = ""
    provider = ""
    turns = []
    current_turn = None

    for e in entries:
        t = e.get("type", "")
        if t == "session_start":
            model = e.get("model", "")
            provider = e.get("provider", "")
        elif t == "user_input":
            if current_turn is not None:
                turns.append(current_turn)
            current_turn = {
                "user": e.get("content", ""),
                "ts": e.get("ts", ""),
                "tools": [],
                "answer": "",
            }
        elif t == "tool_call" and current_turn is not None:
            tool_name = e.get("tool", "") or e.get("content", "")[:30]
            if tool_name and tool_name not in current_turn["tools"]:
                current_turn["tools"].append(tool_name)
        elif t == "final_answer" and current_turn is not None:
            current_turn["answer"] = e.get("content", "")

    if current_turn is not None:
        turns.append(current_turn)

    return {
        "file": path.stem,
        "path": path,
        "model": model,
        "provider": provider,
        "turns": turns,
    }


def _print_sessions_list(sessions: list[dict]):
    """セッション一覧を番号付きで表示する。"""
    if not sessions:
        safe_print(C.gray("  セッションログがまだありません。"))
        return

    safe_print(f"\n  {C.bold_green('過去セッション一覧')}  ({len(sessions)} 件)\n")
    for i, s in enumerate(sessions, 1):
        turns = s.get("turns", [])
        model = s.get("model", "不明")
        date_str = s.get("file", "")
        first_q = turns[0]["user"][:60].replace("\n", " ") if turns else "(空)"
        safe_print(
            C.green_dim(f"  [{i:2d}]") + f" {C.white(date_str)}"
            + C.gray(f"  {len(turns)}ターン  {model[:40]}")
        )
        safe_print(f"       {C.gray(first_q)}")
    safe_print()


def _print_session_detail(session: dict):
    """セッションの全ターンを表示する。"""
    if not session:
        safe_print(C.red("  セッションが見つかりません。"))
        return

    turns = session.get("turns", [])
    model = session.get("model", "不明")
    date_str = session.get("file", "")

    safe_print(f"\n  {C.bold_green('セッション詳細')}  {C.white(date_str)}")
    safe_print(C.gray(f"  モデル: {model}  /  {len(turns)} ターン\n"))

    for i, turn in enumerate(turns, 1):
        safe_print(C.green_dim(f"  ┌─ Turn {i}  {turn.get('ts', '')} ────────────────"))
        safe_print(f"  {C.bold_green('User')} : {C.white(turn['user'][:200])}")
        if turn.get("tools"):
            safe_print(f"  {C.green('Tools')}: {C.gray(', '.join(turn['tools']))}")
        if turn.get("answer"):
            answer_preview = turn["answer"][:300].replace("\n", " ")
            safe_print(f"  {C.green('Answer')}: {C.gray(answer_preview)}")
        safe_print(C.green_dim("  └" + "─" * 50))
        safe_print()


def register_sessions_command(sessions_dir_getter):
    """sessions_dir を返すコールバックを受け取って /sessions を登録する。"""

    @cmd_registry.register("sessions", "過去セッション一覧の表示・詳細閲覧 (/sessions [番号])")
    def cmd_sessions(agent: OpenRouterAgent, args: str):
        sd = sessions_dir_getter()
        if not sd or not sd.exists():
            safe_print(C.yellow("  セッションログがまだありません。"))
            return

        jsonl_files = sorted(sd.glob("*.jsonl"), reverse=True)
        if not jsonl_files:
            safe_print(C.yellow("  セッションログがまだありません。"))
            return

        sessions = [_parse_session_file(f) for f in jsonl_files]
        sessions = [s for s in sessions if s]

        arg = args.strip()
        if not arg:
            _print_sessions_list(sessions)
            return

        if arg.isdigit():
            idx = int(arg) - 1
            if 0 <= idx < len(sessions):
                _print_session_detail(sessions[idx])
            else:
                safe_print(C.red(f"  番号 {arg} のセッションが見つかりません（1〜{len(sessions)}）。"))
            return

        matched = [s for s in sessions if arg in s.get("file", "")]
        if len(matched) == 1:
            _print_session_detail(matched[0])
        elif len(matched) > 1:
            safe_print(C.yellow(f"  {len(matched)} 件ヒットしました。番号で絞り込んでください:"))
            _print_sessions_list(matched)
        else:
            safe_print(C.gray(f"  「{arg}」に一致するセッションが見つかりません。"))

