# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json
import os
import sys
import time
import re
import threading
from pathlib import Path
from typing import Optional
from .utils import safe_print, C, log, get_scratchpad
from .tools import ExecutionRegistry
from .agent import OpenRouterAgent


cmd_registry = ExecutionRegistry()

@cmd_registry.register("status", "レート制限状態を表示")
def cmd_status(agent: OpenRouterAgent, args: str):
    agent.print_status()

@cmd_registry.register("clear", "会話履歴をリセット")
def cmd_clear(agent: OpenRouterAgent, args: str):
    from .team import clear_delegation_history
    agent.clear_history()
    clear_delegation_history()  # 委任履歴・書き込みストリークも同時にリセット
    safe_print("会話履歴をクリアしました。")

@cmd_registry.register("model", "モデルの確認・変更 (/model → ライブ選択  /model <名前> → 直接指定)")
def cmd_model(agent: OpenRouterAgent, args: str):
    current = agent._config.model
    arg = args.strip()

    if not arg:
        # 引数なし → ライブセレクタを起動
        from .config import select_model_interactively_multi, GoogleAIConfig
        cfg = agent._config
        # 現在のプロバイダーだけを渡す（もう一方は None）
        if isinstance(cfg, GoogleAIConfig):
            new_config = select_model_interactively_multi(None, cfg)
        else:
            new_config = select_model_interactively_multi(cfg, None)
        if new_config.model != current:
            agent._config.model          = new_config.model
            agent._config.context_length = new_config.context_length
            agent._update_compaction_threshold()
            agent.clear_history()
            safe_print(C.green(f"  ✓ モデルを変更しました: {new_config.model}"))
            safe_print(C.gray("  会話履歴をリセットしました。"))
        else:
            safe_print(C.gray(f"  モデルは変更されませんでした: {current}"))
        return

    # 引数あり → モデル名を直接指定
    agent._config.model = arg
    agent.clear_history()
    safe_print(C.green(f"  ✓ モデルを変更しました: {arg}"))
    safe_print(C.gray("  会話履歴をリセットしました。"))

@cmd_registry.register("mode", "エージェントモードの確認・切替 (/mode specialist|interactive)")
def cmd_mode(agent: OpenRouterAgent, args: str):
    safe_print(C.gray(
        "  切替: /mode specialist（動的ロール委任・標準）  /mode interactive（通常のReAct・退避用）"
    ))

@cmd_registry.register("cd", "作業フォルダの確認・変更 (/cd <パス>)")
def cmd_cd(agent: OpenRouterAgent, args: str):
    if not args:
        safe_print(f"  現在の作業フォルダ: {agent.cwd}")
        return
    new_path = args.strip().strip('"').strip("'")
    expanded = str(Path(new_path).expanduser().resolve())
    if Path(expanded).exists():
        agent.set_cwd(expanded)
    else:
        safe_print(f"  フォルダが見つかりません: {expanded}")

@cmd_registry.register("scratchpad", "スクラッチパッドの現在の内容を表示")
def cmd_scratchpad(agent: OpenRouterAgent, args: str):
    safe_print(C.yellow("  ┌─ Scratchpad ──────────────────────────────────────"))
    for line in get_scratchpad().splitlines():
        safe_print(C.gray(f"  │  {line}"))
    safe_print(C.yellow("  └──────────────────────────────────────────────────────"))

@cmd_registry.register("help", "コマンド一覧を表示")
def cmd_help(agent: OpenRouterAgent, args: str):
    safe_print(cmd_registry.help_text())


def _search_sessions(sessions_dir: Path, query: str, max_results: int = 5) -> list[dict]:
    """sessions_dir 内の .jsonl を検索し、ヒットしたターンを返す。"""
    hits = []
    q = query.lower()
    for jf in sorted(sessions_dir.glob("*.jsonl"), reverse=True):
        try:
            lines = jf.read_text(encoding="utf-8").splitlines()
        except Exception:
            continue
        entries = []
        for line in lines:
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except Exception:
                    pass
        # user_input / final_answer のペアを構築してヒット判定
        i = 0
        while i < len(entries):
            e = entries[i]
            if e.get("type") == "user_input":
                user_text   = e.get("content", "")
                answer_text = ""
                # 直後の final_answer を探す（次の user_input まで）
                for j in range(i + 1, len(entries)):
                    if entries[j].get("type") == "user_input":
                        break
                    if entries[j].get("type") == "final_answer":
                        answer_text = entries[j].get("content", "")
                        break
                if q in user_text.lower() or q in answer_text.lower():
                    hits.append({
                        "file":   jf.stem,
                        "ts":     e.get("ts", ""),
                        "user":   user_text[:200],
                        "result": answer_text[:300],
                        "full_user":   user_text,
                        "full_result": answer_text,
                    })
                    if len(hits) >= max_results:
                        return hits
            i += 1
    return hits


def register_search_command(sessions_dir_getter):
    """sessions_dir を返すコールバックを受け取って /search を登録する。"""

    @cmd_registry.register("search", "過去セッションを検索して注入 (/search <クエリ>)")
    def cmd_search(agent: OpenRouterAgent, args: str):
        query = args.strip()
        if not query:
            safe_print(C.gray("  使い方: /search <検索ワード>"))
            return

        sd = sessions_dir_getter()
        if not sd or not sd.exists():
            safe_print(C.yellow("  セッションログがまだありません。"))
            return

        hits = _search_sessions(sd, query)
        if not hits:
            safe_print(C.gray(f"  「{query}」に一致するログが見つかりませんでした。"))
            return

        safe_print(f"\n  {C.bold_green('🔍')} {C.white(repr(query))} — {C.green(str(len(hits)) + '件ヒット')}\n")
        for i, h in enumerate(hits, 1):
            safe_print(C.green_dim(f"  ┌─ [{i}] {h['file']}  {h['ts']} ─────────────────────"))
            safe_print(f"  {C.bold_green('User')}  : {C.white(h['user'])}")
            if h["result"]:
                safe_print(f"  {C.green('Result')}: {C.gray(h['result'])}")
            safe_print(C.green_dim("  └" + "─" * 55))
            safe_print()

        safe_print(C.yellow(f"  コンテキストに注入しますか？ [番号をカンマ区切り / all / n]: "), end="", flush=True)
        try:
            resp = sys.stdin.readline().strip().lower()
        except (EOFError, KeyboardInterrupt):
            safe_print()
            return

        if not resp or resp == "n":
            return

        selected = hits if resp == "all" else []
        if resp != "all":
            for token in resp.split(","):
                token = token.strip()
                if token.isdigit():
                    idx = int(token) - 1
                    if 0 <= idx < len(hits):
                        selected.append(hits[idx])

        if not selected:
            return

        inject_lines = [f"[過去セッションの参考情報（/search {query}）]"]
        for h in selected:
            inject_lines.append(f"\nUser: {h['full_user']}")
            if h["full_result"]:
                inject_lines.append(f"Result: {h['full_result']}")
        inject_text = "\n".join(inject_lines)
        agent.conversation.append({"role": "user",      "content": inject_text})
        agent.conversation.append({"role": "assistant", "content": "了解しました。参考情報を確認しました。"})
        safe_print(C.green(f"  ✓ {len(selected)} 件をコンテキストに注入しました。"))


def _parse_session_file(path: Path) -> dict:
    """JSONL セッションファイルをパースしてターン情報を返す。"""
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except Exception:
        return {}

    entries = []
    for line in lines:
        line = line.strip()
        if line:
            try:
                entries.append(json.loads(line))
            except Exception:
                pass

    model = ""
    provider = ""
    turns = []
    current_turn = None

    for e in entries:
        t = e.get("type", "")
        if t == "session_start":
            model = e.get("model", "")
            provider = e.get("provider", "")
        elif t == "user_input":
            if current_turn is not None:
                turns.append(current_turn)
            current_turn = {
                "user": e.get("content", ""),
                "ts": e.get("ts", ""),
                "tools": [],
                "answer": "",
            }
        elif t == "tool_call" and current_turn is not None:
            tool_name = e.get("tool", "") or e.get("content", "")[:30]
            if tool_name and tool_name not in current_turn["tools"]:
                current_turn["tools"].append(tool_name)
        elif t == "final_answer" and current_turn is not None:
            current_turn["answer"] = e.get("content", "")

    if current_turn is not None:
        turns.append(current_turn)

    return {
        "file": path.stem,
        "path": path,
        "model": model,
        "provider": provider,
        "turns": turns,
    }


def _print_sessions_list(sessions: list[dict]):
    """セッション一覧を番号付きで表示する。"""
    if not sessions:
        safe_print(C.gray("  セッションログがまだありません。"))
        return

    safe_print(f"\n  {C.bold_green('過去セッション一覧')}  ({len(sessions)} 件)\n")
    for i, s in enumerate(sessions, 1):
        turns = s.get("turns", [])
        model = s.get("model", "不明")
        date_str = s.get("file", "")
        first_q = turns[0]["user"][:60].replace("\n", " ") if turns else "(空)"
        safe_print(
            C.green_dim(f"  [{i:2d}]") + f" {C.white(date_str)}"
            + C.gray(f"  {len(turns)}ターン  {model[:40]}")
        )
        safe_print(f"       {C.gray(first_q)}")
    safe_print()


def _print_session_detail(session: dict):
    """セッションの全ターンを表示する。"""
    if not session:
        safe_print(C.red("  セッションが見つかりません。"))
        return

    turns = session.get("turns", [])
    model = session.get("model", "不明")
    date_str = session.get("file", "")

    safe_print(f"\n  {C.bold_green('セッション詳細')}  {C.white(date_str)}")
    safe_print(C.gray(f"  モデル: {model}  /  {len(turns)} ターン\n"))

    for i, turn in enumerate(turns, 1):
        safe_print(C.green_dim(f"  ┌─ Turn {i}  {turn.get('ts', '')} ────────────────"))
        safe_print(f"  {C.bold_green('User')} : {C.white(turn['user'][:200])}")
        if turn.get("tools"):
            safe_print(f"  {C.green('Tools')}: {C.gray(', '.join(turn['tools']))}")
        if turn.get("answer"):
            answer_preview = turn["answer"][:300].replace("\n", " ")
            safe_print(f"  {C.green('Answer')}: {C.gray(answer_preview)}")
        safe_print(C.green_dim("  └" + "─" * 50))
        safe_print()


def build_session_inject_text(session: dict) -> str:
    """選択したセッションの全ターン内容を、コンテキスト注入用のテキストにまとめる。"""
    file_name = session.get("file", "")
    turns = session.get("turns", [])
    inject_lines = [f"[過去セッションの参考情報（/sessions {file_name}）]"]
    for i, turn in enumerate(turns, 1):
        inject_lines.append(f"\nTurn {i} User: {turn['user']}")
        if turn.get("tools"):
            inject_lines.append(f"Tools: {', '.join(turn['tools'])}")
        if turn.get("answer"):
            inject_lines.append(f"Answer: {turn['answer']}")
    return "\n".join(inject_lines)


def resolve_session(sessions: list[dict], arg: str) -> "tuple[Optional[dict], list[dict]]":
    """番号またはファイル名の一部から、セッションを1件に絞り込む。

    戻り値: (該当セッション or None, 複数ヒット時の候補リスト)
    """
    arg = arg.strip()
    if arg.isdigit():
        idx = int(arg) - 1
        if 0 <= idx < len(sessions):
            return sessions[idx], []
        return None, []

    matched = [s for s in sessions if arg in s.get("file", "")]
    if len(matched) == 1:
        return matched[0], []
    return None, matched


def register_viewer_command(sessions_dir_getter):
    """sessions_dir を返すコールバックを受け取って /viewer を登録する。"""

    @cmd_registry.register("viewer", "ローカル観測ビューアを起動してURLを表示")
    def cmd_viewer(agent: OpenRouterAgent, args: str):
        sd = sessions_dir_getter()
        if not sd or not sd.exists():
            safe_print(C.yellow("  セッションログがまだありません。"))
            return
        from .viewer import start_viewer_server
        url = start_viewer_server(sd)
        safe_print(C.green(f"  ✓ 観測ビューアを起動しました: {url}"))


def register_sessions_command(sessions_dir_getter):
    """sessions_dir を返すコールバックを受け取って /sessions を登録する。"""

    @cmd_registry.register("sessions", "過去セッション一覧の表示・詳細閲覧・コンテキスト注入 (/sessions [番号])")
    def cmd_sessions(agent: OpenRouterAgent, args: str):
        sd = sessions_dir_getter()
        if not sd or not sd.exists():
            safe_print(C.yellow("  セッションログがまだありません。"))
            return

        jsonl_files = sorted(sd.glob("*.jsonl"), reverse=True)
        if not jsonl_files:
            safe_print(C.yellow("  セッションログがまだありません。"))
            return

        sessions = [_parse_session_file(f) for f in jsonl_files]
        sessions = [s for s in sessions if s]

        arg = args.strip()
        if not arg:
            _print_sessions_list(sessions)
            return

        session, ambiguous = resolve_session(sessions, arg)
        if session is not None:
            _print_session_detail(session)
            return

        if ambiguous:
            safe_print(C.yellow(f"  {len(ambiguous)} 件ヒットしました。番号で絞り込んでください:"))
            _print_sessions_list(ambiguous)
        elif arg.isdigit():
            safe_print(C.red(f"  番号 {arg} のセッションが見つかりません（1〜{len(sessions)}）。"))
        else:
            safe_print(C.gray(f"  「{arg}」に一致するセッションが見つかりません。"))


def register_bench_command():
    """.mimic/ 配下の実績ログ（skill_trust.json / mcp_policy.json / verify_cmds.json /
    sessions/*.jsonl）を集計してレポートを表示する /bench を登録する(bench設計書 Track A P1)。
    新しいベンチマーク問題集は作らない — 既存ログを読むだけ。"""

    @cmd_registry.register(
        "bench",
        "実績ログを集計してベンチマークレポートを表示・保存 (/bench)",
    )
    def cmd_bench(agent: OpenRouterAgent, args: str):
        from . import mimic_bench

        report = mimic_bench.run()
        safe_print(C.gray(
            f"\n  (スナップショットを .mimic/bench_history/ に保存、"
            f"レポートは latest_report.md にも書き出し済み)\n"
        ))
        safe_print(report)


def register_skills_command():
    """.claude/skills/ から読み込んだSkillの一覧・信頼スコアを表示する /skills を登録する
    (design doc P1)。/skills reload でディレクトリを再スキャンする。"""

    @cmd_registry.register(
        "skills",
        "利用可能なSkill一覧と信頼スコアを表示 (/skills | /skills reload)",
    )
    def cmd_skills(agent: OpenRouterAgent, args: str):
        from .skills import registry as skill_registry, default_skill_dirs, _load_trust

        arg = args.strip().lower()
        if arg == "reload":
            n = skill_registry.scan(default_skill_dirs())
            safe_print(C.gray(f"  再スキャン完了: {n} 件のSkillを読み込みました。"))
            return
        if not skill_registry.list_summaries():
            skill_registry.scan(default_skill_dirs())

        skills = skill_registry.list_summaries()
        if not skills:
            safe_print(C.gray(
                "  利用可能なSkillはありません（~/.claude/skills, .claude/skills にSKILL.mdが見つかりません）。"
            ))
            return

        trust = _load_trust()
        safe_print(f"\n  {C.bold_green('利用可能なSkill')}  ({len(skills)} 件)\n")
        for sk in skills:
            t = trust.get(sk.name)
            if t:
                p, f = t.get("pass_count", 0), t.get("fail_count", 0)
                score = C.green(f"✓通過{p}回") if p and not f else (
                    C.yellow(f"✓{p} / ✗{f}") if p or f else C.gray("記録なし"))
            else:
                score = C.gray("※未検証")
            safe_print(f"  {C.green_dim(sk.name)}  [{score}]")
            safe_print(f"      {sk.description[:120]}")
        safe_print(C.gray(
            "\n  本文は load_skill(name) で遅延ロードされます。再スキャン: /skills reload\n"
        ))


def register_mcp_command():
    """接続済みMCPサーバーの一覧・再接続・信頼設定を行う /mcp を登録する
    (design doc P0/P1)。Directorプロセスでのみ登録すること。"""

    @cmd_registry.register(
        "mcp",
        "MCPサーバーの一覧・状態表示 (/mcp | /mcp reconnect <server> | /mcp trust <server> [read-only|off])",
    )
    def cmd_mcp(agent: OpenRouterAgent, args: str):
        from . import mcp_client

        parts = args.strip().split()
        action = parts[0].lower() if parts else ""

        if action == "reconnect" and len(parts) >= 2:
            safe_print(mcp_client.reconnect(parts[1]))
            return

        if action == "trust" and len(parts) >= 2:
            server = parts[1]
            mode = parts[2].lower() if len(parts) >= 3 else "read-only"
            if mode not in ("read-only", "off"):
                safe_print(C.gray("  使い方: /mcp trust <server> [read-only|off]"))
                return
            trust_value = "read-only" if mode == "read-only" else ""
            mcp_client.set_server_trust(server, trust_value)
            if trust_value:
                safe_print(C.yellow(
                    f"  ⚠ '{server}' を read-only 信頼設定にしました。以後、書込み承認なしで呼び出されます。"
                    "実際に書込みを行うサーバーには設定しないでください。"
                ))
            else:
                safe_print(C.gray(f"  '{server}' の信頼設定を解除しました（以後すべて承認必須）。"))
            return

        if action and action not in ("reconnect", "trust"):
            safe_print(C.gray("  使い方: /mcp | /mcp reconnect <server> | /mcp trust <server> [read-only|off]"))
            return

        statuses = mcp_client.list_status()
        if not statuses:
            safe_print(C.gray(
                "  接続対象のMCPサーバーはありません（~/.mcp.json, ./.mcp.json に mcpServers が見つかりません）。"
            ))
            return
        safe_print(f"\n  {C.bold_green('MCPサーバー')}  ({len(statuses)} 件)\n")
        for s in statuses:
            if s["connected"]:
                badge = C.green(f"✓ 接続中 ({s['tool_count']}ツール)")
            else:
                badge = C.red(f"✗ 未接続 ({s.get('error') or '?'})")
            safe_print(f"  {C.green_dim(s['name'])}  [{badge}]  {C.gray(s['command'])}")
        safe_print(C.gray(
            "\n  再接続: /mcp reconnect <server>   信頼設定: /mcp trust <server> read-only\n"
        ))


def register_delegations_command():
    """Directorプロセスのクラッシュ等で中断された delegate_to_team/delegate_to_worker
    の一覧表示・再開・破棄を行う /delegations を登録する。
    Worker（--auto-prompt サブエージェント）側では登録しないこと。
    """

    @cmd_registry.register(
        "delegations",
        "中断された委任タスクの一覧・再開・破棄 (/delegations | /delegations resume <番号> | /delegations discard <番号>)",
    )
    def cmd_delegations(agent: OpenRouterAgent, args: str):
        from .team import list_orphaned_delegations, resume_delegation, discard_delegation

        entries = list_orphaned_delegations()
        parts = args.strip().split(maxsplit=1)
        action = parts[0].lower() if parts else ""

        if not action:
            if not entries:
                safe_print(C.gray("  中断中の委任タスクはありません。"))
                return
            safe_print(f"\n  {C.bold_green('中断中の委任タスク')}  ({len(entries)} 件)\n")
            for i, e in enumerate(entries, 1):
                age = e.get("checkpoint_age_sec")
                if age is None:
                    age_str = "進行状況不明"
                elif age < 90:
                    age_str = f"{age:.0f}秒前に更新（まだ実行中の可能性あり）"
                else:
                    age_str = f"{age/60:.0f}分前に更新"
                task_preview = e.get("task", "")[:80].replace("\n", " ")
                safe_print(
                    C.green_dim(f"  [{i}] ") + f"trace_id={e['trace_id']}  "
                    + C.gray(f"({e.get('kind', '?')}, {age_str})")
                )
                safe_print(f"      {task_preview}")
            safe_print(C.gray("\n  再開: /delegations resume <番号>   破棄: /delegations discard <番号>\n"))
            return

        if action not in ("resume", "discard"):
            safe_print(C.gray(
                "  使い方: /delegations | /delegations resume <番号> | /delegations discard <番号>"
            ))
            return

        if len(parts) < 2 or not parts[1].strip().isdigit():
            safe_print(C.gray(f"  使い方: /delegations {action} <番号>"))
            return

        idx = int(parts[1].strip()) - 1
        if not entries or not (0 <= idx < len(entries)):
            safe_print(C.red(f"  番号 {parts[1]} のタスクが見つかりません（/delegations で一覧を確認してください）。"))
            return

        trace_id = entries[idx]["trace_id"]
        if action == "resume":
            safe_print(C.gray(f"  trace_id={trace_id} を再開しています..."))
            result = resume_delegation(trace_id)
        else:
            result = discard_delegation(trace_id)
        safe_print(result)

