# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import sys
import os
import re
import json
import time
import threading
import io
import traceback
from pathlib import Path
from typing import Optional
from dataclasses import dataclass, field

_ANSI_RE = re.compile(r'\033\[[^m]*m')

def _rl(s: str) -> str:
    """readline 向けに ANSI コードを \001...\002 で囲み幅ゼロと認識させる。"""
    return _ANSI_RE.sub(r'\001\g<0>\002', s)
from .utils import safe_print, C, log, render_markdown
from .config import load_config, OpenRouterConfig
from .agent import OpenRouterAgent
from .tools import ToolRegistry, tools, set_write_approval_handler
from .autogit import AutoGit
from .orchestrator import InteractiveOrchestrator, AgentOrchestrator
from .commands import cmd_registry


def interactive_loop(
    agent: "OpenRouterAgent",
    orchestrator: "AgentOrchestrator",
    interactive_orch: "InteractiveOrchestrator",
    auto_git: "AutoGit",
    react_prompt: str,
    plan_prompt: str,
    sessions_dir: "Optional[Path]" = None,
):
    """
    ハイブリッドエージェントのメインループ。

    interactive (ReAct) モードと plan (Plan-and-Execute) モードを
    /mode コマンドでシームレスに切り替えられる。
    デフォルトは interactive モード。
    """
    _APPROVAL_TIMEOUT = 30  # 秒数未入力で自動承認するタイムアウト

    def _react_approval_handler(tool_name: str, args: dict, preview: str) -> bool:
        from .utils import safe_print, C
        path = args.get("path", "?")
        safe_print(C.yellow(f"\n  ┌─ 書き込み確認 ──────────────────────────────────────"))
        safe_print(C.yellow(f"  │  ツール : {tool_name}"))
        safe_print(C.yellow(f"  │  ファイル: {path}"))
        safe_print(C.yellow(f"  │"))
        for line in preview.splitlines():
            safe_print(C.gray(f"  │  {line}"))
        safe_print(C.yellow(f"  └──────────────────────────────────────────────────────"))
        safe_print(
            C.bold_green(f"  実行しますか？ [Y/n] ({_APPROVAL_TIMEOUT}秒で自動承認): "),
            end="", flush=True,
        )

        response_holder: list[str] = []

        def _read_stdin():
            try:
                response_holder.append(sys.stdin.readline().strip().lower())
            except (EOFError, KeyboardInterrupt):
                response_holder.append("n")

        t = threading.Thread(target=_read_stdin, daemon=True)
        t.start()
        t.join(timeout=_APPROVAL_TIMEOUT)

        if t.is_alive():
            safe_print(C.gray(f"\n  ⏱ {_APPROVAL_TIMEOUT}秒経過 → 自動承認"), flush=True)
            response = ""
        else:
            response = response_holder[0] if response_holder else ""

        approved = response in ("y", "")
        if approved:
            safe_print(C.green("  ✓ 承認しました"))
        else:
            safe_print(C.red("  ✗ 拒否しました（処理を中断します）"))
        return approved

    set_write_approval_handler(_react_approval_handler)
    current_mode = "interactive"

    def _mode_label(mode: str) -> str:
        if mode == "interactive":
            return C.bold_green("Interactive (ReAct)")
        return C.green("Plan-and-Execute")

    def switch_mode(new_mode: str):
        nonlocal current_mode
        if new_mode == current_mode:
            safe_print(C.gray(f"  既に {_mode_label(new_mode)} モードです。"))
            return
        current_mode = new_mode
        agent.set_system_prompt(react_prompt if new_mode == "interactive" else plan_prompt)
        agent.clear_history()
        interactive_orch.react_log.clear()
        safe_print(C.yellow(f"  モード切り替え: {_mode_label(new_mode)}"))
        safe_print(C.gray("  会話履歴をリセットしました。"))

    # ── モード・ユーティリティコマンドをここで登録 ──────────────
    @cmd_registry.register("mode", "モード切り替え (/mode interactive|plan)")
    def cmd_mode(a: "OpenRouterAgent", args: str):
        m = args.strip().lower()
        if m in ("interactive", "react", "i"):
            switch_mode("interactive")
        elif m in ("plan", "p"):
            switch_mode("plan")
        else:
            safe_print(f"  現在: {_mode_label(current_mode)}")
            safe_print(C.gray("  切替: /mode interactive  /mode plan"))

    @cmd_registry.register("undo", "Auto-Git でロールバック (/undo)")
    def cmd_undo(a: "OpenRouterAgent", args: str):
        result = auto_git.rollback(a.cwd)
        safe_print(C.yellow(f"  [AutoGit] {result}"))

    safe_print(C.cyan(f"  作業フォルダ: {agent.cwd}"))
    safe_print(C.gray(
        "  /mode interactive|plan でモード切り替え  "
        "·  /help で一覧  ·  exit で終了"
    ) + "\n")

    while True:
        try:
            # 📋 (U+1F4CB) は表示幅2だが readline は1と計算するためカーソルがズレる
            # → 表示幅1確定のナローUnicode文字に置換
            mode_icon = C.green("⚡") if current_mode == "interactive" else C.orange("≡")
            user_input = input(_rl(f"{mode_icon} {C.bold_green('❯')} ")).strip()
        except (EOFError, KeyboardInterrupt):
            safe_print(C.gray("\n終了します。"))
            break

        if not user_input:
            continue
        if user_input.lower() in ("exit", "quit", "q"):
            if sessions_dir and interactive_orch.react_log.entries:
                try:
                    result = interactive_orch.react_log.save_session(sessions_dir)
                    safe_print(C.gray(f"  [Session] {result}"))
                except Exception as e:
                    safe_print(C.yellow(f"  [Session] 保存失敗: {e}"))
            safe_print(C.gray("終了します。"))
            break

        match = cmd_registry.route(user_input)
        if match:
            _, handler, args = match
            handler(agent, args)
            continue

        if current_mode == "interactive":
            try:
                safe_print(f"\n{C.green_dim('┌─')} {C.bold_green('mimic')}")
                interactive_orch.run_react(user_input)
                safe_print(C.green_dim("└" + "─" * 20) + "\n")
            except KeyboardInterrupt:
                safe_print(C.yellow("\n\n  [割り込み] Ctrl+C"), flush=True)
            except Exception as e:
                safe_print(C.red(f"\n  ✗ {e}"))
                log.error({"event": "react_error", "error": str(e),
                           "traceback": traceback.format_exc()})
        else:  # plan
            _run_plan_ui(orchestrator, user_input)

    set_write_approval_handler(None)

def pipe_mode(agent: OpenRouterAgent, prompt: str):
    """
    パイプモード: bash から
      python3 -m mimic_linux --prompt "質問文"
    のように呼び出す。結果を stdout に出力して終了。
    """
    try:
        response = agent.run(prompt)
        sys.stdout.buffer.write((response + "\n").encode("utf-8"))
        sys.stdout.buffer.flush()
        sys.exit(0)
    except Exception as e:
        msg = f"ERROR: {e}"
        sys.stderr.buffer.write((msg + "\n").encode("utf-8"))
        sys.stderr.buffer.flush()
        log.error({"event": "pipe_error", "error": str(e),
                   "traceback": traceback.format_exc()})
        sys.exit(1)

_MIMIC_DONE_MARKER = "===MIMIC_DONE==="

def auto_mode(
    interactive_orch: "InteractiveOrchestrator",
    prompt: str,
    orchestrator: "Optional[AgentOrchestrator]" = None,
):
    """
    MCP/Claude Code 連携用の自動実行モード。
    承認・介入を一切行わず、自律的にタスクを完結させる。
    prompt が "/plan " で始まる場合は Plan-and-Execute モードで実行する。
    """
    is_plan = prompt.startswith("/plan ")
    actual_prompt = prompt[6:] if is_plan else prompt

    interactive_orch._auto_mode = True

    answer_sent = threading.Event()

    def on_answer(final_text: str):
        if answer_sent.is_set():
            return
        answer_sent.set()
        sys.stdout.write(_MIMIC_DONE_MARKER + "\n")
        sys.stdout.flush()

    error_holder: list = [None]

    try:
        if is_plan and orchestrator is not None:
            result = orchestrator.run_with_plan(actual_prompt)
            on_answer(result)
        else:
            result = interactive_orch.run_react(actual_prompt, on_done=on_answer)
            if not answer_sent.is_set():
                on_answer(result or "(応答なし)")
    except Exception as exc:
        error_holder[0] = exc
        if not answer_sent.is_set():
            on_answer(f"ERROR: {exc}")

    if not answer_sent.is_set():
        on_answer("(応答なし)")

    sys.exit(0 if error_holder[0] is None else 1)

def _run_plan_ui(orchestrator: "AgentOrchestrator", task: str):
    """/plan コマンドのハンドラ"""
    def on_plan(steps):
        safe_print(f"\n{C.green_dim('┌─')} {C.bold_green('実行計画')}")
        for s in steps:
            parallel_tag = C.orange(" [並列]") if s.parallel else ""
            safe_print(f"  {C.gray(f'Step {s.index}:')} {C.white(s.description)}{parallel_tag}")
        safe_print(C.green_dim("└" + "─" * 30))
        safe_print()

    def on_step(step):
        icons = {
            "running":  C.green("▶"),
            "done":     C.bold_green("✓"),
            "failed":   C.red("✗"),
            "retrying": C.yellow("↻"),
        }
        icon  = icons.get(step.status, " ")
        label = "" if step.index == 0 else C.gray(f"Step {step.index}: ")
        parallel_tag = C.orange(" ⚡") if getattr(step, "parallel", False) else ""
        safe_print(f"  {icon} {label}{step.description}{parallel_tag}", flush=True)

    def on_token(t: str):
        safe_print(C.purple(t), end="", flush=True)

    try:
        result = orchestrator.run_with_plan(
            task, on_plan=on_plan, on_step=on_step, on_token=on_token
        )
        safe_print(f"\n{C.green_dim('┌─')} {C.bold_green('完了')}")
        safe_print(render_markdown(result))
        safe_print(C.green_dim("└" + "─" * 20) + "\n")
    except Exception as e:
        safe_print(C.red(f"  ✗ {e}"))
