# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import sys
import threading
import traceback

_FINAL_MARKER = "===MIMIC_FINAL==="

from .utils import log
from .agent import OpenRouterAgent
from .orchestrator import InteractiveOrchestrator


def pipe_mode(agent: OpenRouterAgent, prompt: str):
    """
    パイプモード: bash から
      python3 -m mimic_linux --prompt "質問文"
    のように呼び出す。結果を stdout に出力して終了。
    """
    try:
        response = agent.run(prompt)
        sys.stdout.buffer.write((response + "\n").encode("utf-8"))
        sys.stdout.buffer.flush()
        sys.exit(0)
    except Exception as e:
        msg = f"ERROR: {e}"
        sys.stderr.buffer.write((msg + "\n").encode("utf-8"))
        sys.stderr.buffer.flush()
        log.error({"event": "pipe_error", "error": str(e),
                   "traceback": traceback.format_exc()})
        sys.exit(1)

def auto_mode(
    interactive_orch: "InteractiveOrchestrator",
    prompt: str,
):
    """
    MCP/Claude Code 連携用の自動実行モード。
    承認・介入を一切行わず、自律的にタスクを完結させる。
    """
    interactive_orch._auto_mode = True

    answer_sent = threading.Event()

    def on_answer(final_text: str):
        if answer_sent.is_set():
            return
        answer_sent.set()
        sys.stdout.write(_FINAL_MARKER + "\n")
        sys.stdout.write((final_text or "") + "\n")
        sys.stdout.flush()

    error_holder: list = [None]

    try:
        result = interactive_orch.run_react(prompt, on_done=on_answer)
        if not answer_sent.is_set():
            on_answer(result or "(応答なし)")
    except Exception as exc:
        error_holder[0] = exc
        if not answer_sent.is_set():
            on_answer(f"ERROR: {exc}")

    if not answer_sent.is_set():
        on_answer("(応答なし)")

    sys.exit(0 if error_holder[0] is None else 1)

