# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import re
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from typing import Optional
from .utils import safe_print, C, log, PipelineTypewriter, cache_tool_output
from .agent import OpenRouterAgent, _CACHEABLE_TOOLS, _print_write_diff, _build_tool_call_entry
from .tools import tools, UserRejectedWriteError
from .autogit import AutoGit, ReactLog


BASH_EXECUTOR_GUIDANCE = """\

[bash実行ガイドライン（必須遵守）]
- **bashコマンドは必ず自分で run_bash ツールを使って実行すること。ユーザーに「実行してください」と依頼してはならない。**
- run_bash を呼ぶときは working_directory に現在の作業フォルダのフルパスを必ず指定する。
- コマンド結果の先頭が [SUCCESS] なら成功、[FAILURE...] なら失敗。FAILUREは必ずリトライまたは代替手段を取ること。
- パイプ（|）・リダイレクト（>）・&&・複数行コマンドはそのまま run_bash に渡せる。
- 複数コマンドは && または ; でつなぎ、1回の run_bash にまとめる。
- 変数は同一コマンド内でのみ有効。ステップをまたぐ場合はファイル経由で値を渡す。
- ディレクトリ削除は rm -rf、権限変更は chmod/chown を使う。
- エラー発生時は stderr の内容を確認して原因を特定してから対処する。

[専用ツールへの置き換え（必須）]
以下のコマンドは run_bash を使わず、必ず専用ツールを呼ぶこと:
- stat <file> / wc -l <file>  →  file_info(path=<file>)

[ツール出力の制限（必須遵守）]
- すべてのツール出力は10000文字を超えると自動的にメモリにキャッシュされ、先頭10000文字と cache_key が返される。
- 続きを読む場合は read_tool_cache(cache_key="...", offset=10000) を呼び出す。
- ファイル読み取りは read_file の offset で10000文字ずつ分割して読むこと。
"""

REACT_SYSTEM_PROMPT = """
# 動作ルール

## 言語
すべての出力を日本語で行う（思考・回答・説明すべて）。

## ファイル処理の原則（Pipeline-First）
コンテキストを節約するため、read_file より先に Pipeline 系ツールを試みること。

### 読む前に自問する
| やりたいこと | 使うべきツール |
|---|---|
| キーワードを探したい | search_in_file(pattern, path) |
| コードベース全体を検索 | grep_codebase(pattern, directory) |
| ファイルの大きさを確認 | file_info(path) |
| 関数・クラス一覧を把握 | search_in_file("^def \\|^class ", path) |
| ログを集計・フィルタ | run_pipeline("grep ERROR log | sort | uniq -c") |
| 上記以外で 5,000文字以下 | read_file(path) |

### read_file を使う条件
- ファイルが 5,000文字以下であることが file_info で確認済み
- 行番号が特定済みで offset + limit を指定できる
- バイナリ・設定ファイルで構造全体が必要

### read_file を使ってはいけない条件
- 大きなファイルを「とりあえず読む」目的
- キーワード検索が目的（→ search_in_file を使う）
- 複数ファイル横断検索（→ grep_codebase を使う）

## ツール使用の原則
- プロジェクト構造が不明なときは grep_codebase で検索してから把握する
- ファイルを編集する前に search_in_file で対象箇所を確認する
- 独立した読み取り操作は複数同時に呼び出して並列実行する
- ツールは「言及する」だけでなく、必ず実際に呼び出す
- エラーが出たら原因を特定し、代替手段を試みる

## 完了と停止
- 依頼されたことをすべて完了したら即座に最終回答を出力して停止する
- ツール実行後は必ず結果を日本語テキストで報告すること（無言での終了は禁止）
- 依頼されていない改善・リファクタリングを自発的に行わない
- 範囲外の問題を発見したら「メモ: ～も見つかりました」と一言添えてユーザーに委ねる

## サブエージェントへの委任（delegate_to_team / delegate_to_team_parallel）
**【積極委任モード】複雑・正確性が求められるタスクでは積極的にチームへの委任を試みること。**
- **同期的**（呼び出すと完了まで待機し、戻り値として最終的な差分サマリを受け取る）
- 内部ではWorkerが既存のOverlayFS隔離された専用の作業部屋（仮想合成ビュー）の中で実装を行い、
  Git には一切触れない。プロジェクト本体は変更されず、失敗しても自動的に作業部屋ごと破棄される
- Workerの実装結果を、フレッシュな文脈の監視役（Supervisor）がレビューし、不十分なら
  最大5回までやり直しを内部で繰り返してから最終結果を返す
- 戻り値は「最終的な差分サマリ」であり、サブエージェントの感想文ではない
- **委任して終わりではない**: 差分サマリを読み、採用するか・どう直すかを自分で判断し、
  read_file/write_file/edit_file/patch_file で実際にプロジェクトへ反映し、自分自身でコミットすること
- **【最重要】指示文(task)は呼び出す前に自分(Director)で grep_codebase / search_in_file 等で
  事前に調査し、対象ファイル・変更内容を具体的に書くこと。** 曖昧な指示はWorkerの手戻り回数を
  増やすだけで、レビュー役による誤指示の救済はできない。
- **delegate_to_team_parallel**: 互いに依存しない複数タスクを、それぞれ独立したWorker→Supervisor
  ループとして並列実行する。少しでも独立性があるタスクは積極的に並列委任すること。

## 利用可能なツール
### run_bash の結果の読み方
- `[SUCCESS]` — 正常終了
- `[FAILURE(ExitCode=N)]` — 異常終了（エラー内容を読んで対処する）
- `[TIMEOUT]` — タイムアウト強制終了だが**途中出力が含まれる。必ず読んで分析し作業を継続すること**。
  デプロイ・長時間コマンドはタイムアウトしても成功していることがあるため、途中出力から成否を判断する。

### Pipeline-First（コンテキスト節約・優先使用）
file_info, search_in_file, grep_codebase, run_pipeline, run_bash

### ファイル操作
read_file, read_tool_cache, write_file, edit_file, patch_file

### 探索
get_repo_map, run_bash("ls / find ...")

### 委任（同期・Worker→Supervisorレビュー付き、OverlayFS隔離）
delegate_to_team, delegate_to_team_parallel

### Web
web_search, fetch_webpage
"""

EXTREME_REACT_SYSTEM_PROMPT = """
# 役割と行動指針（Extreme React = Director専任モード）
あなたはこのモードでは「指示係（Director）」専任です。ファイルを直接書き換える
ツール（write_file / edit_file / patch_file）は意図的に取り上げられており、使用できません。
コードへの変更が必要な作業は、すべて delegate_to_team / delegate_to_team_parallel
への委任を通じて行います。

## あなたの仕事の流れ
1. 【調査】Pipeline-First系ツール（grep_codebase, search_in_file, file_info,
   get_repo_map, smart_read, read_file, run_bash 等）でコードベースを調査し、
   対象ファイル・現状の実装・変更が必要な箇所を具体的に特定する。
2. 【指示作成】調査結果をもとに、Workerが迷わず実装できる詳細な指示文(task)を作る。
   - 対象ファイルのフルパス、変更箇所、変更内容、期待される結果を明記する
   - 曖昧な指示は手戻りに直結するため、自分で調べた事実を指示文に織り込む
3. 【委任】delegate_to_team（単一タスク）/ delegate_to_team_parallel（独立した複数タスク）
   を呼び出す。内部でWorkerが実装し、フレッシュな監視役（Supervisor）が差分をレビューして
   不十分なら最大5回までやり直す。
4. 【適用は自動】delegate_to_teamが"完了・適用済み"を返した場合、変更は既にプロジェクトへ
   反映され、AutoGitでコミット済みである。**あなた自身でファイルを書き換えたりコミットし
   直したりする必要はない**。
5. 【検証・追加委任】返ってきた差分サマリを読み、目的を達成しているか確認する。
   不足があれば、判明した事実を踏まえて追加の delegate_to_team を発行する。
6. 【報告】最終的に行われた変更内容と結果を日本語で簡潔にユーザーへ報告する。

## run_bash / run_pipeline について
- 調査・テスト実行・ログ確認など**読み取り専用・診断目的**でのみ使用する。
- ファイルを変更するコマンド（リダイレクト `>` `>>`、`sed -i`、`mv`、`rm`、
  `git commit` 等）は実行しないこと。変更が必要な場合は必ず delegate_to_team を使う。

## update_scratchpad（複数回の委任にまたがる記憶）
複雑なタスクで delegate_to_team を複数回呼ぶ場合、各委任の前後で update_scratchpad
を呼び、以下を整理しておくこと：
【ゴール】全体の目標
【調査で判明した事実】対象ファイル・現状の実装
【委任結果】これまでのdelegate_to_team呼び出しと適用結果
【次の一手】次に委任する内容、または最終報告の準備
"""

class InteractiveOrchestrator:
    """
    ReAct（Reason + Act）ベースの対話型オーケストレーター。

    フロー:
      1. Auto-Git バックアップ
      2. AI が Thought をストリーミング出力（中間ターンのみ端末表示）
      3. Tool call (Action) を実行 → 結果 (Observation) を AI に戻す
      4. 書き込み系ツール成功後に Auto-Git チェックポイント
      5. ツールなし応答 = 最終回答を返す（Markdown レンダリングして表示）
    """

    MAX_REACT_STEPS  = 120 # ReActループ上限
    MAX_EMPTY_RETRIES = 2  # 空レスポンス検知による再試行の上限

    def __init__(self, agent: "OpenRouterAgent", auto_git: "AutoGit"):
        self.agent    = agent
        self.auto_git = auto_git
        self.react_log = ReactLog()

    @staticmethod
    def _fmt_args(args: dict) -> str:
        return ", ".join(f"{k}={repr(v)[:40]}" for k, v in args.items())

    @staticmethod
    def _extract_thought(text: str) -> str:
        """<think>/<thought> タグ内の思考テキストを抽出する。タグがなければ空文字を返す。"""
        if not text:
            return ""
        m = re.search(r'<(?:think|thought)>(.*?)</(?:think|thought)>', text, re.DOTALL | re.IGNORECASE)
        if m:
            return m.group(1).strip()
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("Thought:"):
                return stripped[len("Thought:"):].strip()
        return ""

    @staticmethod
    def _strip_thinking(text: str) -> str:
        """ログ保存前に <think>/<thought> タグとその内容を除去する。"""
        return re.sub(r'<(?:think|thought)>.*?</(?:think|thought)>', '', text, flags=re.DOTALL | re.IGNORECASE).strip()

    def _execute_with_intervention(
        self, fn_name: str, fn_args: dict, error_counts: dict
    ) -> str:
        """
        ツールを実行する。エラー発生時はAIに内容を返して自律的に解決させる（介入なし）。
        読み取り系ツールはキャッシュを利用する。
        """
        # ── キャッシュヒット確認（読み取り系のみ）────────────────
        if fn_name in _CACHEABLE_TOOLS:
            cache_key = self.agent._make_cache_key(fn_name, fn_args)
            if cache_key in self.agent._tool_cache:
                cached = self.agent._tool_cache[cache_key]
                safe_print(C.gray(f"    [キャッシュ] {len(cached)}文字 (再取得スキップ)"), flush=True)
                return cached

        # ── 自動実行（diff表示のみ） ──────────────────────────
        if fn_name in ("write_file", "edit_file", "patch_file"):
            _print_write_diff(fn_name, fn_args)

        try:
            result = self.agent.tools.execute(fn_name, fn_args)
            error_counts[fn_name] = 0
            result_str = cache_tool_output(fn_name, str(result))
            # キャッシュ登録 / 書き込み後の無効化
            if fn_name in _CACHEABLE_TOOLS:
                self.agent._tool_cache[cache_key] = result_str  # type: ignore[possibly-undefined]
            elif fn_name in ("write_file", "edit_file", "patch_file"):
                self.agent._invalidate_cache_for_path(fn_args.get("path", ""))
            return result_str
        except UserRejectedWriteError:
            raise  # run_react でキャッチしてループを即停止する
        except Exception as e:
            error_counts[fn_name] = error_counts.get(fn_name, 0) + 1
            err_msg = str(e)
            log.error({"event": "react_tool_error", "tool": fn_name,
                        "error": err_msg, "count": error_counts[fn_name]})
            safe_print(C.red(f"\n  ✗ [{fn_name}] エラー: {err_msg}"), flush=True)
            # エラーテキストをAIに返してAIに対処させる（自律的なリカバリ）
            return f"ツール実行エラー: {fn_name}: {err_msg}"

    def run_react(self, user_message: str, on_done=None) -> str:
        """
        ReActループのメインエントリポイント。

        Thought → Action → Observation を繰り返して最終回答を返す。
        on_done: 最終回答が確定した瞬間に呼ばれるコールバック(text) → str
                 教訓保存より前に呼ばれるので、MCP自動モードで即返しに使える。
        """
        try:
            return self._run_react_inner(user_message, on_done)
        except KeyboardInterrupt:
            safe_print(C.yellow("\n\n  [割り込み] Ctrl+C — ツール実行を中断しました。"), flush=True)
            return "処理を中断しました。"

    def _run_react_inner(self, user_message: str, on_done=None) -> str:
        from .tools import clear_read_files_registry
        clear_read_files_registry()

        # ── 1. Auto-Git バックアップ ──────────────────────────────
        backup_result = self.auto_git.backup(self.agent.cwd)
        safe_print(C.gray(f"  [AutoGit] {backup_result}"), flush=True)

        # ── 2. メッセージ構築 ─────────────────────────────────────
        self.react_log.add("user_input", content=user_message)
        self.agent._compact_if_needed()

        ctx    = self.agent._build_context_header()
        task   = self.agent._task_context()
        prefix = "\n\n".join(p for p in [ctx, task] if p)
        aug_message = f"{prefix}\n\n{user_message}" if prefix else user_message

        messages: list[dict] = list(self.agent.conversation)
        old_conv_len = len(self.agent.conversation)  # ツール実行履歴保存用
        messages.append({"role": "user", "content": aug_message})

        step_count        = 0
        empty_retry_count = 0
        had_tool_call     = False
        error_counts: dict[str, int] = {}
        write_tools  = {"write_file", "edit_file", "patch_file", "delete_file"}

        # ── 3. ReActループ ───────────────────────────────────────
        while step_count < self.MAX_REACT_STEPS:
            # PipelineTypewriter でバッファ→レンダリング→タイプライター表示
            _tw = PipelineTypewriter(auto_mode=getattr(self, "_auto_mode", False))
            _tw.start()
            text, tool_calls = self.agent._stream_react_call(
                messages, text_callback=_tw.feed
            )
            _tw.finalize()

            # Ctrl+C 中断
            if text == "__interrupted__":
                return "処理を中断しました。"

            # ── Thought ログ記録 ──────────────────────────────────
            if text:
                thought = self._extract_thought(text)
                if thought:
                    self.react_log.add("thought", content=thought, step=step_count)

            # ── ツールなし = 最終回答候補 ──────────────────────────
            if not tool_calls:
                # 空レスポンス検知: ツール実行後に空テキストが返された場合に報告を促す
                if (not text and had_tool_call
                        and empty_retry_count < self.MAX_EMPTY_RETRIES):
                    empty_retry_count += 1
                    safe_print(C.yellow(
                        f"  ⚠ 空レスポンス検知 → 報告を促します ({empty_retry_count}/{self.MAX_EMPTY_RETRIES})"
                    ), flush=True)
                    messages.append({"role": "assistant", "content": "（思考中...）", "_skip_save": True})
                    messages.append({"role": "user",
                        "content": "ツール実行結果を踏まえて、作業内容と結果を日本語で報告してください。",
                        "_skip_save": True,
                    })
                    step_count += 1
                    continue

                final_text = text or "(応答なし)"
                self.react_log.add("final_answer", content=self._strip_thinking(final_text))

                # ツール実行履歴を含む全ターンを conversation に保存（内部マーカーを除外）
                self.agent.conversation.append({"role": "user", "content": user_message})
                _save_msgs = [m for m in messages[old_conv_len + 1:] if not m.get("_skip_save")]
                self.agent.conversation.extend(_save_msgs)
                self.agent.conversation.append({"role": "assistant", "content": final_text})

                if on_done:
                    try:
                        on_done(final_text)
                    except Exception:
                        pass

                return final_text

            # ── アシスタント応答を OpenAI ネイティブ形式で追加 ──
            messages.append({
                "role": "assistant",
                "content": text or None,
                "tool_calls": [_build_tool_call_entry(tc) for tc in tool_calls],
            })

            # ── ツール実行（Action → Observation）───────────────
            tool_results: list[dict] = []

            # 書き込み系ツールが含まれる場合は逐次実行（チェックポイント・介入が必要）
            # 読み取り系のみなら並列実行
            has_write_tool = any(tc.get("name", "") in write_tools for tc in tool_calls)

            if len(tool_calls) > 1 and not has_write_tool:
                # ── 並列実行（読み取り系のみ）──────────────────────
                safe_print(C.orange(f"\n  ⚡ {len(tool_calls)} ツールを並列実行"), flush=True)
                ordered: list[Optional[dict]] = [None] * len(tool_calls)

                def _par_exec(idx_tc: tuple) -> tuple:
                    idx, tc = idx_tc
                    fn_n = tc.get("name", "")
                    fn_a = tc.get("args", {})
                    call_id = tc.get("id") or f"call_{fn_n}_{idx}"
                    safe_print(
                        f"  {C.bold_green('⚙')} {C.green(fn_n)}"
                        + C.cyan(f"({self._fmt_args(fn_a)})"),
                        flush=True,
                    )
                    self.react_log.add("action", tool=fn_n, args=fn_a, step=step_count)
                    ck = None  # キャッシュキー（非対象ツールでは未使用）
                    # キャッシュヒット確認
                    if fn_n in _CACHEABLE_TOOLS:
                        ck = self.agent._make_cache_key(fn_n, fn_a)
                        if ck in self.agent._tool_cache:
                            r_str = self.agent._tool_cache[ck]
                            safe_print(C.gray(f"    [キャッシュ] {len(r_str)}文字"), flush=True)
                            self.react_log.add("observation", tool=fn_n, result=r_str[:500], step=step_count)
                            return idx, fn_n, r_str, call_id
                    try:
                        r = self.agent.tools.execute(fn_n, fn_a)
                        r_str = cache_tool_output(fn_n, str(r))
                        if fn_n in _CACHEABLE_TOOLS:
                            self.agent._tool_cache[ck] = r_str  # type: ignore[possibly-undefined]
                    except Exception as e:
                        r_str = f"ツール実行エラー: {fn_n}: {e}"
                        log.error({"event": "react_tool_error_par", "tool": fn_n, "error": str(e)})
                        safe_print(C.red(f"  ✗ [{fn_n}] 並列実行エラー: {e}"), flush=True)
                        safe_print(C.gray("    （並列実行中のため自動リトライ・介入なし — AIがリカバリします）"), flush=True)
                    obs_preview = r_str[:300].replace("\n", " ")
                    safe_print(C.cyan(f"  👁 {obs_preview}"), flush=True)
                    self.react_log.add("observation", tool=fn_n, result=r_str[:500], step=step_count)
                    return idx, fn_n, r_str, call_id

                with ThreadPoolExecutor(max_workers=len(tool_calls)) as tpool:
                    for idx, fn_n, r_str, call_id in tpool.map(_par_exec, enumerate(tool_calls)):
                        ordered[idx] = {"tool": fn_n, "result": r_str, "call_id": call_id}
                tool_results = ordered  # type: ignore
            else:
                # ── 逐次実行（書き込み系を含む場合・単一ツール）──────
                for tc in tool_calls:
                    fn_name = tc.get("name", "")
                    fn_args = tc.get("args", {})
                    call_id = tc.get("id") or f"call_{fn_name}"
                    args_preview = self._fmt_args(fn_args)

                    safe_print(
                        f"\n  {C.bold_green('⚙')} {C.green(fn_name)}"
                        + C.cyan(f"({args_preview})"),
                        flush=True,
                    )
                    self.react_log.add("action", tool=fn_name, args=fn_args, step=step_count)

                    try:
                        result_str = self._execute_with_intervention(fn_name, fn_args, error_counts)
                    except UserRejectedWriteError as e:
                        safe_print(C.yellow(f"\n  ✋ 書き込みを拒否しました（{e}）。処理を中断します。"), flush=True)
                        safe_print(C.gray("  新しい指示を入力してください。"), flush=True)
                        return "書き込みが拒否されたため処理を中断しました。"

                    # Auto-checkpoint: 書き込み系ツール成功後に自動コミット
                    # エラー・スキップ・キャンセル時はチェックポイントを行わない
                    _non_success = (
                        "ツール実行エラー: ",
                        "[ユーザーがスキップを選択]",
                        "[ユーザーがキャンセル]",
                        "ユーザーによるキャンセル: ",
                        "[ユーザー指示]",
                    )
                    if fn_name in write_tools and not any(
                        result_str.startswith(p) for p in _non_success
                    ):
                        self.auto_git.checkpoint(
                            self.agent.cwd, fn_name, fn_args.get("path", "")
                        )

                    obs_preview = result_str[:300].replace("\n", " ")
                    safe_print(C.cyan(f"  👁 {obs_preview}"), flush=True)
                    self.react_log.add(
                        "observation", tool=fn_name,
                        result=result_str[:500], step=step_count
                    )
                    tool_results.append({
                        "tool":    fn_name,
                        "result":  result_str,
                        "call_id": call_id,
                    })

            # ── Observation を OpenAI ネイティブ形式（role: tool）で追加 ──
            for r in tool_results:
                messages.append({
                    "role": "tool",
                    "tool_call_id": r["call_id"],
                    "content": r["result"],
                })
            had_tool_call = True
            step_count += 1

        # ループ上限到達
        fallback = f"(ReActループ上限 {self.MAX_REACT_STEPS} ステップに達しました)"
        self.agent.conversation.append({"role": "user", "content": user_message})
        _save_msgs = [m for m in messages[old_conv_len + 1:] if not m.get("_skip_save")]
        self.agent.conversation.extend(_save_msgs)
        self.agent.conversation.append({"role": "assistant", "content": fallback})
        return fallback



# (DualModelOrchestrator は削除済み — Plan モードに統合)
