# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json as _json
import os as _os
import re
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from pathlib import Path as _Path
from typing import Optional

_CHECKPOINT_FILE = ".mimic_checkpoint.json"
_CHECKPOINT_RESUME_NOTE = (
    "[システム通知] 前回の実行が予期せず終了しました。"
    "overlay上の変更は保持されています。続きから再開してください。"
)

# モデルがXML形式でツール呼び出しをテキストに埋め込んだ場合に検知するパターン
_XML_TOOL_PATTERN = re.compile(
    r'<tool_call\b|<function=|<invoke\b|<function_calls\b|\[TOOL_CALL\]',
    re.IGNORECASE,
)
_MAX_XML_TOOL_RETRIES = 3


# ── 最終回答ゲート（弱いモデルの失敗モードを機械検査で差し戻す） ────
# 「ツールなし応答＝最終回答」の無条件受理をやめ、観測済みの失敗パターンを
# 受理前に文字列検査する。各ゲートは1回だけ差し戻す（無限ループ防止）。

# ゲートA: 実行ツールを持っているのにユーザーへコマンド実行を丸投げする回答
_OFFLOAD_RE = re.compile(
    r"実行してください|実行して下さい|実行をお願い|お手元で実行|ご自身で実行"
    r"|手動で(?:実行|編集|修正)|以下のコマンドを実行|コマンドを叩いて"
)
# 丸投げ検知の適用除外: 本当にユーザーの環境・操作が必要なケース
_OFFLOAD_EXEMPT_RE = re.compile(
    r"ログイン|認証|サインイン|パスワード|ブラウザで開いて|この環境では実行できな"
)
_EXEC_CAPABLE_TOOLS = {
    "run_bash", "run_pipeline", "run_host_command",
    "delegate_to_specialist", "delegate_to_team", "delegate_to_worker",
    "delegate_to_team_parallel",
}


def _detect_command_offload(text: str, available_tools) -> bool:
    """実行手段を持つのにユーザーへ実行を丸投げしている最終回答を検知する。"""
    if not text or not (_EXEC_CAPABLE_TOOLS & set(available_tools)):
        return False
    if not _OFFLOAD_RE.search(text):
        return False
    if _OFFLOAD_EXEMPT_RE.search(text):
        return False
    return True


# ゲートB: ターン内に「※未検証」の委任結果があるのに検証済みかのように断言する回答
_COMPLETION_CLAIM_RE = re.compile(
    r"完了しました|解決しました|完了です|修正しました|対応しました|実装しました|適用しました"
)


def _detect_unverified_claim(text: str, turn_had_unverified: bool) -> bool:
    """未検証の変更を「完了/解決」と断言している最終回答を検知する。"""
    if not turn_had_unverified or not text:
        return False
    if "未検証" in text or "動作未確認" in text or "確認できていません" in text:
        return False
    return bool(_COMPLETION_CLAIM_RE.search(text))


# ── 同一ツール呼び出しの反復失敗ループブレーカー ────────────────────
# 弱いモデルは「同じ呼び出しを同じ引数で失敗し続ける」傾向が最も強い。
# 同一キーの失敗が上限に達したら実行自体を拒否し（安価なno-op化）、
# 拒否が続く場合はターンを強制終了する。

_MAX_IDENTICAL_TOOL_FAILURES = 3   # 同一呼び出しの失敗上限（以降は実行拒否）
_MAX_LOOP_REFUSALS = 5             # 実行拒否の累計上限（超えたらターン終了）


class ToolLoopBreakError(Exception):
    """同一ツール呼び出しの失敗反復が上限を超えたことを示す。"""


def _tool_call_key(fn_name: str, fn_args: dict) -> str:
    """ツール呼び出しの同一性判定キー（名前+正規化引数）。"""
    try:
        args_repr = _json.dumps(fn_args, sort_keys=True, ensure_ascii=False)
    except Exception:
        args_repr = str(fn_args)
    return f"{fn_name}:{args_repr[:512]}"


def _parse_xml_tool_calls(text: str) -> list[dict]:
    """テキスト内のXML形式ツール呼び出しをパースして tool_calls リストに変換する。

    対応フォーマット:
      A. <tool_call>{"name":"fn","arguments":{...}}</tool_call>   (Qwen/Hermes JSON標準)
      B. <tool_call>                                               (nex-n2-pro等の実測形式)
           <function=fn>
             <parameter=key1>value1</parameter>
             <parameter=key2>value2</parameter>
           </function>
         </tool_call>
      C. 上記BのB外側 <tool_call> なしの単独 <function=...> 形式
    """
    results: list[dict] = []

    def _coerce(val: str) -> object:
        """数値文字列は int/float に変換する。"""
        s = val.strip()
        try:
            return int(s)
        except ValueError:
            pass
        try:
            return float(s)
        except ValueError:
            pass
        return s

    def _extract_params(fn_body: str) -> dict:
        """<parameter=NAME>VALUE</parameter> を全て抽出して dict に変換する。"""
        params: dict = {}
        for pm in re.finditer(
            r'<parameter=([^>]+)>([\s\S]*?)</parameter>', fn_body, re.IGNORECASE
        ):
            params[pm.group(1).strip()] = _coerce(pm.group(2))
        if params:
            return params
        # フォールバック: <parameters>{JSON}</parameters>
        jm = re.search(r'<parameters?>([\s\S]*?)</parameters?>', fn_body, re.IGNORECASE)
        if jm:
            try:
                obj = _json.loads(jm.group(1).strip())
                if isinstance(obj, dict):
                    return obj
            except _json.JSONDecodeError:
                pass
        # フォールバック: 本文全体がJSON
        try:
            obj = _json.loads(fn_body.strip())
            if isinstance(obj, dict):
                return obj
        except _json.JSONDecodeError:
            pass
        return {}

    def _add(name: str, args: dict) -> None:
        results.append({
            "id":   f"xml_call_{len(results)}",
            "name": name.strip(),
            "args": args,
        })

    # ── フォーマットA/B: <tool_call>...</tool_call> ────────────
    for m in re.finditer(r'<tool_call\b[^>]*>([\s\S]*?)</tool_call>', text, re.IGNORECASE):
        body = m.group(1).strip()

        # A: 中身がそのままJSON
        try:
            obj = _json.loads(body)
            if isinstance(obj, dict) and "name" in obj:
                raw_args = obj.get("arguments") or obj.get("parameters") or obj.get("args") or {}
                _add(obj["name"], raw_args if isinstance(raw_args, dict) else {})
                continue
        except _json.JSONDecodeError:
            pass

        # B: <function=NAME>...</function>
        fn_m = re.search(
            r'<function=([^>]+)>([\s\S]*?)(?:</function>|$)', body, re.IGNORECASE
        )
        if fn_m:
            _add(fn_m.group(1), _extract_params(fn_m.group(2)))

    # ── フォーマットC: <function=...> 単独 (tool_call なし) ────
    if not results:
        for m in re.finditer(
            r'<function=([^>]+)>([\s\S]*?)(?:</function>|$)', text, re.IGNORECASE
        ):
            _add(m.group(1), _extract_params(m.group(2)))

    return results
from .utils import safe_print, C, log, PipelineTypewriter, cache_tool_output, cache_obs
from .agent import OpenRouterAgent, _CACHEABLE_TOOLS, _print_write_diff, _build_tool_call_entry
from .tools import tools, UserRejectedWriteError
from .autogit import AutoGit, ReactLog

_OBS_MAX_CHARS = 2000  # conversation内のobservationをこの文字数に切り詰める（大出力はtool cacheに別保存済み）

# 委任結果はDirectorの唯一の情報源（Directorは自分でファイルを読めないモードがある）ため、
# 通常ツールより大きい切り詰め上限を使う。2000字では診断レポートの核心が失われる事故があった。
_DELEGATION_OBS_MAX_CHARS = 6000
_DELEGATION_TOOLS = {
    "delegate_to_specialist", "delegate_to_team", "delegate_to_worker",
    "delegate_to_team_parallel", "delegate_research", "continue_specialist",
}

# 覗き見ツール: 書き込みツールを持たないDirector（Specialistモード）に許可された
# 読み取りツールの観測上限。存在確認・場所特定には足りるが深読みはできないサイズにし、
# 「深い調査は委任へ」の誘導をプロンプト規約ではなく出力構造で行う。
_PEEK_OBS_MAX_CHARS = 600
_PEEK_TOOLS = {"read_file", "grep_codebase", "file_info"}

BASH_EXECUTOR_GUIDANCE = """\

[bash実行ガイドライン（必須遵守）]
- **bashコマンドは必ず自分で run_bash ツールを使って実行すること。ユーザーに「実行してください」と依頼してはならない。**
- run_bash を呼ぶときは working_directory に現在の作業フォルダのフルパスを必ず指定する。
- コマンド結果の先頭が [SUCCESS] なら成功、[FAILURE...] なら失敗。FAILUREは必ずリトライまたは代替手段を取ること。
- パイプ（|）・リダイレクト（>）・&&・複数行コマンドはそのまま run_bash に渡せる。
- 複数コマンドは && または ; でつなぎ、1回の run_bash にまとめる。
- 変数は同一コマンド内でのみ有効。ステップをまたぐ場合はファイル経由で値を渡す。
- ディレクトリ削除は rm -rf、権限変更は chmod/chown を使う。
- エラー発生時は stderr の内容を確認して原因を特定してから対処する。

[専用ツールへの置き換え（必須）]
以下のコマンドは run_bash を使わず、必ず専用ツールを呼ぶこと:
- stat <file> / wc -l <file>  →  file_info(path=<file>)

[ツール出力の制限（必須遵守）]
- すべてのツール出力は10000文字を超えると自動的にメモリにキャッシュされ、先頭10000文字と cache_key が返される。
- 続きを読む場合は read_tool_cache(cache_key="...", offset=10000) を呼び出す。
- ファイル読み取りは read_file の offset で10000文字ずつ分割して読むこと。
"""

# ReActプロンプトは部品から組み立てる:
#   REACT_SYSTEM_PROMPT        … Director/interactive用（委任ガイダンス込み）
#   WORKER_REACT_SYSTEM_PROMPT … Workerサブプロセス用（委任ツールへの言及を一切含まない。
#                                Workerには委任ツールが存在しないため、存在を知らせると
#                                弱いモデルが幻覚呼び出し・様子見停止を起こす）
_REACT_PROMPT_CORE = """
# 動作ルール

## 言語
すべての出力を日本語で行う（思考・回答・説明すべて）。

## ファイル処理の原則（Pipeline-First）
コンテキストを節約するため、read_file より先に Pipeline 系ツールを試みること。

### 読む前に自問する
| やりたいこと | 使うべきツール |
|---|---|
| キーワードを探したい | grep_codebase(pattern, path=path) |
| コードベース全体を検索 | grep_codebase(pattern, directory=dir) |
| ファイルの大きさを確認 | file_info(path) |
| 関数・クラス一覧を把握 | grep_codebase("^def \\|^class ", path=path) |
| ログを集計・フィルタ | run_pipeline("grep ERROR log | sort | uniq -c") |
| 上記以外で 5,000文字以下 | read_file(path) |

### read_file を使う条件
- ファイルが 5,000文字以下であることが file_info で確認済み
- 行番号が特定済みで offset + limit を指定できる
- バイナリ・設定ファイルで構造全体が必要

### read_file を使ってはいけない条件
- 大きなファイルを「とりあえず読む」目的
- キーワード検索が目的（→ grep_codebase(pattern, path=path) を使う）
- 複数ファイル横断検索（→ grep_codebase(pattern, directory=dir) を使う）

## ツール使用の原則
- プロジェクト構造が不明なときは grep_codebase で検索してから把握する
- ファイルを編集する前に grep_codebase(pattern, path=path) で対象箇所を確認する
- 独立した読み取り操作は複数同時に呼び出して並列実行する
- ツールは「言及する」だけでなく、必ず実際に呼び出す
- エラーが出たら原因を特定し、代替手段を試みる
- **ツール呼び出しは必ずAPIのtool_calls機能（JSON形式）で行うこと。**
  テキスト内に `<tool_call>`, `<function=...>`, `<invoke>` などのXML形式で
  ツール名を書いても実行されない（最終回答として打ち切られる）。

## 完了と停止
- 依頼されたことをすべて完了したら即座に最終回答を出力して停止する
- ツール実行後は必ず結果を日本語テキストで報告すること（無言での終了は禁止）
- 依頼されていない改善・リファクタリングを自発的に行わない
- 範囲外の問題を発見したら「メモ: ～も見つかりました」と一言添えてユーザーに委ねる

"""

_REACT_DELEGATION_GUIDANCE = """
## サブエージェントへの委任（delegate_to_team / delegate_to_team_parallel）
**【積極委任モード】複雑・正確性が求められるタスクでは積極的にチームへの委任を試みること。**
- **同期的**（呼び出すと完了まで待機し、戻り値として最終的な差分サマリを受け取る）
- 内部では指示文(task)をもとに、まずフレッシュな文脈の調査役（Researcher）が対象コード・
  外部ドキュメント等を調査し、Worker向けの詳細な設計ワークフローを作成する。
  続いてWorkerがそのワークフローに沿って、OverlayFS隔離された専用の作業部屋（仮想合成ビュー）
  の中で実装を行う（Gitには一切触れない。プロジェクト本体は変更されず、失敗しても自動的に
  作業部屋ごと破棄される）
- Researcher（調査・設計ワークフロー作成）→ Worker（実装）の順に実行し、
  変更を即時適用・AutoGitコミットして差分サマリをDirectorに返す。
- 戻り値は「差分サマリ」。**委任して終わりではない**: 差分サマリを読み、目的を達成しているか
  自分で判断すること。不十分なら指示文を見直して再度委任すること。
- **指示文(task)の書き方**: Researcherが詳細調査・設計を行うため、ファイル単位の網羅的な
  事前調査は不要。ただし「目的・対象範囲・制約条件（既存仕様との整合性、互換性など）」は
  自分(Director)が把握している情報を漏れなく書くこと。曖昧な目的設定はResearcherの調査の
  方向性を誤らせる。
- **delegate_to_team_parallel**: 互いに依存しない複数タスクを、それぞれ独立した
  Researcher→Workerパイプラインとして並列実行する。少しでも独立性があるタスクは
  積極的に並列委任すること。

## 単発委任（delegate_to_worker）
- 対象ファイル・変更内容が既に明確で、調査が不要な単純なタスク
  （例: 指定箇所の小さな修正、決まったコマンドの実行と結果確認）には、
  Researcherを介さない delegate_to_worker を使うこと。delegate_to_team
  より高速・低コスト。変更は即時適用・コミットされ、差分サマリが返る。
- 結果を見てさらに修正が必要なら再度 delegate_to_worker を呼ぶか、
  複雑・大規模な場合は delegate_to_team を使うこと。

## 調べ物の委任（delegate_research）
- 外部の公式ドキュメント・API仕様・ライブラリの使い方など、複数回の
  web_search/fetch_webpageが必要になりそうな「調べ物」は、自分で直接 web_search /
  fetch_webpage を繰り返すのではなく delegate_research(question) に委任すること。
- フレッシュな文脈の調査役が調査し、結果（回答）だけを返す。ページ内容や試行錯誤が
  自分の会話履歴に積み上がらないため、その後のやり取りでのコンテキスト圧迫・劣化を防げる。
- 戻り値はユーザーへの回答としてそのまま（必要なら整形して）提示してよい。
- 単発で1回 fetch_webpage すれば済む程度の軽い確認は、自分で web_search / fetch_webpage を
  使ってよい。
"""

_REACT_TOOLS_COMMON = """
## 利用可能なツール
### run_bash の結果の読み方
- `[SUCCESS]` — 正常終了
- `[FAILURE(ExitCode=N)]` — 異常終了（エラー内容を読んで対処する）
- `[TIMEOUT]` — タイムアウト強制終了だが**途中出力が含まれる。必ず読んで分析し作業を継続すること**。
  デプロイ・長時間コマンドはタイムアウトしても成功していることがあるため、途中出力から成否を判断する。

### Pipeline-First（コンテキスト節約・優先使用）
file_info, grep_codebase, run_pipeline, run_bash

### ファイル操作
read_file, read_tool_cache, write_file, edit_file, patch_file

### 探索
get_repo_map, run_bash("ls / find ...")
"""

_REACT_TOOLS_DIRECTOR = """
### 委任（同期・Worker→Supervisorレビュー付き、OverlayFS隔離）
delegate_to_team, delegate_to_team_parallel

### 単発委任（同期・レビュー無し、自己完結タスク向け）
delegate_to_worker

### 調べ物
delegate_research（本格的な調べ物はこちら）, web_search, fetch_webpage（軽い確認用）
"""

_REACT_TOOLS_WORKER = """
### 調べ物
web_search, fetch_webpage
"""

REACT_SYSTEM_PROMPT = (_REACT_PROMPT_CORE + _REACT_DELEGATION_GUIDANCE
                        + _REACT_TOOLS_COMMON + _REACT_TOOLS_DIRECTOR)

# Worker用: 委任ツール群への言及なし（Workerのレジストリにはそもそも存在しない）
WORKER_REACT_SYSTEM_PROMPT = _REACT_PROMPT_CORE + _REACT_TOOLS_COMMON + _REACT_TOOLS_WORKER

# delegate_to_team/delegate_to_worker の Worker（サブエージェント、MIMIC_NO_AUTOGIT=1で起動）に
# のみ追加で付与するガイダンス。Directorには付与しない（毎ターンの追加往復を避けるため）。
WORKER_COMPLETION_GUIDANCE = """

## Workerとして実行中
- タスクを完了したら、作業内容を最終回答として報告して終了すること。
- 完了できない場合も、何をどこまで行ったか・何が問題だったかを日本語で報告して停止すること。
"""

SPECIALIST_REACT_SYSTEM_PROMPT = """
# 役割と行動指針（Specialist = 動的ロール委任モード・標準）
あなたは指揮役（Director）です。実装・修正・実行・深い調査は専門家Workerへの
委任で行い、自分は「軽量な確認・委任の設計・結果の検証・ユーザーへの報告」に徹します。

## あなたが使えるツール（これがすべて。ここにないツールは存在しない）
- delegate_to_specialist(role, task, can_write, can_execute): 専門家への委任（標準の作業手段）
- continue_specialist(task): 直前の can_write Worker への追加指示（会話・作業状態を引き継ぐ）
- read_file / grep_codebase / file_info: 覗き見ツール（読み取り専用・観測は先頭600字まで）
- run_host_command(command, reason): ホスト直接実行（ユーザー承認必須・限定用途）
- update_scratchpad: 作業メモの更新
- read_tool_cache: 長いツール出力の続きを読む（10000字超の出力は自動キャッシュされ cache_key が返る）
- search_history / get_delegation_trace: 過去セッションの検索・委任実行トレースの確認

## 覗き見ツール（read_file / grep_codebase / file_info）
存在確認・場所特定のための軽量な読み取りは自分で行える。ただし観測は先頭600字で
打ち切られるため、深読みはできない。600字で足りない調査は読み取り専用の
delegate_to_specialist に委任すること。
- 使う: ファイルの存在確認、関数の場所特定、委任結果の軽い実地検証
- 使わない: コードの理解・診断・レビュー（→委任）

## continue_specialist（継続委任 — 重要）
直前の can_write 委任のWorkerは、会話と作業状態を保持したまま待機している。
**前回の変更に対するフィードバック（エラーが出た・動かない・追加要望）を反映する
場合は、新しい delegate_to_specialist ではなく continue_specialist(task) を使うこと。**
Workerは経緯を覚えているため、taskには新しく判明した情報だけを書けばよい。
新しい種類の作業・別の専門性が必要なときだけ新規の delegate_to_specialist を使う。

## run_host_command（ホスト直接実行 — ユーザー承認必須）
Workerの隔離環境では原理的に不可能な操作**のみ**、run_host_command(command, reason) で
実行できる。実行前に必ずユーザーの承認確認が入る（拒否されたら実行されない）。
- 使う: システムパッケージのインストール（apt等）、ログイン状態が必要な操作
  （vercel --prod / gh / git push 等のデプロイ・公開）、ユーザー環境の設定変更
- 使わない: ファイル編集・テスト・ビルド・調査（→ 委任。承認不要で速い）
- ユーザーに「このコマンドを実行してください」と依頼するのは禁止。代わりに
  run_host_command で承認を求めること。reason には委任で代替できない理由を書く。

## delegate_to_specialist の使い方
- `role`: 専門家ロールを日本語で記述する。**「視点」「制約」「完了基準」の3要素を必ず含めること**
  （「完了基準」の文字列がないと機械チェックで差し戻され、Workerは起動しない）。
  例: "視点: pytestテストコードライター。制約: 既存テストのスタイルと命名規則に合わせ、
      実装コードは変更しない。完了基準: 追加テストがすべてパスすること"
- 権限は3段階。**用途に合う最小権限を選ぶこと**:
  - デフォルト（両方False）: 調査・レビュー・回答など読み取り専用タスク。
    ブラウザ観測ツールも使えるため「デプロイ先のページを開いて実際の表示・エラーを確認する」
    委任もこの権限でできる
  - `can_execute=True`: テスト実行・ビルド・診断などコマンド実行が必要だが
    変更を残す必要がないタスク（OverlayFS隔離・ファイル変更はタスク終了後に破棄）
  - `can_write=True`: ファイル変更が必要な実装・修正タスク（OverlayFS隔離・自動適用）。
    `expected_files`（変更を想定するファイルのリスト）も指定すると、想定外の変更を
    ハーネスが検出して警告する
- 独立したタスクは複数回並べて呼んでよい（Workerの同時実行は内部で3並列に制限される）
- システムプロンプト末尾に「保存済みロール」がある場合、類似タスクではそれを
  そのまま、または微修正して再利用すること（機械検証を通過したロールのみ保存されている）

## ハーネスによる自動制御（あなたの申告に依存しない仕組み）
- 直近の委任履歴（誰が何を変更したか）は、次の委任タスクへ**自動で注入される**。
  ただしユーザーへの報告に必要な経緯は update_scratchpad で自分でも保持すること。
- can_write委任で verify_cmd を指定しない場合、ハーネスが検証コマンドを自動調達する。
  調達できなければ結果に「※未検証」と付くので、**未検証の変更を「完了しました」と
  ユーザーに断言しないこと**（「適用済みだが動作未確認」と報告する）。
- 変更ファイル0件のcan_write委任には警告が付く。Workerの「完了しました」という
  自己申告と矛盾するため、読み取り専用委任で実ファイルを確認してから報告すること。
- **同じファイル群への書き込み委任が3連続で失敗すると、次の書き込み委任は
  自動的に拒否される**。その場合は指示に従い、読み取り専用の全体診断を先に委任すること。

## あなたの仕事の流れ
1. 【要求の整理】ユーザーの要求を読み解き、目的・対象範囲・制約条件を整理する。
   複雑な要求は依存関係に沿って複数の委任タスクに分解する。
2. 【ロール設計】タスクごとに最適な専門家ロールを定義する。
   role 文に「視点・制約・完了基準」を明記するほど Specialist の精度が上がる。
3. 【委任】delegate_to_specialist を呼ぶ。独立したタスクは複数回並べて呼んでよい。
   task 文には目的・対象・制約を漏れなく書く（Specialist はあなたの会話履歴を持たない）。
4. 【適用は自動】can_write=True で変更が生じた場合、プロジェクトへの反映と
   AutoGit コミットは自動で行われる。**自分でファイルを書き換える必要はない**。
5. 【検証・報告】戻り値の差分サマリと回答内容を確認し、不足があれば追加の
   delegate_to_specialist を発行する。最終的な結果を日本語で簡潔にユーザーへ報告する。

## update_scratchpad（複数回の委任にまたがる記憶）
複数回 delegate_to_specialist を呼ぶ場合、各委任の前後で update_scratchpad を呼び
以下を整理しておくこと：
【ゴール】全体の目標
【委任結果】これまでの呼び出しと適用結果
【次の一手】次に委任する内容、または最終報告の準備

## ツール呼び出しの形式（必須）
**ツール呼び出しは必ずAPIのtool_calls機能（JSON形式）で行うこと。**
テキスト内に `<tool_call>`, `<function=...>`, `<invoke>` などのXML形式で
ツール名を書いても実行されない（最終回答として打ち切られる）。
"""

class InteractiveOrchestrator:
    """
    ReAct（Reason + Act）ベースの対話型オーケストレーター。

    フロー:
      1. Auto-Git バックアップ
      2. AI が Thought をストリーミング出力（中間ターンのみ端末表示）
      3. Tool call (Action) を実行 → 結果 (Observation) を AI に戻す
      4. 書き込み系ツール成功後に Auto-Git チェックポイント
      5. ツールなし応答 = 最終回答を返す（Markdown レンダリングして表示）
    """

    MAX_REACT_STEPS  = 120 # ReActループ上限
    MAX_EMPTY_RETRIES = 2  # 空レスポンス検知による再試行の上限

    def __init__(self, agent: "OpenRouterAgent", auto_git: "AutoGit"):
        self.agent    = agent
        self.auto_git = auto_git
        self.react_log = ReactLog()

    @staticmethod
    def _fmt_args(args: dict) -> str:
        return ", ".join(f"{k}={repr(v)[:40]}" for k, v in args.items())

    def _execute_with_intervention(
        self, fn_name: str, fn_args: dict, error_counts: dict,
        repeat_fail_counts: Optional[dict] = None,
        loop_state: Optional[dict] = None,
    ) -> str:
        """
        ツールを実行する。エラー発生時はAIに内容を返して自律的に解決させる（介入なし）。
        読み取り系ツールはキャッシュを利用する。
        同一引数の呼び出しが _MAX_IDENTICAL_TOOL_FAILURES 回失敗した後は実行を拒否し、
        拒否が _MAX_LOOP_REFUSALS 回を超えたら ToolLoopBreakError でターンを打ち切る。
        """
        # ── ループブレーカー: 反復失敗した同一呼び出しは実行しない ──
        call_key = _tool_call_key(fn_name, fn_args)
        if repeat_fail_counts is not None and \
                repeat_fail_counts.get(call_key, 0) >= _MAX_IDENTICAL_TOOL_FAILURES:
            if loop_state is not None:
                loop_state["refusals"] = loop_state.get("refusals", 0) + 1
                if loop_state["refusals"] > _MAX_LOOP_REFUSALS:
                    raise ToolLoopBreakError(fn_name)
            safe_print(C.yellow(
                f"    ⛔ [{fn_name}] 同一引数の失敗が{_MAX_IDENTICAL_TOOL_FAILURES}回に達したため実行拒否"
            ), flush=True)
            return (
                f"[ループ防止] この呼び出し（{fn_name}）は同一の引数で"
                f"{_MAX_IDENTICAL_TOOL_FAILURES}回失敗しているため、これ以上実行されません。\n"
                "引数を変える・別のツールを使う・アプローチを変える、のいずれかを行ってください。\n"
                "打つ手がない場合は、現状と失敗の内容を最終回答として報告してください。"
            )

        # ── キャッシュヒット確認（読み取り系のみ）────────────────
        if fn_name in _CACHEABLE_TOOLS:
            cache_key = self.agent._make_cache_key(fn_name, fn_args)
            if cache_key in self.agent._tool_cache:
                cached = self.agent._tool_cache[cache_key]
                safe_print(C.gray(f"    [キャッシュ] {len(cached)}文字 (再取得スキップ)"), flush=True)
                return cached

        # ── 自動実行（diff表示のみ） ──────────────────────────
        if fn_name in ("write_file", "edit_file", "patch_file"):
            _print_write_diff(fn_name, fn_args)

        try:
            result = self.agent.tools.execute(fn_name, fn_args)
            error_counts[fn_name] = 0
            result_str = cache_tool_output(fn_name, str(result))
            # キャッシュ登録 / 書き込み後の無効化
            if fn_name in _CACHEABLE_TOOLS:
                self.agent._tool_cache[cache_key] = result_str  # type: ignore[possibly-undefined]
            elif fn_name in ("write_file", "edit_file", "patch_file"):
                self.agent._invalidate_cache_for_path(fn_args.get("path", ""))
            return result_str
        except UserRejectedWriteError:
            raise  # run_react でキャッチしてループを即停止する
        except Exception as e:
            error_counts[fn_name] = error_counts.get(fn_name, 0) + 1
            err_msg = str(e)
            log.error({"event": "react_tool_error", "tool": fn_name,
                        "error": err_msg, "count": error_counts[fn_name]})
            safe_print(C.red(f"\n  ✗ [{fn_name}] エラー: {err_msg}"), flush=True)
            # ── ループブレーカー: 同一呼び出しの失敗を計数し、2回目で予告する ──
            repeat_hint = ""
            if repeat_fail_counts is not None:
                repeat_fail_counts[call_key] = repeat_fail_counts.get(call_key, 0) + 1
                n = repeat_fail_counts[call_key]
                if n == _MAX_IDENTICAL_TOOL_FAILURES - 1:
                    repeat_hint = (
                        f"\n⚠ 同一の呼び出しが{n}回連続で失敗しています。"
                        "次も同じ引数で呼ぶと実行が拒否されます。引数または手段を変えてください。"
                    )
            # エラーテキストをAIに返してAIに対処させる（自律的なリカバリ）
            return f"ツール実行エラー: {fn_name}: {err_msg}{repeat_hint}"

    def run_react(self, user_message: str, on_done=None) -> str:
        """
        ReActループのメインエントリポイント。

        Thought → Action → Observation を繰り返して最終回答を返す。
        on_done: 最終回答が確定した瞬間に呼ばれるコールバック(text) → str
                 教訓保存より前に呼ばれるので、MCP自動モードで即返しに使える。
        """
        try:
            return self._run_react_inner(user_message, on_done)
        except KeyboardInterrupt:
            safe_print(C.yellow("\n\n  [割り込み] Ctrl+C — ツール実行を中断しました。"), flush=True)
            return "処理を中断しました。"

    def _run_react_inner(self, user_message: str, on_done=None) -> str:
        from .tools import clear_read_files_registry
        clear_read_files_registry()

        # ── 0. チェックポイント確認（Worker/Researcher サブエージェントのみ）──
        _is_subagent = bool(_os.environ.get("MIMIC_NO_AUTOGIT"))
        _cp_path: Optional[_Path] = (
            _Path(self.agent.cwd) / _CHECKPOINT_FILE if _is_subagent else None
        )

        _from_checkpoint = False
        if _cp_path and _cp_path.exists():
            try:
                _cp = _json.loads(_cp_path.read_text(encoding="utf-8"))
                _cp_messages      = _cp.get("messages", [])
                _cp_step          = int(_cp.get("step", 0))
                _cp_read_call_ids = _cp.get("_read_call_ids", {})
                _cp_user_message  = _cp.get("user_message", user_message)
                _from_checkpoint = True
                safe_print(C.yellow(
                    f"  [Checkpoint] ステップ {_cp_step} から復元します"
                ), flush=True)
            except Exception as _e:
                safe_print(C.yellow(f"  [Checkpoint] 読み込み失敗: {_e}"), flush=True)

        # ── 1. Auto-Git バックアップ ──────────────────────────────
        backup_result = self.auto_git.backup(self.agent.cwd)
        safe_print(C.gray(f"  [AutoGit] {backup_result}"), flush=True)

        # ── 2. メッセージ構築 ─────────────────────────────────────
        self.react_log.add("user_input", content=user_message)

        if _from_checkpoint:
            messages: list[dict]          = list(_cp_messages)
            step_count                    = _cp_step
            _read_call_ids: dict[str, list[str]] = dict(_cp_read_call_ids)
            old_conv_len                  = len(self.agent.conversation)
            user_message                  = _cp_user_message
            # 継続委任（continue_specialist）はチェックポイントに専用ノートを埋めて
            # 「クラッシュ再開」ではなく「追加指示による継続」として文脈を再開する
            messages.append({
                "role": "user",
                "content": _cp.get("resume_note") or _CHECKPOINT_RESUME_NOTE,
                "_skip_save": True,
            })
        else:
            self.agent._compact_if_needed()
            ctx    = self.agent._build_context_header()
            task   = self.agent._task_context()
            prefix = "\n\n".join(p for p in [ctx, task] if p)
            aug_message = f"{prefix}\n\n{user_message}" if prefix else user_message

            messages: list[dict] = list(self.agent.conversation)
            old_conv_len = len(self.agent.conversation)  # ツール実行履歴保存用
            messages.append({"role": "user", "content": aug_message})
            step_count        = 0
            _read_call_ids: dict[str, list[str]] = {}

        empty_retry_count   = 0
        xml_tool_retry_count = 0
        had_tool_call       = False
        error_counts: dict[str, int] = {}
        repeat_fail_counts: dict[str, int] = {}   # ループブレーカー: 同一呼び出しの失敗数
        loop_state: dict[str, int] = {"refusals": 0}
        offload_retry_done   = False   # 最終回答ゲートA（丸投げ）の差し戻しは1回まで
        unverified_retry_done = False  # 最終回答ゲートB（未検証断言）の差し戻しは1回まで
        turn_had_unverified  = False   # ターン内に「※未検証」の委任結果があったか
        write_tools  = {"write_file", "edit_file", "patch_file", "delete_file"}

        # ── 3. ReActループ ───────────────────────────────────────
        while step_count < self.MAX_REACT_STEPS:
            # PipelineTypewriter でバッファ→レンダリング→タイプライター表示
            _tw = PipelineTypewriter(auto_mode=getattr(self, "_auto_mode", False))
            _tw.start()
            text, tool_calls = self.agent._stream_react_call(
                messages, text_callback=_tw.feed
            )
            _tw.finalize()

            # Ctrl+C 中断
            if text == "__interrupted__":
                return "処理を中断しました。"

            # ── XML形式ツール呼び出し救済 ────────────────────────
            # tool_callsが空でもテキストにXML形式の呼び出しが含まれていればパースして実行する
            if not tool_calls and text and _XML_TOOL_PATTERN.search(text):
                _xml_parsed = _parse_xml_tool_calls(text)
                if _xml_parsed:
                    safe_print(C.yellow(
                        f"  ⚠ XML形式ツール呼び出しを検知 → {len(_xml_parsed)}件をtool_callsとして実行"
                    ), flush=True)
                    tool_calls = _xml_parsed

            # ── ツールなし = 最終回答候補 ──────────────────────────
            if not tool_calls:
                # 空レスポンス検知: ツール実行後に空テキストが返された場合に報告を促す
                if (not text and had_tool_call
                        and empty_retry_count < self.MAX_EMPTY_RETRIES):
                    empty_retry_count += 1
                    safe_print(C.yellow(
                        f"  ⚠ 空レスポンス検知 → 報告を促します ({empty_retry_count}/{self.MAX_EMPTY_RETRIES})"
                    ), flush=True)
                    messages.append({"role": "assistant", "content": "（思考中...）", "_skip_save": True})
                    messages.append({"role": "user",
                        "content": "ツール実行結果を踏まえて、作業内容と結果を日本語で報告してください。",
                        "_skip_save": True,
                    })
                    step_count += 1
                    continue

                # XML検知したがパース失敗 → tool_calls形式で再送を促す
                if (text and _XML_TOOL_PATTERN.search(text)
                        and xml_tool_retry_count < _MAX_XML_TOOL_RETRIES):
                    xml_tool_retry_count += 1
                    safe_print(C.yellow(
                        f"  ⚠ XMLツール呼び出しのパース失敗 → 修正を促します"
                        f" ({xml_tool_retry_count}/{_MAX_XML_TOOL_RETRIES})"
                    ), flush=True)
                    messages.append({"role": "assistant", "content": text, "_skip_save": True})
                    messages.append({"role": "user",
                        "content": (
                            "[システム] ツール呼び出しがXML形式でテキストに含まれていましたが、"
                            "パースできませんでした。\n"
                            "ツールを呼び出す場合は、テキスト内に書かず、"
                            "APIのtool_calls機能（JSON形式）を使ってください。\n"
                            "直前のツール呼び出し意図をtool_calls形式で再送してください。"
                        ),
                        "_skip_save": True,
                    })
                    step_count += 1
                    continue

                # ── 最終回答ゲートA: 実行の丸投げ検知（1回だけ差し戻す）──
                if (not offload_retry_done and text
                        and _detect_command_offload(text, self.agent.tools._tools.keys())):
                    offload_retry_done = True
                    safe_print(C.yellow(
                        "  ⚠ 最終回答ゲート: ユーザーへの実行丸投げを検知 → 差し戻します"
                    ), flush=True)
                    messages.append({"role": "assistant", "content": text, "_skip_save": True})
                    messages.append({"role": "user", "content": (
                        "[システム] 回答内でユーザーにコマンド実行や手動修正を依頼していますが、"
                        "実行はあなたの仕事です。あなたが持っている実行・委任ツールを使って"
                        "自分で実行（または委任・承認付きホスト実行を提案）してから結果を報告してください。\n"
                        "この環境で本当に実行できない場合（認証・対話操作が必要等）のみ、"
                        "その理由を明記した上でユーザーへの依頼を残してください。"
                    ), "_skip_save": True})
                    step_count += 1
                    continue

                # ── 最終回答ゲートB: 未検証変更の断言検知（1回だけ差し戻す）──
                if (not unverified_retry_done and text
                        and _detect_unverified_claim(text, turn_had_unverified)):
                    unverified_retry_done = True
                    safe_print(C.yellow(
                        "  ⚠ 最終回答ゲート: 未検証の変更を断言 → 差し戻します"
                    ), flush=True)
                    messages.append({"role": "assistant", "content": text, "_skip_save": True})
                    messages.append({"role": "user", "content": (
                        "[システム] このターンの変更には「※未検証」のものが含まれています。"
                        "動作確認をしていない変更を「完了・解決」と断言しないでください。\n"
                        "回答を修正し、どこまでが確認済みでどこからが未検証かを明記して"
                        "再報告してください（可能なら検証を先に実行してもよい）。"
                    ), "_skip_save": True})
                    step_count += 1
                    continue

                final_text = text or "(応答なし)"
                self.react_log.add("final_answer", content=final_text)

                # ターン内の複数checkpointコミットを1つにまとめる（git log を読みやすくする）。
                # _checkpointsが空（書き込みなし）なら squash() は即リターンして何もしない。
                _sq_msg = f"🤖 task: {user_message[:72].replace(chr(10), ' ')}"
                _sq_result = self.auto_git.squash(self.agent.cwd, _sq_msg)
                if _sq_result:
                    safe_print(C.gray(f"  [AutoGit] {_sq_result}"), flush=True)

                # ツール実行履歴を含む全ターンを conversation に保存（内部マーカーを除外）
                self.agent.conversation.append({"role": "user", "content": user_message})
                _save_msgs = [m for m in messages[old_conv_len + 1:] if not m.get("_skip_save")]
                self.agent.conversation.extend(_save_msgs)
                self.agent.conversation.append({"role": "assistant", "content": final_text})

                # チェックポイント削除（正常完了）。
                # MIMIC_KEEP_CHECKPOINT=1（セッションWorker）の場合は会話状態を残し、
                # 次回の継続委任（continue_specialist）が文脈を引き継げるようにする。
                if _cp_path and not _os.environ.get("MIMIC_KEEP_CHECKPOINT"):
                    try:
                        _cp_path.unlink(missing_ok=True)
                    except Exception:
                        pass

                if on_done:
                    try:
                        on_done(final_text)
                    except Exception:
                        pass

                return final_text

            # ── アシスタント応答を OpenAI ネイティブ形式で追加 ──
            messages.append({
                "role": "assistant",
                "content": text or None,
                "tool_calls": [_build_tool_call_entry(tc) for tc in tool_calls],
            })

            # ── ツール実行（Action → Observation）───────────────
            tool_results: list[dict] = []

            # 書き込み系ツールが含まれる場合は逐次実行（チェックポイント・介入が必要）
            # 読み取り系のみなら並列実行
            has_write_tool = any(tc.get("name", "") in write_tools for tc in tool_calls)

            if len(tool_calls) > 1 and not has_write_tool:
                # ── 並列実行（読み取り系のみ）──────────────────────
                safe_print(C.orange(f"\n  ⚡ {len(tool_calls)} ツールを並列実行"), flush=True)
                ordered: list[Optional[dict]] = [None] * len(tool_calls)

                def _par_exec(idx_tc: tuple) -> tuple:
                    idx, tc = idx_tc
                    fn_n = tc.get("name", "")
                    fn_a = tc.get("args", {})
                    call_id = tc.get("id") or f"call_{fn_n}_{idx}"
                    safe_print(
                        f"  {C.bold_green('⚙')} {C.green(fn_n)}"
                        + C.cyan(f"({self._fmt_args(fn_a)})"),
                        flush=True,
                    )
                    self.react_log.add("action", tool=fn_n, args=fn_a, step=step_count)
                    ck = None  # キャッシュキー（非対象ツールでは未使用）
                    # キャッシュヒット確認
                    if fn_n in _CACHEABLE_TOOLS:
                        ck = self.agent._make_cache_key(fn_n, fn_a)
                        if ck in self.agent._tool_cache:
                            r_str = self.agent._tool_cache[ck]
                            safe_print(C.gray(f"    [キャッシュ] {len(r_str)}文字"), flush=True)
                            self.react_log.add("observation", tool=fn_n, result=r_str[:500], step=step_count)
                            return idx, fn_n, r_str, call_id, fn_a.get("path", "")
                    # ループブレーカー: 反復失敗した同一呼び出しは実行しない
                    _lb_key = _tool_call_key(fn_n, fn_a)
                    if repeat_fail_counts.get(_lb_key, 0) >= _MAX_IDENTICAL_TOOL_FAILURES:
                        r_str = (
                            f"[ループ防止] この呼び出し（{fn_n}）は同一の引数で"
                            f"{_MAX_IDENTICAL_TOOL_FAILURES}回失敗しているため実行されません。"
                            "引数または手段を変えてください。"
                        )
                        safe_print(C.yellow(f"    ⛔ [{fn_n}] 反復失敗のため実行拒否"), flush=True)
                        self.react_log.add("observation", tool=fn_n, result=r_str[:500], step=step_count)
                        return idx, fn_n, r_str, call_id, fn_a.get("path", "")
                    try:
                        r = self.agent.tools.execute(fn_n, fn_a)
                        r_str = cache_tool_output(fn_n, str(r))
                        if fn_n in _CACHEABLE_TOOLS:
                            self.agent._tool_cache[ck] = r_str  # type: ignore[possibly-undefined]
                    except Exception as e:
                        r_str = f"ツール実行エラー: {fn_n}: {e}"
                        repeat_fail_counts[_lb_key] = repeat_fail_counts.get(_lb_key, 0) + 1
                        log.error({"event": "react_tool_error_par", "tool": fn_n, "error": str(e)})
                        safe_print(C.red(f"  ✗ [{fn_n}] 並列実行エラー: {e}"), flush=True)
                        safe_print(C.gray("    （並列実行中のため自動リトライ・介入なし — AIがリカバリします）"), flush=True)
                    obs_preview = r_str[:300].replace("\n", " ")
                    safe_print(C.cyan(f"  👁 {obs_preview}"), flush=True)
                    self.react_log.add("observation", tool=fn_n, result=r_str[:500], step=step_count)
                    return idx, fn_n, r_str, call_id, fn_a.get("path", "")

                with ThreadPoolExecutor(max_workers=len(tool_calls)) as tpool:
                    for idx, fn_n, r_str, call_id, _path in tpool.map(_par_exec, enumerate(tool_calls)):
                        ordered[idx] = {"tool": fn_n, "result": r_str, "call_id": call_id, "path": _path}
                tool_results = ordered  # type: ignore
            else:
                # ── 逐次実行（書き込み系を含む場合・単一ツール）──────
                for tc in tool_calls:
                    fn_name = tc.get("name", "")
                    fn_args = tc.get("args", {})
                    call_id = tc.get("id") or f"call_{fn_name}"
                    args_preview = self._fmt_args(fn_args)

                    safe_print(
                        f"\n  {C.bold_green('⚙')} {C.green(fn_name)}"
                        + C.cyan(f"({args_preview})"),
                        flush=True,
                    )
                    self.react_log.add("action", tool=fn_name, args=fn_args, step=step_count)

                    try:
                        result_str = self._execute_with_intervention(
                            fn_name, fn_args, error_counts,
                            repeat_fail_counts=repeat_fail_counts, loop_state=loop_state)
                    except UserRejectedWriteError as e:
                        safe_print(C.yellow(f"\n  ✋ 書き込みを拒否しました（{e}）。処理を中断します。"), flush=True)
                        safe_print(C.gray("  新しい指示を入力してください。"), flush=True)
                        return "書き込みが拒否されたため処理を中断しました。"
                    except ToolLoopBreakError as e:
                        safe_print(C.red(
                            f"\n  ⛔ 同一ツール呼び出し（{e}）の失敗反復が上限を超えたため処理を中断します。"
                        ), flush=True)
                        return (
                            f"同一のツール呼び出し（{e}）が同じ引数で失敗し続けたため、処理を中断しました。\n"
                            "アプローチを変えた指示を出すか、対象の状態を確認してください。"
                        )

                    # Auto-checkpoint: 書き込み系ツール成功後に自動コミット
                    # エラー・スキップ・キャンセル時はチェックポイントを行わない
                    _non_success = (
                        "ツール実行エラー: ",
                        "[ユーザーがスキップを選択]",
                        "[ユーザーがキャンセル]",
                        "ユーザーによるキャンセル: ",
                        "[ユーザー指示]",
                    )
                    if fn_name in write_tools and not any(
                        result_str.startswith(p) for p in _non_success
                    ):
                        self.auto_git.checkpoint(
                            self.agent.cwd, fn_name, fn_args.get("path", "")
                        )

                    obs_preview = result_str[:300].replace("\n", " ")
                    safe_print(C.cyan(f"  👁 {obs_preview}"), flush=True)
                    self.react_log.add(
                        "observation", tool=fn_name,
                        result=result_str[:500], step=step_count
                    )
                    tool_results.append({
                        "tool":    fn_name,
                        "result":  result_str,
                        "call_id": call_id,
                        "path":    fn_args.get("path", ""),
                    })

            # 未検証の委任結果があったかを記録（最終回答ゲートBで使用）
            if any("※未検証" in str(r.get("result", "")) for r in tool_results if r):
                turn_had_unverified = True

            # ── Observation を OpenAI ネイティブ形式（role: tool）で追加 ──
            for r in tool_results:
                fn_n = r["tool"]
                path = r.get("path", "")
                # 書き込み系: 同一ファイルの古いread観測を無効化
                if fn_n in write_tools and path:
                    for stale_id in _read_call_ids.pop(path, []):
                        for m in messages:
                            if m.get("role") == "tool" and m.get("tool_call_id") == stale_id:
                                m["content"] = "[このread結果は後で上書きされました—省略]"
                                break
                if fn_n in _DELEGATION_TOOLS:
                    _obs_limit = _DELEGATION_OBS_MAX_CHARS
                elif fn_n in _PEEK_TOOLS and "write_file" not in self.agent.tools._tools:
                    # 書き込みツールなし = 委任特化Director → 読み取りは覗き見上限
                    _obs_limit = _PEEK_OBS_MAX_CHARS
                else:
                    _obs_limit = _OBS_MAX_CHARS
                obs = cache_obs(fn_n, r["result"], threshold=_obs_limit)
                cid = r["call_id"]
                # 読み取り系: call_idを記録してあとで無効化できるようにする
                if fn_n == "read_file" and path:
                    _read_call_ids.setdefault(path, []).append(cid)
                messages.append({
                    "role": "tool",
                    "tool_call_id": cid,
                    "content": obs,
                })
            had_tool_call = True
            step_count += 1

            # ── チェックポイント保存 ─────────────────────────────
            if _cp_path:
                try:
                    _cp_path.write_text(
                        _json.dumps({
                            "messages": [m for m in messages if not m.get("_skip_save")],
                            "step": step_count,
                            "_read_call_ids": _read_call_ids,
                            "user_message": user_message,
                        }, ensure_ascii=False),
                        encoding="utf-8",
                    )
                except Exception:
                    pass  # overlay I/O エラーは無視

        # ループ上限到達 → チェックポイントを保存して再開可能にする
        if _cp_path:
            try:
                _cp_path.write_text(
                    _json.dumps({
                        "messages": [m for m in messages if not m.get("_skip_save")],
                        "step": step_count,
                        "_read_call_ids": _read_call_ids,
                        "user_message": user_message,
                    }, ensure_ascii=False),
                    encoding="utf-8",
                )
            except Exception:
                pass

        fallback = f"(ReActループ上限 {self.MAX_REACT_STEPS} ステップに達しました)"
        self.agent.conversation.append({"role": "user", "content": user_message})
        _save_msgs = [m for m in messages[old_conv_len + 1:] if not m.get("_skip_save")]
        self.agent.conversation.extend(_save_msgs)
        self.agent.conversation.append({"role": "assistant", "content": fallback})
        return fallback



# (DualModelOrchestrator は削除済み — Plan モードに統合)
