# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import subprocess
import re
import os
import ast
import difflib
import json
import time
import threading
import traceback
import urllib.request
import urllib.error
import urllib.parse
import http.client
from pathlib import Path
from typing import Optional, Any
from concurrent.futures import ThreadPoolExecutor

# ── 書き込み承認フック ────────────────────────────────────────

class UserRejectedWriteError(Exception):
    """ユーザーが書き込み確認で拒否したときに送出される。ReActループを即停止させる。"""
    pass

_write_approval_handler = None   # Callable[[str, dict, str], bool] | None
_approval_lock = threading.Lock()

def set_write_approval_handler(handler):
    """React モード用: write_file/edit_file/patch_file 前の承認ハンドラーを登録する。
    None を渡すと承認なし（Plan-and-Execute モード用）。"""
    global _write_approval_handler
    _write_approval_handler = handler

def _request_write_approval(tool_name: str, args: dict, preview: str) -> None:
    """承認ハンドラーが設定されていれば呼び出す。拒否された場合は UserRejectedWriteError を送出。"""
    if _write_approval_handler is None:
        return
    with _approval_lock:
        approved = _write_approval_handler(tool_name, args, preview)
    if not approved:
        raise UserRejectedWriteError(args.get("path", "?"))

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    sync_playwright = None  # type: ignore
from .utils import (safe_print, C, log, _try_read_file_text,
                    cache_tool_output, _tool_output_cache, _TOOL_CHUNK_SIZE,
                    get_scratchpad, set_scratchpad)
from .config import OpenRouterConfig

# ── 精度改善用レジストリ（スレッドローカル） ─────────────────────
_tls = threading.local()

def _get_registry() -> set:
    """現在スレッドの読み取り履歴 set を返す（未初期化なら空 set を生成）。"""
    if not hasattr(_tls, "registry"):
        _tls.registry = set()
    return _tls.registry

def clear_read_files_registry():
    """ターンの開始時に読み取り履歴をリセットする。"""
    _get_registry().clear()

def _check_worker_write_boundary(path: str) -> str:
    """Worker（OverlayFS隔離サブプロセス）実行時、作業部屋の外への書き込みを拒否する。

    Overlay隔離は作業ディレクトリ（merged）のマウントにしか効かないため、
    絶対パスで外部へ書くとホストFSへ直接書き込まれ、差分検出（changed_files）にも
    掛からず適用もロールバックもできない「見えない書き込み」になる。
    エラー文字列を返した場合、呼び出し元は書き込みを行わずそれをそのまま返すこと。"""
    if not os.environ.get("MIMIC_NO_AUTOGIT"):
        return ""
    try:
        root = Path.cwd().resolve()
        Path(path).resolve().relative_to(root)
    except ValueError:
        return (
            f"エラー: 作業ディレクトリ（{Path.cwd()}）の外への書き込みは禁止されています: {path}\n"
            "この環境はOverlayFS隔離されており、外部への書き込みは差分として検出・適用されません。\n"
            "作業ディレクトリ内の相対パスで書き込んでください。"
            "外部ファイルの変更が必要な場合は、その旨を最終回答でDirectorに報告してください。"
        )
    except Exception:
        return ""
    return ""


def _check_read_warning(path: str) -> str:
    """ファイルが現在のターンで read_file されたか確認し、警告を返す。"""
    resolved = str(Path(path).resolve())
    if resolved not in _get_registry():
        return "⚠ 警告: このファイルは現在のターンで read_file されていません。内容を確認せずに編集しています。\n"
    return ""


def _generate_diff(old_text: str, new_text: str) -> str:
    """変更前後の差分を生成し、最大30行まで返す"""
    old_lines = old_text.splitlines(keepends=True)
    new_lines = new_text.splitlines(keepends=True)
    diff = list(difflib.unified_diff(old_lines, new_lines, n=3))
    
    if not diff:
        return ""
    
    if len(diff) > 30:
        # 行数を計算
        plus = sum(1 for l in diff if l.startswith('+') and not l.startswith('+++'))
        minus = sum(1 for l in diff if l.startswith('-') and not l.startswith('---'))
        diff_content = f"（差分が長いため省略。変更行数: +{plus}/-{minus}）"
    else:
        diff_content = "".join(diff).strip()
    
    return f"\n─── 差分 ───────────────────────────\n{diff_content}\n────────────────────────────────────"



class ExecutionRegistry:
    """
    スラッシュコマンドを登録・ルーティングするレジストリ。

    登録: @registry.register("name", "説明") デコレータ
    ルーティング: route("/name args") → (name, handler, args) または None

    handler のシグネチャ: fn(agent: OpenRouterAgent, args: str) -> None
    """

    def __init__(self):
        self._commands: dict[str, tuple[str, Any]] = {}  # name -> (description, handler)

    def register(self, name: str, description: str):
        def decorator(fn):
            self._commands[name.lower()] = (description, fn)
            return fn
        return decorator

    def route(self, text: str) -> Optional[tuple[str, Any, str]]:
        """
        スラッシュコマンドをパースしてハンドラを返す。
        Returns: (name, handler, remaining_args) or None
        """
        if not text.startswith("/"):
            return None
        parts = text[1:].split(maxsplit=1)
        key = parts[0].lower()
        args = parts[1] if len(parts) > 1 else ""
        if key in self._commands:
            _, handler = self._commands[key]
            return key, handler, args
        return None

    def help_text(self) -> str:
        lines = ["コマンド一覧:"]
        for name, (desc, _) in sorted(self._commands.items()):
            lines.append(f"  /{name:<20} - {desc}")
        lines.append("  exit                  - 終了")
        return "\n".join(lines)

class ToolRegistry:
    """エージェントが使えるツールを管理"""

    def __init__(self):
        self._tools: dict[str, dict] = {}

    def register(self, name: str, description: str, parameters: dict, short_desc: str = ""):
        """ツールを登録（OpenAI tools 形式でネイティブ保存）。short_desc はTPM制約時の短縮説明文。"""
        def decorator(fn):
            self._tools[name] = {
                "fn": fn,
                "short_desc": short_desc or description,
                "spec": {
                    "type": "function",
                    "function": {
                        "name": name,
                        "description": description,
                        "parameters": parameters,
                    },
                }
            }
            return fn
        return decorator

    def get_specs(self, short: bool = False) -> list[dict]:
        if not short:
            return [v["spec"] for v in self._tools.values()]
        result = []
        for v in self._tools.values():
            spec = v["spec"]
            sd = v.get("short_desc", "")
            if sd and sd != spec["function"]["description"]:
                import copy
                spec = copy.deepcopy(spec)
                spec["function"]["description"] = sd
            result.append(spec)
        return result

    def unregister(self, name: str) -> bool:
        """ツールを登録解除する。存在しない場合は False を返す。"""
        return self._tools.pop(name, None) is not None

    def copy_tool(self, name: str, source: "ToolRegistry") -> bool:
        """source レジストリからツール1件をコピーする。存在しない場合は False を返す。"""
        if name not in source._tools:
            return False
        self._tools[name] = source._tools[name]  # short_desc も含めてコピー
        return True

    def execute(self, name: str, args: dict) -> Any:
        if name not in self._tools:
            raise ValueError(f"未知のツール: {name}")
        log.info({"tool_call": name, "args": args})
        return self._tools[name]["fn"](**args)

tools = ToolRegistry()
_browser_registry = ToolRegistry()


@tools.register(
    name="update_scratchpad",
    description="作業メモを更新する（800字以内）。ゴール・完了済み・次のステップ・発見事項を記録し記憶喪失を防ぐ。",
    parameters={
        "type": "object",
        "properties": {
            "content": {"type": "string", "description": "スクラッチパッドに書き込む内容（800字以内、所定フォーマットで記述）"}
        },
        "required": ["content"]
    }
)
def update_scratchpad(content: str) -> str:
    if len(content) > 800:
        content = content[:800] + "\n…（上限800字で切り捨て）"
    set_scratchpad(content)
    return f"スクラッチパッドを更新しました（{len(content)}文字）"


def update_scratchpad_smart(content: str) -> str:
    """
    計画書 Step 3: 上限超過時に機械的切り捨てを防ぐスマート版。
    ScribeAgent が利用可能な場合は呼び出し元で圧縮を依頼すること。
    単体で使う場合は先頭優先で 800 文字を保持する。
    """
    if len(content) <= 800:
        set_scratchpad(content)
        return "✓ スクラッチパッドを更新しました。"
    # 末尾ではなく先頭（ゴール・完了済み）を優先して保持
    safe_content = content[:797] + "…"
    set_scratchpad(safe_content)
    return (
        "⚠️ 800文字を超えたため先頭 800 文字を保持しました。\n"
        "記憶担当（Scribe）による圧縮を推奨します: /mode multi を使用してください。"
    )

# utils._TOOL_CHUNK_SIZE と統一（どちらも 10000 文字チャンク）
_READ_FILE_CHAR_CHUNK = _TOOL_CHUNK_SIZE

@tools.register(
    name="read_file",
    description=(
        f"ファイルを{_READ_FILE_CHAR_CHUNK}文字単位で読む。offset で続きを読める。"
        "大きいファイルは先に grep_codebase を試すこと。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "path":   {"type": "string",  "description": "読み取るファイルパス"},
            "offset": {"type": "integer", "description": "読み取り開始文字位置（デフォルト0）", "default": 0},
        },
        "required": ["path"]
    }
)
def read_file(path: str, offset: int = 0) -> str:
    p = Path(path)
    if not p.exists():
        return f"エラー: ファイルが見つかりません: {path}"

    # 読み取り履歴に登録（スレッドローカル）
    _get_registry().add(str(p.resolve()))

    content = _try_read_file_text(p)
    total = len(content)

    # 大ファイルかつ先頭から読む場合は Pipeline-First を促す
    _LARGE_FILE_THRESHOLD = 5000
    if total > _LARGE_FILE_THRESHOLD and offset == 0:
        preview = content[:1500]
        return (
            f"[read_file: {path}]\n"
            f"⚠ このファイルは {total:,} 文字あります（推奨上限 {_LARGE_FILE_THRESHOLD:,} 文字）。\n"
            f"コンテキスト節約のため以下を先に検討してください:\n"
            f"  • grep_codebase(pattern='キーワード', path='{path}')  ← 特定箇所だけ取得\n"
            f"  • smart_read(path='{path}', focus='関数名')            ← focus 指定で絞り込み\n"
            f"  • grep_codebase(pattern='...')                         ← 複数ファイル横断検索\n"
            f"それでも全文が必要な場合は read_file(path='{path}', offset=0) を続けてください。\n"
            f"{'─' * 60}\n"
            f"--- 先頭 1,500文字（プレビュー）---\n{preview}\n"
            f"{'─' * 60}\n"
            f"続き: read_file(path='{path}', offset=1500)\n"
        )
    chunk = _READ_FILE_CHAR_CHUNK


    sliced = content[offset: offset + chunk]
    end = offset + len(sliced)
    remaining = total - end

    header = f"[{path}  文字 {offset}–{end} / 全{total}文字]\n{'─' * 60}\n"

    if remaining > 0:
        footer = (
            f"\n{'─' * 60}\n"
            f"⚠ 残り {remaining} 文字\n"
            f"  続きを読む: offset={end}\n"
            f"{'─' * 60}"
        )
    else:
        footer = f"\n{'─' * 60}\n  ✓ ファイル末尾まで読み込み完了\n{'─' * 60}"

    return header + sliced + footer

@tools.register(
    name="read_tool_cache",
    description=(
        "ツール出力が長くてキャッシュされた場合に続きを読む。"
        "cache_tool_output が返したフッターに書かれた cache_key と offset を指定する。"
        "例: read_tool_cache(cache_key=\"run_bash_001\", offset=10000)"
    ),
    parameters={
        "type": "object",
        "properties": {
            "cache_key": {"type": "string", "description": "キャッシュキー（ツール出力のフッターに記載）"},
            "offset":    {"type": "integer", "description": "読み取り開始文字位置", "default": 0}
        },
        "required": ["cache_key"]
    }
)
def read_tool_cache(cache_key: str, offset: int = 0) -> str:
    result = _tool_output_cache.get(cache_key)
    if result is None:
        return f"エラー: cache_key '{cache_key}' が見つかりません。利用可能なキー: {list(_tool_output_cache.keys())}"

    total = len(result)
    sliced = result[offset: offset + _TOOL_CHUNK_SIZE]
    end = offset + len(sliced)
    remaining = total - end

    header = f"[{cache_key}  文字 {offset}–{end} / 全{total}文字]\n{'─' * 60}\n"
    if remaining > 0:
        footer = (
            f"\n{'─' * 60}\n"
            f"⚠ 残り {remaining} 文字\n"
            f"  続きを読む: read_tool_cache(cache_key=\"{cache_key}\", offset={end})\n"
            f"{'─' * 60}"
        )
    else:
        footer = f"\n{'─' * 60}\n  ✓ 末尾まで読み込み完了\n{'─' * 60}"
    return header + sliced + footer

@tools.register(
    name="get_repo_map",
    description=(
        "プロジェクトのディレクトリ構造とPythonファイルのクラス・関数構成をツリー状に取得する。"
        "不明なプロジェクト構造を把握するのに最適。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "構造を取得するルートディレクトリ（デフォルト: .）", "default": "."}
        }
    }
)
def get_repo_map(path: str = ".") -> str:
    import ast
    root = Path(path)
    if not root.exists():
        return f"エラー: ディレクトリが見つかりません: {path}"

    ignore_dirs = {".git", "__pycache__", "venv", "node_modules", ".idea", ".vscode"}
    output = [f"RepoMap: {root.resolve()}"]

    def _get_py_info(p: Path) -> str:
        try:
            content = _try_read_file_text(p)
            tree = ast.parse(content)
            defs = []
            for node in tree.body:
                if isinstance(node, ast.ClassDef):
                    methods = [n.name for n in node.body if isinstance(n, ast.FunctionDef)]
                    meth_str = f"({', '.join(methods)})" if methods else ""
                    defs.append(f"class {node.name}{meth_str}")
                elif isinstance(node, ast.FunctionDef):
                    defs.append(f"def {node.name}(...)")
            return " [" + ", ".join(defs[:10]) + (", ..." if len(defs) > 10 else "") + "]"
        except Exception:
            return ""

    for item in sorted(root.rglob("*")):
        if any(ignored in item.parts for ignored in ignore_dirs):
            continue
        rel = item.relative_to(root)
        depth = len(rel.parts)
        indent = "  " * (depth - 1)
        prefix = indent + ("└── " if depth > 0 else "")
        
        info = ""
        if item.is_file() and item.suffix == ".py":
            info = _get_py_info(item)
        
        line = f"{prefix}{item.name}{'/' if item.is_dir() else ''}{info}"
        output.append(line)
        
        if len("\n".join(output)) > 20000:
            output.append("... (出力制限のため省略)")
            break

    return "\n".join(output)

@tools.register(
    name="write_file",
    description="ローカルファイルに内容を書き込む",
    parameters={
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "書き込み先ファイルパス"},
            "content": {"type": "string", "description": "書き込む内容"}
        },
        "required": ["path", "content"]
    }
)
def write_file(path: str, content: str) -> str:
    boundary_error = _check_worker_write_boundary(path)
    if boundary_error:
        return boundary_error
    warning = _check_read_warning(path)
    p = Path(path)
    preview = f"  書き込み内容（先頭30行）:\n" + "\n".join(content.splitlines()[:30])
    _request_write_approval("write_file", {"path": path}, preview)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    
    return f"{warning}書き込み完了: {path} ({len(content)} 文字)"


@tools.register(
    name="edit_file",
    description="ファイルの特定部分を差分編集する。old_string を new_string に置き換える。ファイル全体の再書き込みより安全で正確。",
    parameters={
        "type": "object",
        "properties": {
            "path":       {"type": "string", "description": "編集するファイルパス"},
            "old_string": {"type": "string", "description": "置き換え対象の文字列（ファイル内で一意である必要あり）"},
            "new_string": {"type": "string", "description": "置き換え後の文字列"}
        },
        "required": ["path", "old_string", "new_string"]
    }
)
def edit_file(path: str, old_string: str, new_string: str) -> str:
    boundary_error = _check_worker_write_boundary(path)
    if boundary_error:
        return boundary_error
    warning = _check_read_warning(path)
    p = Path(path)
    old_preview = "\n".join(old_string.splitlines()[:15])
    new_preview = "\n".join(new_string.splitlines()[:15])
    preview = f"  変更前（先頭15行）:\n{old_preview}\n  変更後（先頭15行）:\n{new_preview}"
    _request_write_approval("edit_file", {"path": path}, preview)
    if not p.exists():
        return f"エラー: ファイルが見つかりません: {path}"
    content = _try_read_file_text(p)
    count = content.count(old_string)
    if count == 1:
        new_content = content.replace(old_string, new_string, 1)
        p.write_text(new_content, encoding="utf-8")
        
        diff_lines = new_string.count("\n") - old_string.count("\n")
        sign = "+" if diff_lines >= 0 else ""
        
        res = f"{warning}編集完了: {path}  ({sign}{diff_lines} 行差分, 計 {new_content.count(chr(10))+1} 行)"
        return res + _generate_diff(content, new_content)
    if count > 1:
        return (
            f"エラー: 指定した文字列が {count} 箇所に存在します（一意に特定できません）。\n"
            f"前後の文脈をより多く含めた文字列を指定してください。"
        )
    # 完全一致なし → LLM にエラーを返す（patch_file への横流しは二重承認を生むため廃止）
    preview = old_string[:120].replace("\n", "↵")
    return (
        f"{warning}エラー: 指定された 'old_string' がファイル内に見つかりません: {path}\n"
        f"検索対象（先頭120文字）: {preview}\n"
        f"対処法:\n"
        f"  ① grep_codebase や smart_read で現在のファイル内容を確認し、正確な文字列で再実行してください。\n"
        f"  ② インデントのズレが疑われる場合は patch_file を明示的に指定してください。"
    )

@tools.register(
    name="web_search",
    description="キーワードでWebを検索して結果（タイトル・URL・概要）を返す。DuckDuckGo使用、APIキー不要。",
    parameters={
        "type": "object",
        "properties": {
            "query":       {"type": "string",  "description": "検索クエリ"},
            "max_results": {"type": "integer", "description": "最大件数（デフォルト5）", "default": 5}
        },
        "required": ["query"]
    }
)
def web_search(query: str, max_results: int = 5) -> str:
    encoded = urllib.parse.quote_plus(query)
    url = f"https://html.duckduckgo.com/html/?q={encoded}"
    req = urllib.request.Request(url, headers={
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
        ),
        "Accept-Language": "ja,en-US;q=0.9,en;q=0.8",
    })

    def _strip(s: str) -> str:
        return re.sub(r"<[^>]+>", "", s).replace("&amp;", "&").replace("&#x2F;", "/").strip()

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            html = resp.read().decode("utf-8", errors="replace")
    except Exception as e:
        log.error({"event": "web_search_error", "query": query, "error": str(e)})
        return f"Web検索エラー: {e}"

    # DuckDuckGo HTML 構造: result__a (タイトル+href), result__snippet (概要)
    # href は /l/?uddg=<encoded_url> 形式のリダイレクト
    title_pat   = re.compile(r'class="result__a"[^>]+href="([^"]*)"[^>]*>(.*?)</a>', re.DOTALL)
    snippet_pat = re.compile(r'class="result__snippet"[^>]*>(.*?)</a>', re.DOTALL)

    titles_urls = title_pat.findall(html)
    snippets    = [_strip(s) for s in snippet_pat.findall(html)]

    if not titles_urls:
        # フォールバック: href に uddg= が含まれる <a> を探す
        fallback = re.findall(r'href="(/l/\?uddg=[^"]+)"[^>]*>(.*?)</a>', html, re.DOTALL)
        titles_urls = fallback

    results = []
    for i, (href, title) in enumerate(titles_urls):
        if i >= max_results:
            break
        title_clean = _strip(title)
        # リダイレクトURLから実URLを復元
        uddg_m = re.search(r"uddg=([^&\"]+)", href)
        actual_url = urllib.parse.unquote(uddg_m.group(1)) if uddg_m else href
        snippet = snippets[i] if i < len(snippets) else ""
        results.append(f"[{i+1}] {title_clean}\n    {actual_url}\n    {snippet}")

    if not results:
        return f"「{query}」の検索結果が見つかりませんでした。"

    return f"Web検索: 「{query}」\n\n" + "\n\n".join(results)

@tools.register(
    name="fetch_webpage",
    description=(
        "URLのWebページを取得してテキストを抽出する。"
        "web_searchで得たURLの内容を詳しく読む・ドキュメントを参照する・記事全文を確認するのに使う。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "url":       {"type": "string",  "description": "取得するURL"},
            "max_chars": {"type": "integer", "description": "最大文字数（デフォルト10000）", "default": 10000}
        },
        "required": ["url"]
    }
)
def fetch_webpage(url: str, max_chars: int = 10000) -> str:
    req = urllib.request.Request(url, headers={
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
        ),
        "Accept-Language": "ja,en-US;q=0.9,en;q=0.8",
    })
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            content_type = resp.headers.get("Content-Type", "")
            # charset 検出
            charset = "utf-8"
            if "charset=" in content_type:
                charset = content_type.split("charset=")[-1].strip().split(";")[0].strip()
            raw = resp.read()
    except Exception as e:
        return f"ページ取得エラー: {e}"

    try:
        html = raw.decode(charset, errors="replace")
    except (LookupError, UnicodeDecodeError):
        html = raw.decode("utf-8", errors="replace")

    # <script> <style> <nav> <footer> <header> を除去
    for tag in ("script", "style", "nav", "footer", "header", "aside"):
        html = re.sub(rf"<{tag}[^>]*>.*?</{tag}>", " ", html,
                      flags=re.DOTALL | re.IGNORECASE)
    # HTMLコメント除去
    html = re.sub(r"<!--.*?-->", " ", html, flags=re.DOTALL)

    # タイトル抽出
    title_m = re.search(r"<title[^>]*>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    title = re.sub(r"<[^>]+>", "", title_m.group(1)).strip() if title_m else ""

    # タグを除去してテキスト化
    text = re.sub(r"<[^>]+>", " ", html)

    # HTML エンティティ変換
    entities = {
        "&amp;": "&", "&lt;": "<", "&gt;": ">", "&nbsp;": " ",
        "&#39;": "'", "&quot;": '"', "&#x2F;": "/", "&apos;": "'",
    }
    for ent, char in entities.items():
        text = text.replace(ent, char)
    # 数値エンティティ（例: &#12354; → あ）
    text = re.sub(r"&#(\d+);",
                  lambda m: chr(int(m.group(1))) if int(m.group(1)) < 0x110000 else "", text)

    # 空白正規化
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = text.strip()

    header = f"URL: {url}\n"
    if title:
        header += f"タイトル: {title}\n"
    header += "\n"

    body = text[:max_chars]
    suffix = f"\n\n... (全 {len(text):,} 文字中 {max_chars:,} 文字を表示)" if len(text) > max_chars else ""
    return header + body + suffix



@tools.register(
    name="patch_file",
    description=(
        "Search & Replace ブロック方式でファイルを編集する（Aider/Cline スタイル）。"
        "インデントのズレをある程度許容してマッチする。"
        "edit_file より耐障害性が高い。変更前に read_file で内容を確認すること。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "path":    {"type": "string", "description": "編集するファイルパス"},
            "search":  {"type": "string", "description": "置き換え対象のコードブロック（前後の行を含めて一意にすること）"},
            "replace": {"type": "string", "description": "置き換え後のコードブロック"},
        },
        "required": ["path", "search", "replace"]
    }
)
def patch_file(path: str, search: str, replace: str) -> str:
    boundary_error = _check_worker_write_boundary(path)
    if boundary_error:
        return boundary_error
    warning = _check_read_warning(path)
    p = Path(path)
    search_preview = "\n".join(search.splitlines()[:15])
    replace_preview = "\n".join(replace.splitlines()[:15])
    preview = f"  検索文字列（先頭15行）:\n{search_preview}\n  置換文字列（先頭15行）:\n{replace_preview}"
    _request_write_approval("patch_file", {"path": path}, preview)
    if not p.exists():
        return f"エラー: ファイルが見つかりません: {path}"
    content = _try_read_file_text(p)

    # ── 1. 完全一致を試みる ───────────────────────────────────────
    if search in content:
        count = content.count(search)
        if count > 1:
            return (
                f"エラー: 検索ブロックが {count} 箇所に存在します（一意に特定できません）。\n"
                f"より長い範囲の文字列を指定して、一意に特定できるようにしてください。"
            )
        new_content = content.replace(search, replace, 1)
        p.write_text(new_content, encoding="utf-8")
        diff_lines = replace.count("\n") - search.count("\n")
        sign = "+" if diff_lines >= 0 else ""
        
        res = f"{warning}編集完了（完全一致）: {path}  ({sign}{diff_lines} 行差分)"
        return res + _generate_diff(content, new_content)

    # ── 2. インデント正規化後にファジーマッチ ────────────────────

    def strip_common_indent(text: str) -> tuple[str, int]:
        """共通インデントを除去して (正規化テキスト, インデント幅) を返す"""
        lines = text.splitlines()
        non_empty = [l for l in lines if l.strip()]
        if not non_empty:
            return text, 0
        min_indent = min(len(l) - len(l.lstrip()) for l in non_empty)
        stripped = "\n".join(
            l[min_indent:] if len(l) >= min_indent else l for l in lines
        )
        return stripped, min_indent

    content_lines = content.splitlines()
    s_stripped, s_indent = strip_common_indent(search)
    s_lines = s_stripped.splitlines()
    n = len(s_lines)

    def apply_and_write(content_lines: list, i: int, n: int,
                        block: str, b_indent: int) -> str:
        """マッチしたブロックを replace で置換してファイルに書く共通処理"""
        indent_delta = b_indent - s_indent
        r_stripped, _ = strip_common_indent(replace)
        r_lines = r_stripped.splitlines()
        if indent_delta >= 0:
            re_indented = "\n".join(
                " " * indent_delta + l if l.strip() else l for l in r_lines
            )
        else:
            r_min = min(
                (len(l) - len(l.lstrip()) for l in r_lines if l.strip()), default=0
            )
            trim = min(-indent_delta, r_min)
            re_indented = "\n".join(
                l[trim:] if len(l) >= trim else l for l in r_lines
            )
        new_lines = (content_lines[:i]
                     + re_indented.splitlines()
                     + content_lines[i + n:])
        trailing = "\n" if content.endswith("\n") else ""
        p.write_text("\n".join(new_lines) + trailing, encoding="utf-8")
        return re_indented, block

    matches = []
    for i in range(len(content_lines) - n + 1):
        block = "\n".join(content_lines[i:i + n])
        b_stripped, b_indent = strip_common_indent(block)
        if ([l.strip() for l in b_stripped.splitlines()] ==
                [l.strip() for l in s_lines]):
            matches.append((i, block, b_indent))

    if len(matches) == 1:
        i, block, b_indent = matches[0]
        re_indented, block = apply_and_write(content_lines, i, n, block, b_indent)
        diff_lines = re_indented.count("\n") - block.count("\n")
        sign = "+" if diff_lines >= 0 else ""
        return (
            f"編集完了（インデント許容マッチ）: {path}  "
            f"({sign}{diff_lines} 行差分, indent_delta={b_indent - s_indent:+})"
        )
    if len(matches) > 1:
        return f"エラー: 検索ブロックが {len(matches)} 箇所にマッチします（一意に特定できません）。"

    # ── 3. difflib SequenceMatcher による類似ブロック探索 ─────────
    import difflib
    s_key = [l.strip() for l in s_lines if l.strip()]  # 空行除いた比較キー
    best_ratio = 0.0
    best_i = -1
    best_n = n  # 検索行数 ±2 の範囲でウィンドウ幅を変えて探す
    THRESHOLD = 0.85 # より厳格化

    for win in range(max(1, n - 2), n + 3):
        for i in range(len(content_lines) - win + 1):
            block_lines = content_lines[i:i + win]
            b_key = [l.strip() for l in block_lines if l.strip()]
            ratio = difflib.SequenceMatcher(None, s_key, b_key).ratio()
            if ratio > best_ratio:
                best_ratio = ratio
                best_i = i
                best_n = win

    if best_ratio >= THRESHOLD and best_i >= 0:
        block_preview = "\n".join(content_lines[best_i:best_i + min(best_n, 10)])
        return (
            f"エラー: 完全一致が見つかりません（類似度 {best_ratio:.2f}、行 {best_i+1}–{best_i+best_n}）。\n"
            f"誤書き込みを防ぐため自動修正しません。\n"
            f"read_file で内容を確認し、正確な文字列を指定してください。\n"
            f"近似箇所（先頭10行）:\n{block_preview}"
        )

    preview = search[:120].replace("\n", "↵")
    hint = f"\n最近似ブロック類似度: {best_ratio:.2f}（行 {best_i+1}–{best_i+best_n}）" if best_ratio > 0 else ""
    return (
        f"エラー: 指定された検索文字列がファイル内に見つかりません: {path}\n"
        f"検索対象: {preview}...\n{hint}\n"
        f"ヒント: read_file で現在の内容を確認し、正確な（特にインデントや改行を含む）文字列を指定してください。"
    )


# ── delegate_to_team / delegate_to_team_parallel ツール ───────
@tools.register(
    name="delegate_to_team",
    description=(
        "Researcher（調査・設計ワークフロー作成）→ Worker（実装）の順に実行し、"
        "変更を即時適用・AutoGitコミットして差分サマリをDirectorに返す委任ツール。"
        "verify_cmdを指定すると Worker 実行後に検証を実行し、失敗した場合は"
        "同じOverlay上で Worker が自動的に修正再試行する（最大3回）。"
        "verify_cmdを省略した場合でも Researcher が適切なテストコマンドを提案すれば自動採用される。"
        "【重要】指示文(task)は目的・対象範囲・制約条件を具体的に書くこと。"
        "Researcherが詳細調査・設計を行うため、ファイル単位の網羅的な事前調査は不要だが、"
        "曖昧な目的設定はResearcherの調査方向を誤らせる。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "task": {
                "type": "string",
                "description": "Workerへの具体的・詳細な指示（目的・対象範囲・制約条件を含む）",
            },
            "project_dir": {
                "type": "string",
                "description": "作業対象のプロジェクトディレクトリのフルパス（通常は現在の作業フォルダ）",
                "default": ".",
            },
            "verify_cmd": {
                "type": "string",
                "description": (
                    "Worker完了後に同じOverlay上で実行する検証コマンド（例: 'pytest tests/test_x.py -q'）。"
                    "失敗(exit!=0)の場合、出力をフィードバックとしてWorkerが修正再試行する（最大3回）。"
                    "省略時はResearcherが推奨コマンドを自動提案する場合がある。"
                ),
                "default": "",
            },
        },
        "required": ["task"],
    },
)
def delegate_to_team(task: str, project_dir: str = ".", verify_cmd: str = "") -> str:
    from .team import run_team_task, _get_team_config
    return run_team_task(task, project_dir, _get_team_config(), verify_cmd=verify_cmd)


@tools.register(
    name="delegate_to_worker",
    description=(
        "Researcherを介さず Worker だけを実行する軽量委任ツール。"
        "対象ファイル・変更内容が既に明確で自己完結している単純なタスク向け"
        "（例: 指定箇所の小さな修正、決まったコマンドの実行と結果確認）。"
        "verify_cmdを指定すると Worker 完了後に検証を実行し、失敗した場合は"
        "同じOverlay上で Worker が自動的に修正再試行する（最大3回）。"
        "調査が必要・複雑な変更には delegate_to_team を使うこと。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "task": {
                "type": "string",
                "description": "Workerへの具体的・詳細な指示（対象ファイル・変更内容を含む）",
            },
            "project_dir": {
                "type": "string",
                "description": "作業対象のプロジェクトディレクトリのフルパス（通常は現在の作業フォルダ）",
                "default": ".",
            },
            "verify_cmd": {
                "type": "string",
                "description": (
                    "Worker完了後に同じOverlay上で実行する検証コマンド（例: 'pytest tests/test_x.py -q'）。"
                    "失敗(exit!=0)の場合、出力をフィードバックとしてWorkerが修正再試行する（最大3回）。"
                ),
                "default": "",
            },
        },
        "required": ["task"],
    },
)
def delegate_to_worker(task: str, project_dir: str = ".", verify_cmd: str = "") -> str:
    from .team import run_worker_once, _get_team_config
    return run_worker_once(task, project_dir, _get_team_config(), verify_cmd=verify_cmd)


@tools.register(
    name="delegate_to_team_parallel",
    description=(
        "互いに依存しない複数のタスクを、それぞれ delegate_to_team と同じ"
        "Researcher→Worker パイプラインで並列実行する。"
        "各タスクの指示文(tasks)は事前に自分(Director)で調査し具体的に書くこと。"
        "【重要】tasks は必ず文字列の配列（list[str]）で渡すこと（例: [\"タスク1の説明\", \"タスク2の説明\"]）。"
        "1つのタスクを\"###\"等の区切りで連結した単一の文字列として渡してはならない"
        "（文字列を渡すと1文字ごとに大量のWorkerが起動してしまう）。要素数は最大10件まで。"
        "verify_cmdを指定すると、各タスクのWorker実行後に同じOverlay上でこのコマンドが実行され、"
        "失敗した場合は各Workerがそれぞれ自動修正再試行する（全タスク共通・最大3回）。"
        "省略時でも各タスクのResearcherが適切なコマンドを提案すれば自動採用される。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "tasks": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Workerチームに与えるタスク一覧（各要素が独立した自己完結タスクであること、最大10件）",
            },
            "project_dir": {
                "type": "string",
                "description": "作業対象のプロジェクトディレクトリのフルパス（通常は現在の作業フォルダ）",
                "default": ".",
            },
            "verify_cmd": {
                "type": "string",
                "description": "各タスクのWorker実行後に実行する検証コマンド（全タスク共通）。省略可。",
                "default": "",
            },
        },
        "required": ["tasks"],
    },
)
def delegate_to_team_parallel(tasks: list[str], project_dir: str = ".", verify_cmd: str = "") -> str:
    from .team import run_team_tasks_parallel, _get_team_config
    if isinstance(tasks, str):
        return ("エラー: tasks は文字列ではなく、文字列の配列（list[str]）で渡してください。"
                "例: [\"タスク1の説明\", \"タスク2の説明\"]")
    if not tasks:
        return "エラー: tasks が空です。"
    if len(tasks) > 10:
        return f"エラー: tasks が{len(tasks)}件あります。1回の呼び出しは10件以下に分割してください。"
    results = run_team_tasks_parallel(tasks, project_dir, _get_team_config(), verify_cmd=verify_cmd)
    blocks = []
    for i, r in enumerate(results, 1):
        blocks.append(f"── チーム {i}/{len(results)} ──\n{r}")
    return f"[delegate_to_team_parallel: {len(results)} 件完了]\n\n" + "\n\n".join(blocks)


@tools.register(
    name="delegate_research",
    description=(
        "外部の公式ドキュメント・仕様などを調べる「調べ物」を、フレッシュな文脈の調査役"
        "（Researcher）に委任し、調査結果（回答）だけを受け取る。"
        "複数回のweb_search/fetch_webpageが必要になりそうな調べ物は、自分(Director)で"
        "直接行わず必ずこれを使うこと。Web検索結果のページ内容や試行錯誤が自分の会話履歴に"
        "積み上がるのを防ぎ、その後のやり取りでのコンテキスト圧迫・劣化を避けられる。"
        "戻り値はユーザーへの回答としてそのまま提示してよい。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "question": {
                "type": "string",
                "description": "調べてほしいこと（ユーザーの質問の意図が伝わるように具体的に書く）",
            },
            "project_dir": {
                "type": "string",
                "description": "作業対象のプロジェクトディレクトリのフルパス（通常は現在の作業フォルダ）",
                "default": ".",
            },
        },
        "required": ["question"],
    },
)
def delegate_research(question: str, project_dir: str = ".") -> str:
    from .team import run_research_qa, _get_team_config
    return run_research_qa(question, project_dir, _get_team_config())


@tools.register(
    name="delegate_to_specialist",
    description=(
        "指定したロール説明を持つ専門家エージェントにタスクを委任する。"
        "ロールはDirectorが自由に定義できる"
        "（例: 'TypeScript型エラーの診断専門家'、'セキュリティレビュアー'、'テストコードライター'）。"
        "権限は3段階で、用途に合う最小権限を選ぶこと: デフォルト（読み取り専用の調査・レビュー）、"
        "can_execute=True（OverlayFS隔離内でテスト・ビルド等のコマンド実行可、変更は破棄）、"
        "can_write=True（OverlayFS隔離内で実装し、変更をプロジェクトへ適用・コミット）。"
        "Specialistモードでの標準の委任手段（直前のWorkerへの追加指示は continue_specialist を使う）。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "role": {
                "type": "string",
                "description": (
                    "専門家ロールの説明。「視点」「制約」「完了基準」の3要素を必ず含めること"
                    "（「完了基準」の明記がないと機械チェックで差し戻される）。"
                    "例: '視点: セキュリティ脆弱性の診断専門家。制約: コードの変更提案はしない。"
                    "完了基準: 認証・認可・入力検証の問題点を重大度付きで列挙できている'"
                ),
            },
            "task": {
                "type": "string",
                "description": "そのロールに実行させるタスク",
            },
            "expected_files": {
                "type": "array",
                "items": {"type": "string"},
                "description": (
                    "can_write=True のとき、変更を想定しているファイルのリスト（プロジェクト相対パス）。"
                    "指定すると、想定外のファイルが変更された場合にハーネスが警告を付与する。省略可。"
                ),
                "default": [],
            },
            "can_write": {
                "type": "boolean",
                "description": (
                    "Trueでファイル変更可能なWorker（OverlayFS隔離、変更は適用・コミットされる）、"
                    "False（デフォルト）で読み取り専用"
                ),
                "default": False,
            },
            "can_execute": {
                "type": "boolean",
                "description": (
                    "Trueで実行専用Worker（OverlayFS隔離内で run_bash 等のコマンド実行が可能だが、"
                    "ファイル変更はタスク終了後に破棄される）。テスト実行・ビルド・診断など"
                    "「実行はするが変更を残さない」タスク向け。can_write=True が優先される。"
                ),
                "default": False,
            },
            "project_dir": {
                "type": "string",
                "description": "作業ディレクトリ（デフォルト: カレント）",
                "default": ".",
            },
            "verify_cmd": {
                "type": "string",
                "description": (
                    "can_write=True / can_execute=True のとき、Worker実行後にOverlay上で実行する"
                    "検証コマンド（例: 'pytest tests/test_foo.py -q'）。"
                    "失敗した場合はWorkerが修正再試行する（最大3回）。"
                    "読み取り専用（両方False）の場合は無視される。省略可。"
                ),
                "default": "",
            },
        },
        "required": ["role", "task"],
    },
)
def delegate_to_specialist(role: str, task: str,
                            can_write: bool = False, can_execute: bool = False,
                            project_dir: str = ".", verify_cmd: str = "",
                            expected_files: Optional[list] = None) -> str:
    from .team import run_specialist_task, validate_specialist_role, _get_team_config
    role_error = validate_specialist_role(role)
    if role_error:
        return role_error
    return run_specialist_task(
        role, task, project_dir, _get_team_config(),
        can_write=can_write, can_execute=can_execute,
        label=role[:15], verify_cmd=verify_cmd,
        expected_files=list(expected_files or []),
    )


@tools.register(
    name="continue_specialist",
    description=(
        "直前の delegate_to_specialist(can_write=True) のWorkerに追加指示を出し、"
        "**前回の会話と作業状態を引き継いだまま**続きの作業をさせる。"
        "同じ問題の修正を繰り返す場合・前回の変更に対するフィードバック"
        "（エラーが出た、動かない等）を反映させる場合は、新しい delegate_to_specialist "
        "ではなくこちらを使うこと（毎回ゼロから経緯を説明し直す必要がなくなる）。"
        "保持されるセッションは最新1件のみで、/clear やモード切替で破棄される。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "task": {
                "type": "string",
                "description": (
                    "追加指示。前回の会話をWorkerが覚えているため、経緯の再説明は不要。"
                    "新しく判明した情報（エラーメッセージ・ユーザーのフィードバック等）を具体的に書く"
                ),
            },
            "verify_cmd": {
                "type": "string",
                "description": "検証コマンド（省略時は前回と同じものを使用）",
                "default": "",
            },
        },
        "required": ["task"],
    },
)
def continue_specialist(task: str, verify_cmd: str = "") -> str:
    from .team import run_specialist_continue
    return run_specialist_continue(task, verify_cmd=verify_cmd)


@tools.register(
    name="get_delegation_trace",
    description=(
        "delegate_to_team / delegate_to_worker の実行結果に含まれるtrace_idを指定し、"
        "そのWorkerが実際に行ったThought/Action/Observationの実行トレースを取得する。"
        "差分サマリだけでは判断が難しい場合に、Workerが本当に意図通りの手順で"
        "作業したかを検証する用途に使う。"
        "Researcher（delegate_research / delegate_to_team内の調査フェーズ）の"
        "トレースは対象外（調査結果は委任結果の中に既に含まれている）。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "trace_id": {
                "type": "string",
                "description": "delegate_to_team/delegate_to_workerの結果文字列に含まれる trace_id",
            },
            "max_steps": {
                "type": "integer",
                "description": "表示する最大ステップ数（デフォルト20）",
                "default": 20,
            },
        },
        "required": ["trace_id"],
    },
)
def get_delegation_trace(trace_id: str, max_steps: int = 20) -> str:
    from .viewer import get_session_trace_text
    if not _sessions_dir_for_tool or not _sessions_dir_for_tool.exists():
        return "セッションログがまだありません。"
    return get_session_trace_text(_sessions_dir_for_tool, trace_id, max_steps)


# ── search_history ツール ──────────────────────────────────────────
_sessions_dir_for_tool: "Optional[Path]" = None

def set_sessions_dir(path: "Path") -> None:
    global _sessions_dir_for_tool
    _sessions_dir_for_tool = path


@tools.register(
    name="search_history",
    description=(
        "過去のセッションログを検索し、ユーザー入力と回答を返す。"
        "以前のタスクの結果・知見を参照したいときや、作業を再開したいときに使う。"
        "query='' (空文字) にすると最新セッションから順に全件サマリを返す（作業再開時はまずこれを使うこと）。"
        "キーワードを指定すると内容で絞り込む。max_results は多めに指定してよい（デフォルト10）。"
    ),
    parameters={
        "type": "object",
        "properties": {
            "query":       {"type": "string", "description": "検索キーワード（空文字で最新N件をすべて返す）", "default": ""},
            "max_results": {"type": "integer", "description": "最大件数（デフォルト10）", "default": 10},
        },
        "required": [],
    }
)
def search_history(query: str = "", max_results: int = 10) -> str:
    from .commands import _search_sessions, _parse_session_file
    if not _sessions_dir_for_tool or not _sessions_dir_for_tool.exists():
        return "セッションログがまだありません。"

    # 空クエリ → 最新セッションから順にターン一覧を返す
    if not query.strip():
        jsonl_files = sorted(_sessions_dir_for_tool.glob("*.jsonl"), reverse=True)
        lines = [f"[search_history: 最新セッション一覧  {len(jsonl_files)}ファイル]\n"]
        shown = 0
        for jf in jsonl_files:
            s = _parse_session_file(jf)
            if not s:
                continue
            turns = s.get("turns", [])
            lines.append(f"=== {s['file']}  ({len(turns)} ターン  {s.get('model','')}) ===")
            for t in turns:
                user_preview = t["user"][:120].replace("\n", " ")
                ans_preview  = t.get("answer", "")[:120].replace("\n", " ")
                lines.append(f"  Q: {user_preview}")
                if ans_preview:
                    lines.append(f"  A: {ans_preview}")
                shown += 1
                if shown >= max_results:
                    lines.append(f"\n…（{max_results}件表示済み。さらに必要なら max_results を増やすか query で絞り込む）")
                    return "\n".join(lines)
            lines.append("")
        return "\n".join(lines)

    # キーワード検索
    hits = _search_sessions(_sessions_dir_for_tool, query, max_results=max_results)
    if not hits:
        return (
            f"「{query}」に一致するログが見つかりませんでした。\n"
            f"ヒント: query='' で最新セッションの全ターンを確認できます。"
        )
    lines = [f"[search_history: {query}] {len(hits)}件ヒット\n"]
    for i, h in enumerate(hits, 1):
        lines.append(f"--- [{i}] {h['file']}  {h['ts']}")
        lines.append(f"User: {h['full_user']}")
        if h["full_result"]:
            lines.append(f"Result: {h['full_result']}")
        lines.append("")
    return "\n".join(lines)


_pw_context: dict = {}  # {"playwright": ..., "browser": ..., "page": ...}
_pw_lock = threading.Lock()

def _get_browser_page():
    """Playwright ページを lazy init で返す。未インストール時は RuntimeError。"""
    with _pw_lock:
        if "page" not in _pw_context or _pw_context["page"].is_closed():
            try:
                from playwright.sync_api import sync_playwright
            except ImportError:
                raise RuntimeError(
                    "Playwright が未インストールです。\n"
                    "pip install playwright && playwright install chromium を実行してください。"
                )
            if "playwright" not in _pw_context:
                _pw_context["playwright"] = sync_playwright().start()
            if "browser" not in _pw_context or not _pw_context["browser"].is_connected():
                _pw_context["browser"] = _pw_context["playwright"].chromium.launch(headless=False)
            _pw_context["page"] = _pw_context["browser"].new_page()
        return _pw_context["page"]

@_browser_registry.register(
    name="browser_navigate",
    description="ブラウザで指定URLに遷移する。ログインページや動的サイトの操作に使用。",
    parameters={
        "type": "object",
        "properties": {
            "url": {"type": "string", "description": "遷移先のURL"},
            "wait_ms": {"type": "integer", "description": "遷移後の待機ミリ秒（デフォルト1000）", "default": 1000}
        },
        "required": ["url"]
    }
)
def browser_navigate(url: str, wait_ms: int = 1000) -> str:
    try:
        page = _get_browser_page()
        page.goto(url, timeout=30000)
        page.wait_for_timeout(wait_ms)
        return f"遷移完了: {page.url}\nタイトル: {page.title()}"
    except Exception as e:
        return f"browser_navigate エラー: {e}"

@_browser_registry.register(
    name="browser_click",
    description="CSSセレクタまたはテキストで要素をクリックする。ボタン・リンク・メニュー操作に使用。",
    parameters={
        "type": "object",
        "properties": {
            "selector": {"type": "string", "description": "CSSセレクタ（例: button#submit）またはテキスト（例: text=ログイン）"},
            "wait_ms": {"type": "integer", "description": "クリック後の待機ミリ秒（デフォルト500）", "default": 500}
        },
        "required": ["selector"]
    }
)
def browser_click(selector: str, wait_ms: int = 500) -> str:
    try:
        page = _get_browser_page()
        page.click(selector, timeout=10000)
        page.wait_for_timeout(wait_ms)
        return f"クリック完了: {selector}\n現在のURL: {page.url}"
    except Exception as e:
        return f"browser_click エラー: {e}"

@_browser_registry.register(
    name="browser_type",
    description="入力フィールドにテキストを入力する。フォーム記入・検索ボックス入力に使用。",
    parameters={
        "type": "object",
        "properties": {
            "selector": {"type": "string", "description": "入力先のCSSセレクタ（例: input[name=email]）"},
            "text": {"type": "string", "description": "入力するテキスト"},
            "clear_first": {"type": "boolean", "description": "入力前に既存テキストを消去するか（デフォルトtrue）", "default": True}
        },
        "required": ["selector", "text"]
    }
)
def browser_type(selector: str, text: str, clear_first: bool = True) -> str:
    try:
        page = _get_browser_page()
        if clear_first:
            page.fill(selector, text, timeout=10000)
        else:
            page.type(selector, text, timeout=10000)
        return f"入力完了: {selector} ← \"{text[:50]}\""
    except Exception as e:
        return f"browser_type エラー: {e}"

@_browser_registry.register(
    name="browser_get_text",
    description="ページ全体またはセレクタで指定した要素のテキストを取得する。",
    parameters={
        "type": "object",
        "properties": {
            "selector": {"type": "string", "description": "取得対象のCSSセレクタ（省略時はページ全体）"},
            "max_chars": {"type": "integer", "description": "最大取得文字数（デフォルト5000）", "default": 5000}
        }
    }
)
def browser_get_text(selector: str = "", max_chars: int = 5000) -> str:
    try:
        page = _get_browser_page()
        if selector:
            text = page.inner_text(selector, timeout=10000)
        else:
            text = page.inner_text("body", timeout=10000)
        truncated = text[:max_chars]
        suffix = f"\n... (全{len(text):,}文字中{max_chars:,}文字を表示)" if len(text) > max_chars else ""
        return f"[URL: {page.url}]\n{truncated}{suffix}"
    except Exception as e:
        return f"browser_get_text エラー: {e}"

@_browser_registry.register(
    name="browser_screenshot",
    description="現在のブラウザ画面のスクリーンショットをファイルに保存する。",
    parameters={
        "type": "object",
        "properties": {
            "path": {"type": "string", "description": "保存先ファイルパス（省略時は ./screenshot.png）"}
        }
    }
)
def browser_screenshot(path: str = "./screenshot.png") -> str:
    try:
        page = _get_browser_page()
        page.screenshot(path=path, full_page=True)
        return f"スクリーンショット保存: {path}\nURL: {page.url}"
    except Exception as e:
        return f"browser_screenshot エラー: {e}"

@_browser_registry.register(
    name="browser_close",
    description="ブラウザを閉じてリソースを解放する。セッション終了時に呼ぶ。",
    parameters={"type": "object", "properties": {}}
)
def browser_close() -> str:
    try:
        if "browser" in _pw_context and _pw_context["browser"].is_connected():
            _pw_context["browser"].close()
        if "playwright" in _pw_context:
            _pw_context["playwright"].stop()
        _pw_context.clear()
        return "ブラウザを閉じました。"
    except Exception as e:
        return f"browser_close エラー: {e}"

_BROWSER_TOOL_NAMES = [
    "browser_navigate", "browser_click", "browser_type",
    "browser_get_text", "browser_screenshot", "browser_close",
]

def enable_browser_tools() -> str:
    for name in _BROWSER_TOOL_NAMES:
        tools.copy_tool(name, _browser_registry)
    return f"ブラウザツール有効化 ({len(_BROWSER_TOOL_NAMES)} 本)"

def disable_browser_tools() -> str:
    for name in _BROWSER_TOOL_NAMES:
        tools.unregister(name)
    return "ブラウザツール無効化"

def browser_tools_enabled() -> bool:
    return "browser_navigate" in tools._tools


# ── Linux専用ツール（run_bash / run_pipeline 等）を登録 ──────────────
from . import tools_linux  # noqa: F401, E402
from . import pipeline     # noqa: F401, E402
